<?xml version="1.0" encoding="UTF-8" ?>
<!-- saved from url=(0014)about:internet -->

<!DOCTYPE site [
 <!ELEMENT site (topic+) >
  <!ELEMENT topic (title,url,content) >
   <!ELEMENT url (#PCDATA) >
   <!ELEMENT profiled (#PCDATA | profiled)* >
   <!ELEMENT title (#PCDATA | profiled)* >
   <!ELEMENT content (#PCDATA | profiled)* >
   <!ATTLIST topic profiles CDATA #IMPLIED >
   <!ATTLIST profiled profiles CDATA #IMPLIED >
]>

<site>
<topic>
  <title>Novell iFolder 3.8.4 Cross-Platform Help</title>
  <url>../bookinfo.html</url>
  <content>Novell iFolder 3.8.4 Cross-Platform Help 3.8.4 iFolder Help Novell iFolder is a file-sharing application for Linux, Windows, and Macintosh clients. With iFolder, your local files automatically follow you everywhere---online, offline, all the time---across computers. You can share files in multiple iFolders, each with different users. You control who can participate in an iFolder and their access rights to the files in it. You can also participate in iFolders that others share with you. This help system describes how to use and manage the iFolder client. Audience This guide is intended for users of the iFolder client. Additional Documentation If you are using the iFolder 3.7 or later client with a Novell iFolder 3.7 or later enterprise server or Web access server, see the iFolder 3.8.4 User Guide at the Novell iFolder Documentation Web site . </content>
</topic>

<topic>
  <title>Overview of iFolder</title>
  <url>../overview.html</url>
  <content>Overview of iFolder Novell iFolder is a file-sharing application for Linux, Windows, and Macintosh clients. You can share files in multiple iFolders, each with different users or LDAPGroups. You control who can participate in an iFolder and the access level for each member. You can also participate in iFolders that others share with you. iFolder provides you a simple, hassle-free user interface for client-side migration from iFolder 2. x to iFolder 3.6 and later, and for a client-side upgrade from iFolder 3. x to iFolder 3.6 and later. This section familiarizes you with the various benefits and features of iFolder: </content>
</topic>

<topic>
  <title>Benefits of iFolder</title>
  <url>../benefits.html</url>
  <content>Benefits of iFolder iFolder provides the following benefits: iFolder integrates with your native desktop environment, making it easy to create and manage multiple iFolders. iFolder is highly scalable and flexible, with no practical limit on the number of iFolders per user or on the number of members per iFolder. With encryption enabled, iFolder protects data as it travels across the wire and is stored on the iFolder server. With the enhanced Web Access console, you can access your files on the iFolder server from any workstation without the iFolder client, and use a Web browser to perform all the operations of iFolder client. You can easily and selectively share personal and business files. iFolder can migrate and upgrade your iFolder data to the latest version. iFolder supports LDAPGroups. You can share iFolders with LDAPGroups. Members of the LDAPGroup can create, own and share iFolders with other individual users or other LDAPGroups. You can control the access level of member users of the iFolders you own, or where you have the necessary rights to control the access rights of members. iFolder transparently updates your files to member iFolders on multiple workstations. When iFolder is running, it tracks and logs changes made while you work offline, and synchronizes those changes when you connect to the server. iFolder provides secure authentication of members who access an iFolder to synchronize its data. iFolders offers an alternative to exchanging files via e-mail, which avoids the file-size limits on e-mail attachments and reduces your e-mail storage requirements. </content>
</topic>

<topic>
  <title>The iFolder Client</title>
  <url>../bawqltp.html</url>
  <content>The iFolder Client The iFolder client integrates with your operating system to provide iFolder services in your native desktop environment. The iFolder client allows you to manage your own iFolders and to select which shared iFolders to set up on each computer. iFolder supports the following operating systems: SUSE Linux Enterprise Desktop 10 SP1, SP2, and SP3 SUSE Linux Enterprise Desktop 11 Windows Vista SP1 Windows XP SP2 and SP3 Windows 7 OpenSUSE 11.1 OpenSUSE 11.2 Apple Macintosh 10.4 and later </content>
</topic>

<topic>
  <title>iFolder Account</title>
  <url>../bawqmpe.html</url>
  <content>iFolder Account An iFolder account is created when an iFolder services administrator provisions you as an iFolder user for an iFolder server. The administrator provides you with a username and password. For an enterprise, this might be your username or e-mail address and the related password. You must configure at least one iFolder account before you can create iFolders. For more information, see . An iFolder session begins when you log in to an iFolder services account and ends when you log out, or when you exit the iFolder client. Your iFolders synchronize files with other active iFolders only when your session is active and you are working online. You can access data in your local iFolders at any time, whether you are logged in to the account, or not. For information, see . </content>
</topic>

<topic>
  <title>Cross-Platform Considerations</title>
  <url>../ovwxplat.html</url>
  <content>Cross-Platform Considerations The user interfaces for the Linux, Windows, and Macintosh versions of the iFolder client conform to interface conventions of their individual platforms. The way you perform common tasks is parallel in each platform, but you might observe slight differences in the buttons, the display area, function labels, the location of the desktop notification area, the start iFolder preference, and so on as you perform the tasks. Except where procedures differ explicitly, this guide provides instructions for only one of the three platforms. The following table lists some typical differences and similarities in the client interface: Task Linux Windows Macintosh iFolder menu Quit Exit Quit iFolder Preferences &gt; Accounts dialog Add button Add button Plus ( + ) button iFolder Preference Accounts dialog Remove button Remove button Minus ( - ) button Multiple locations Close button Actions are committed when you perform the action OK , Cancel , and Apply buttons Actions are committed only when you click Apply or OK OK and Cancel button Actions are committed when you perform the action iFolder Preferences dialog Add iFolder to the desktop’s Startup Programs Select (enable) Start iFolder when logging In to the desktop This feature is not available Configuring an iFolder Account Remember my password Remember password on this computer Remember Password Notification area Notification area Status and Notification area Notification area Right-click notification area Account Settings Accounts This feature is not available iFolders iFolder menu Properties Properties Get Info iFolder Wizards Forward button and Back button Next button and Back button No buttons to move front and back. You can configure your username, password and server in a single window. Configuring an iFolder Account iFolder Account Assistant iFolder Account Creation Wizard Preferences &gt; Account iFolder Server Configuration Wizard iFolder Server Choose an iFolder Server Not available iFolder Identity Configuration Wizard Identity iFolder Account Information Not available </content>
</topic>

<topic>
  <title>Key Features of iFolder</title>
  <url>../keyfeatures.html</url>
  <content>Key Features of iFolder Before you begin to use iFolder, it is important to understand the following key features: iFolder Sharing Typically, when you work in multiple locations or in collaboration with others, you must conscientiously manage file versions. With iFolder, the most recent version of your files can follow you to any computer where you have installed the iFolder client and created an iFolder for them. iFolder also allows you to share multiple iFolders and their separate content with other authorized users or LDAPGroups. For more information on shared iFolder, see . The iFolder client supports sharing by synchronizing files across multiple computers through a central server. It allows you to do the following: Share files across computers Share files with others Own multiple iFolders Participate in multiple iFolders that other users share with you Participate as the owner or a member of iFolders in multiple accounts You work with iFolders directly in your file manager or in the iFolder browser that is part of the client. Within the iFolder, you can set up any subdirectory structure that suits your personal or corporate work habits. The subdirectory structure is constant across all member iFolders. Shared iFolders An iFolder is a local directory that selectively shares and synchronizes files via a central server with user-specified users. The iFolder files are accessible to all iFolder members and can be changed by those with the rights to do so. You can access your iFolders across multiple workstations and share them with both individual users and LDAPGroups. You decide who participates in each iFolder and the level of access for each member. Similarly, you can participate in shared iFolders that are owned by others in your collaboration environment. When you share an iFolder, member users with the Write permission can modify the directory structure, and those changes apply to all copies of the iFolder. Each user can locate the shared iFolder anywhere on his or her own computer if it satisfies the requirements in . iFolder Access Rights The iFolder client supports the owner and three levels of access for members of an iFolder: Members of an LDAPGroup inherit the access rights set for that group. Owner: Only one user serves as the owner of an iFolder. This is typically the user who creates the iFolder. The owner user can use the iFolder client to transfer ownership to another member of the iFolder. The owner of an iFolder has the Full Control right. This user has Read/Write access to the iFolder, manages membership and access rights for member users, and can remove the Full Control right for any member. If an LDAPGroup owns an iFolders, all the member users of that group are given the full control right. Full Control: A member of the shared iFolder, with the Full Control access right. This member has Read/Write access to the iFolder and manages membership and access rights for all users except the owner. Read/Write: A member of the shared iFolder, with the Read/Write access right to the directories and files in the iFolder. This member can modify a file, but the local changes are synchronized to other members’ copies of the iFolder. Read Only: A member of the shared iFolder, with the Read Only access right to directories and files in the iFolder. This member can modify a file, but the local changes are not synchronized to other members’ copies of the iFolder. Any iFolder user or LDAPGroup can own some iFolders and be a member of other iFolders. As an owner user, you always have the Full Control right. As a member user, your level of access in each shared iFolder can differ, depending on the access granted to you by any member with the Full Control right. File Synchronization When you are connected to the server, iFolder can synchronize iFolder membership and files in the background as you work. When you set up an iFolder account, you can enable Remember My Password so that iFolder can remember the password on that machine, and next time when you launch iFolder, it is automatically connects to the server and synchronize the data without prompting for the password. You can configure the iFolder client to run automatically each time you log in to your computer’s desktop environment. The session runs in the background as you work with files in your local iFolders, tracking and logging any changes you make. You can synchronize the files manually or at specified intervals. iFolder also has delta synchronization capabilities. When you make any changes to an iFolder file, only the deltas or changes are synchronized to the server. In other words, delta synchronization only retrieves updates since the last synchronization between the iFolder client and the server. This increases the efficiency, because it reduces the synchronization time. Migration Novell iFolder provides a simple, hassle-free user interface for client-side migration from iFolder2.x to iFolder 3.6 and later. The Migration Wizard provided in the iFolder client helps you migrate the existing iFolder 2. x data to iFolder 3.6 and later quickly and easily. For more information, see . Encryption iFolder provides higher security for your confidential iFolder files, to protect them from intentional or unintentional access by unauthorized people. In the past, data security was not ensured on the server side, so the data was accessible to the administrator or to anyone who gained unauthorized access to the server. In addition, when you access iFolder files via an ISP provider, there is a chance that an unauthorized individual can inadvertently stumble across your confidential files. Now, you can encrypt and save your files on the server, and retrieve them through a passphrase known only to you. If you forget your passphrase, the Recovery agent you have selected during the creation of the encrypted iFolder helps you recover your data. Encrypted iFolders cannot be shared. For more information on encryption, see . Upgrade Novell iFolder provides a simple upgrade from iFolder 3. x to the iFolder client for Novell iFolder 3.6 and above versions. For more information, see . Merge With Merge, you can consolidate the iFolder data and minimize the data transfer between the iFolder client and the server. Merge also allows you to move an existing folder to a different location on the client machine. For more information, see . Default iFolder iFolder allows you to set up a default iFolder when you configure a new account. Whenever you configure a new iFolder account, iFolder automatically checks for the presence of the default iFolder. If you have not created a default iFolder, iFolder prompts you to create one. If it already exists, the iFolder client prompts you to download. You are also allowed to ignore both these options. For more information, see in the . Enhanced Web Access iFolder provides an enhanced Web interface that allows you to access your iFolder files on remote servers. With the Web Access console, you can use a Web browser to access your files on the iFolder server from any workstation without the iFolder client. The Web Access interface enables you to perform all the operations of the iFolder client. When compared to the previous iFolder versions, iFolder 3.6 and later versions lets you create, browse, share, upload and delete iFolders via the enhanced Web access console. Mobile users can also make use of this facility through the Web. Synchronization Log The synchronization log displays a log of your iFolder background activity, such as uploading and downloading files for different iFolders, policy violations, excluded files, and non-synchronized files. </content>
</topic>

<topic>
  <title>What’s Next</title>
  <url>../ovwnext.html</url>
  <content>What’s Next For information about configuring using the iFolder client, see the following: </content>
</topic>

<topic>
  <title>Managing iFolder Accounts and Preferences</title>
  <url>../accountsprefs.html</url>
  <content>Managing iFolder Accounts and Preferences This section discusses how to configure your iFolder accounts and how to manage preferences for the iFolder client. </content>
</topic>

<topic>
  <title>Starting the iFolder Client</title>
  <url>../startclient.html</url>
  <content>Starting the iFolder Client When iFolder is running, the iFolder Services icon appears in the notification area of the taskbar. iFolder is integrated in the desktop environment. The iFolder emblem (a green “i”) appears on iFolders when they are viewed in a file manager, on the desktop, or in the iFolder browser. The encrypted iFolder is indicated by the emblem (locked folder). The notification area of the taskbar must be enabled in order for the iFolder Services icon to be displayed when iFolder is running. You can work locally with files in your local iFolders at any time. Whenever the iFolder client is running, it logs the changes you make to local iFolder data as you work. If you make changes to local iFolder data when iFolder is not running, iFolder identifies and logs the differences the next time you start iFolder. When iFolder is not running, iFolders appear in the file manager or on the desktop. You can access files in your local copy of an iFolder, but you cannot manage iFolders. In addition, you must log in to an account to create an iFolder or synchronize its files. During account creation, user login happens through SSL. When you are prompted to accept the server certificate, you must validate the certificate and accept it for a successful connection. For information about stopping the iFolder client, see . Linux Starting iFolder Automatically on Login To enable iFolder to start automatically when you log in to the desktop, do one of the following: Open the applications menu, click More Applications , locate and right-click iFolder 3 , then select Add to Startup Programs from the menu. Make sure iFolder is running when you log out, then save the session setup. Select this session option when you log in to the desktop. Open a terminal window, log in as the root user, then run /opt/gnome/bin/gnome-session-properties to add iFolder as a program to start when you log in to your computer. To disable iFolder from starting automatically on login, do one of the following: Open the applications menu, locate and right-click iFolder 3 , then select Remove from Startup Programs . Make sure iFolder is not running when you log out, then save the session setup. Select this session option when you log in to the desktop. Starting iFolder Manually Log in to your computer with the local Linux user identity you want to use when you create iFolders. Use one of the following methods to start iFolder: In the taskbar, open the applications menu, click More Applications , locate iFolder 3 by searching or scrolling through the available options, right-click iFolder 3, then select Start iFolder 3 . Open a terminal shell, then enter /usr/bin/ifolder Windows Starting iFolder Automatically on Logon To start iFolder automatically when you log in to the desktop: Right-click the iFolder Services icon, then select Preferences to open the iFolder Preferences dialog box to the General tab. Select Start iFolder When logging in to the Desktop , then click Apply . Click OK to close the iFolders Preferences dialog box. To disable iFolder from starting automatically when you log on to the desktop: Right-click the iFolder Services icon, then select Preferences to open the iFolder Preferences dialog box to the General tab. Deselect Start iFolder When logging in to the Desktop , then click Apply . Click OK to close the iFolders Preferences dialog box. Starting iFolder Manually Log in to the computer with the local Windows user identity you want to use when you create iFolders. If iFolder does not start automatically on successful logon, start iFolder by clicking Start Programs iFolder 3 , then select the iFolder 3 Client application. Macintosh Starting iFolder Automatically on Login To enable iFolder to start automatically when you log in to your Macintosh computer, add iFolder to the Startup Items . Start iFolder. From the dock, right-click the iFolder icon and select the option Open at Login . or From the dock, press the Ctrl key, click the iFolder icon, then select Open at Login . To disable iFolder from starting automatically, remove iFolder from the Startup Items . From the dock, right-click the iFolder icon, and deselect Open at Login . or From the dock, right-click or Ctrl-click the iFolder icon, then deselect Open at Login. Starting iFolder Manually Log in to your computer with the local Macintosh user identity you want to use when you create iFolders. Use one of the following methods to start iFolder: Open the Applications directory on Macintosh HD , select Applications , then double-click iFolder 3 . Type iFolder in the spotlight (Apple button + Spacebar or click the magnifying glass icon on top right) then click the iFolder 3 under Applications. Open a terminal shell, log in as the root user, then enter /Applications/iFolder 3.app/Contents/MacOS/iFolder 3 </content>
</topic>

<topic>
  <title>Configuring an iFolder Account</title>
  <url>../accounts.html</url>
  <content>Configuring an iFolder Account Use the iFolder Account Creation Wizard to add and configure a new account. You must configure at least one iFolder account before you can create iFolders or share iFolders on your system. You can connect to the iFolder server with only one account at any given time. However, to connect to more than one iFolder servers, you can configure multiple accounts. You can log in separately to each account and be logged in concurrently to multiple accounts. Multiple users with different local login identities will have iFolders on the same computer. The first time you start iFolder under your current local login identity, iFolder prompts you to set up an iFolder account. iFolder 3.7 and later versions introduce a new feature, auto-account creation, which helps the iFolder administrator to create and configure an account for you. If your iFolder administrator has enabled auto-account creation, you don’t need to configure an account for yourself. When you start an iFolder for the first time, you are prompted to enter your password. Enter your password and complete configuring the account. To configure a new account: Access the iFolder Account Creation Wizard , using one of the following methods: The first time you start iFolder under your current local login identity, iFolder prompts you to set up an iFolder account. Click Forward to go directly to the iFolder Account Creation Wizard . Right-click the iFolder Services icon in the notification area, select Accounts to open the iFolder Preferences dialog box to the Accounts tab, then click Add to open the iFolder Account Creation Wizard . Follow the on-screen instructions to specify the following values: Parameter Description Server Address The DNS name or IP address of the iFolder enterprise server where you have an account. Get this information from your iFolder administrator. For example: svr21.example.com or 192.168.1.1 The server name is always displayed along with it’s IP address in the iFolder user interface. For example: iFolder - 192.168.1.1 You cannot use an iFolder 3.7 or later client to connect to an iFolder 3.2 server. Set this as my default server If you have multiple servers connected to your account, select the Set this as my default server check box to set the selected server from the drop-down list of servers as the default Server when you create or upload an ifolder. User Name Specify your user identity for this account. Your iFolder administrator decides whether the format you should use must be your network user ID (LDAP common name) or your e-mail address. For example, if your name is John Smith with a user ID of jsmith and an e-mail address of john.smith@example.com , your administrator configures a setting for the server that determines which of the two formats to accept in the Username field for authentication purposes. Password Specify the password for your username. Authentication happens through Secure channel (SSL). You are prompted to validate and accept the server certificate. Remember Password Select the Remember Password on this computer check box to log in automatically to this iFolder account whenever you log in to your computer. If your network password changes, automatic authentication fails gracefully the next time iFolder attempts to log in to the iFolder account. iFolder prompts you to log in with your new password and allows you to specify and save the new password. Verify the information entered by you. To make any changes, click the Back button and revisit the previous pages. Click Connect to proceed and validate your connection with the server. If you are prompted to Accept the certificate of this server , click Details to review the certificate information, then click OK to accept it. During the account creation, login happens through SSL. When you are prompted to accept the server certificate, you must validate the certificate and accept it for a successful connection. If the administrator has enabled the encryption policy , iFolder prompts you to enter your passphrase. Enter your passphrase in the Passphrase field. Re-enter the passphrase in Retype the passphrase field. Select Remember the Passphrase check box to automatically access the encrypted iFolder data during the current session. If you select this option, iFolder can remember your passphrase during the next login process. This passphrase exchange is done automatically. Select the desired Recovery agent from the list and click OK . Specify the location where you want to create the default iFolder. By default, the default iFolder is stored at &lt;users home directory&gt;/ifolder/server_name/user_name . Select the type of the Default iFolder that you want to create. If you choose Encryption , you will be prompted to provide the passphrase. You can share only the regular iFolders. Encrypted iFolders cannot be shared. If your iFolder administrator has not enabled encryption for your current account, you can create only regular iFolders, and if encryption is enabled, the Regular option is selected by default. Select Secure Sync to enable secure synchronization of files in the iFolder you are creating. You can enable secure channel for both regular and encrypted iFolders. With this option selected, iFolder allows you to use a secure channel to synchronize between iFolder on the server and on the local machine. If you remove the default iFolder on the server, the next time you configure the account from any thick client, iFolder prompts you to create a default iFolder again. However, if you remove the default iFolder from the local machine, the next time you configure the account, iFolder prompts you to download the default iFolder. If you have already set up a default iFolder, you can download it to your local machine. Download the default iFolder and click Next to proceed. If a folder with the same name as the default ifolder already exists on your system, you are prompted to either merge the two folders or download the default ifolder to a different location. Click OK to merge the two folders or click Cancel to download the default iFolder to a different location Click Finish to close the iFolder Account Creation Wizard. iFolder synchronizes the user list for the specified account and identifies iFolders that are available for download. This initial download can take a few seconds to a few minutes, depending on the size of the user list for the account. Verify that the account you set up appears in the list of accounts. Right-click the iFolder Services icon in the notification area, then select Preferences from the menu to open the iFolder Preferences dialog box to the Accounts tab. When you are connected to the iFolder server, the Online check box is selected. Close the iFolder Preferences dialog box. Set up iFolders for the account using either of these methods: Right-click the iFolder Services icon in the notification area, then select iFolders to open the iFolder browser. Continue with . If iFolders for this account are available for download from the server, they are listed on the iFolder window under iFolders on &lt; iFolder_server_name &gt;. The download icon indicates that the iFolder is available for download. Continue with . </content>
</topic>

<topic>
  <title>Logging In to an iFolder Account</title>
  <url>../login.html</url>