<?xml version="1.0" encoding="UTF-8" ?>
<!-- saved from url=(0014)about:internet -->

<!DOCTYPE site [
 <!ELEMENT site (topic+) >
  <!ELEMENT topic (title,url,content) >
   <!ELEMENT url (#PCDATA) >
   <!ELEMENT profiled (#PCDATA | profiled)* >
   <!ELEMENT title (#PCDATA | profiled)* >
   <!ELEMENT content (#PCDATA | profiled)* >
   <!ATTLIST topic profiles CDATA #IMPLIED >
   <!ATTLIST profiled profiles CDATA #IMPLIED >
]>

<site>
<topic>
  <title>Novell iFolder 3.9 Plattformübergreifende Hilfe</title>
  <url>../bookinfo.html</url>
  <content>Novell iFolder 3.9 Plattformübergreifende Hilfe 3.9 Hilfe zu iFolder Novell iFolder ist eine Dateifreigabe-Anwendung für Linux-, Windows- und Macintosh-Clients. Dank iFolder stehen Ihnen Ihre lokalen Dateien automatisch auf allen Computern zur Verfügung – online, offline, jederzeit. Sie können Dateien in mehreren iFolder-Ordnern freigeben, von denen jeder einem anderen Benutzer zugehörig ist. Sie können steuern, welche Benutzer einen iFolder-Ordner nutzen dürfen und über welche Zugriffsrechte diese Benutzer für die in diesem Ordner enthaltenen Dateien verfügen. Sie können zudem iFolder-Ordner nutzen, die andere Benutzer für Sie freigeben. In dieser Hilfe wird erläutert, wie der iFolder-Client verwendet und verwaltet wird. Zielgruppe Dieses Handbuch richtet sich an Benutzer des iFolder-Clients. Zusätzliche Dokumentation Wenn Sie den iFolder-Client der Version 3.7 oder höher mit einem Novell iFolder-Enterprise 3.7 (oder höher)-Server oder -Webzugriffsserver verwenden, finden Sie weitere Informationen in der iFolder 3.9-Benutzeranleitung auf der Novell iFolder-Dokumentationswebsite . </content>
</topic>

<topic>
  <title>Übersicht über iFolder</title>
  <url>../overview.html</url>
  <content>Übersicht über iFolder Novell iFolder ist eine Dateifreigabe-Anwendung für Linux-, Windows- und Macintosh-Clients. Sie können Dateien in mehreren iFolder-Ordnern freigeben, zu denen jeweils andere Benutzer oder LDAP-Gruppen gehören. Sie können steuern, welche Benutzer einen iFolder-Ordner nutzen dürfen und welche Zugriffsstufe den einzelnen Mitgliedern zugewiesen wird. Sie können zudem iFolder-Ordner nutzen, die andere Benutzer für Sie freigeben. iFolder stellt Ihnen eine einfache, problemlose Benutzerschnittstelle für die clientseitige Migration von iFolder 2. x auf iFolder 3.6 und höher bereit sowie für ein clientseitiges Upgrade von iFolder 3. x auf iFolder 3.6 und höher. In diesem Abschnitt wird näher auf die unterschiedlichen Vorteile und Funktionen von iFolder eingegangen: </content>
</topic>

<topic>
  <title>Vorteile von iFolder</title>
  <url>../benefits.html</url>
  <content>Vorteile von iFolder iFolder bietet folgende Vorteile: iFolder kann in Ihre systemeigene Desktop-Umgebung integriert werden und ermöglicht so die einfache Erstellung und Verwaltung mehrerer iFolder-Ordner. iFolder weist ein hohes Maß an Skalierbarkeit und Flexibilität auf, d. h., die Anzahl der iFolder-Ordner pro Benutzer bzw. die Anzahl der Mitglieder pro iFolder-Ordner ist nahezu unbegrenzt. Wenn die Verschlüsselung aktiviert ist, schützt iFolder Ihre Daten bei der Übertragung und bei der Speicherung auf dem iFolder-Server. Mit der verbesserten Webzugriffskonsole können Sie von einer Arbeitsstation aus ohne iFolder-Client auf Ihre Dateien auf dem iFolder-Server zugreifen und mithilfe eines Webbrowsers alle Operationen auf dem iFolder-Client durchführen. Sie können auf einfache Weise ausgewählte persönliche und berufliche Dateien freigeben. iFolder kann Ihre iFolder-Daten zur aktuellen Version migrieren und upgraden. iFolder unterstützt LDAP-Gruppen. Sie können iFolder-Ordner für LDAP-Gruppen freigeben. Mitglieder der LDAP-Gruppen können iFolder-Ordner erstellen, besitzen und für andere Einzelbenutzer oder andere LDAP-Gruppen freigeben. Sie können die Zugriffsstufe von Benutzern steuern, die Mitglieder der iFolder-Ordner sind, deren Eigentümer Sie sind bzw. für die Sie über die erforderlichen Rechte zur Steuerung der Zugriffsrechte von Mitgliedern verfügen. iFolder führt transparente Aktualisierungen Ihrer Dateien für iFolder-Mitgliederordner auf mehreren Arbeitsstationen durch. Wenn iFolder ausgeführt wird, werden Änderungen, die Sie offline vornehmen, überwacht und protokolliert. Außerdem werden diese Änderungen synchronisiert, wenn Sie eine Verbindung zum Server herstellen. iFolder stellt eine sichere Authentifizierung für Mitglieder bereit, die zum Synchronisieren der Daten auf einen iFolder-Ordner zugreifen. iFolder bietet eine Alternative zum Austausch von Dateien per Email, auf diese Weise müssen für Email-Anlagen geltende Größenbeschränkungen nicht mehr berücksichtigt und weniger Speicherplatz für Emails bereitgestellt werden. </content>
</topic>

<topic>
  <title>iFolder-Client</title>
  <url>../bawqltp.html</url>
  <content>iFolder-Client Der iFolder-Client wird im Betriebssystem integriert, um iFolder-Dienste in Ihrer Desktop-Umgebung bereitzustellen. Mit dem iFolder-Client können Sie Ihre eigenen iFolder-Ordner verwalten und auswählen, welche freigegebenen iFolder-Ordner auf dem jeweiligen Computer eingerichtet werden. iFolder unterstützt folgende Betriebssysteme: SUSE Linux Enterprise Desktop (SLED) 10 , SP3 64-Bit-SUSE Linux Enterprise Desktop (SLED) 11 SP1 openSUSE 11.4 Für den iFolder-Linux-Client ist das Mono-Framework für Linux und das Nautilus-Plugin für die GNOME Desktop-iFolder-Unterstützung erforderlich. 32-Bit-Windows XP SP3 Windows Vista SP1 Windows 7 32-Bit-Macintosh OS X (Intel-Architektur) v10.5 und höher (erfordert Mono 2.4.2.3). PowerPc-Architektur wird nicht unterstützt. </content>
</topic>

<topic>
  <title>iFolder-Konto</title>
  <url>../bawqmpe.html</url>
  <content>iFolder-Konto Ein iFolder-Konto wird erstellt, wenn ein iFolder-Dienstadministrator Sie als iFolder-Benutzer für einen iFolder-Server einrichtet. Der Administrator stellt Ihnen einen Benutzernamen und ein Passwort bereit. In einem Unternehmen kann es sich dabei um Ihren Benutzernamen oder Ihre E-Mail-Adresse und das zugehörige Passwort handeln. Vor der Erstellung von iFolder-Ordnern muss mindestens ein iFolder-Konto konfiguriert werden. Weitere Informationen finden Sie unter . Eine iFolder-Sitzung beginnt, wenn Sie sich bei einem iFolder-Servicekonto anmelden, und endet, wenn Sie sich abmelden oder den iFolder-Client beenden. Ihre iFolder-Ordner werden nur mit anderen aktiven iFolder-Ordnern synchronisiert, wenn Ihre Sitzung aktiv ist und Sie online arbeiten. Sie können jederzeit auf die in Ihren lokalen iFolder-Ordnern enthaltenen Daten zugreifen, egal, ob Sie beim jeweiligen Konto angemeldet sind oder nicht. Informationen hierzu erhalten Sie unter . </content>
</topic>

<topic>
  <title>Plattformübergreifende Überlegungen</title>
  <url>../ovwxplat.html</url>
  <content>Plattformübergreifende Überlegungen Die Benutzeroberflächen für die Linux-, Windows- und Macintosh-Version des iFolder-Client entsprechen den Oberflächenkonventionen ihrer jeweiligen Plattform. Allgemeine Aufgaben werden auf jeder Plattform auf dieselbe Weise ausgeführt, bei der Arbeit fallen Ihnen jedoch möglicherweise geringfügige Abweichungen hinsichtlich Schaltflächen, Anzeigebereich, Funktionsbezeichnungen, Position des Desktop-Benachrichtigungsbereichs, Einstellung für das Starten von iFolder usw. auf. Mit Ausnahme der Fälle, in denen es zu deutlichen Abweichungen in der Vorgehensweise kommt, enthält dieses Handbuch nur Anweisungen für eine der drei Plattformen. In der folgenden Tabelle werden einige typische Unterschiede und Gemeinsamkeiten der Client-Oberflächen erläutert: Job Linux Windows Macintosh iFolder-Menü Beenden Beenden Beenden iFolder-Einstellungen &gt; Konten-Dialogfeld Schaltfläche Hinzufügen Schaltfläche Hinzufügen Plus -Schaltfläche ( + ) iFOLDER-Einstellungen Konten-Dialogfeld Schaltfläche Entfernen Schaltfläche Entfernen Minus -Schaltfläche ( - ) Verschiedene Orte Schaltfläche Schließen Aktionen werden übernommen, wenn Sie die Aktion durchführen Schaltflächen OK , Abbrechen und Übernehmen Aktionen werden nur übernommen, wenn Sie auf Übernehmen oder OK klicken Schaltflächen OK und Abbrechen Aktionen werden übernommen, wenn Sie die Aktion durchführen Dialogfeld iFolder-Einstellungen Fügen Sie iFolder zu den Startprogrammen des Desktops hinzu. Aktivieren Sie iFolder starten, wenn Anmeldung am Desktop erfolgt . Diese Funktion ist nicht verfügbar. Konfigurieren von iFolder-Konten Passwort nicht vergessen Passwort auf diesem Computer nicht vergessen Passwort speichern Benachrichtigungsbereich Benachrichtigungsbereich Status- und Benachrichtigungsbereich Benachrichtigungsbereich Mit der rechten Maustaste in den Benachrichtigungsbereich klicken Kontoeinstellungen Konten Diese Funktion ist nicht verfügbar. iFolder-Ordner Menü iFolder Eigenschaften Eigenschaften Informationen iFolder-Assistenten Schaltflächen Weiter und Zurück Schaltflächen Weiter und Zurück Keine Schaltflächen für die Navigation vor und zurück Sie können Ihren Benutzernamen, Ihr Passwort und den Server in einem einzigen Fenster konfigurieren. Konfigurieren von iFolder-Konten iFolder-Kontoassistent iFolder-Kontoerstellungs-Assistent Einstellungen &gt; Konto iFolder-Serverkonfigurations-Assistent iFolder Server Auswählen eines iFolder-Servers Nicht verfügbar iFolder-Identitätskonfigurations-Assistent Identität iFolder-Kontoinformationen Nicht verfügbar </content>
</topic>

<topic>
  <title>Wichtigste Funktionen von iFolder</title>
  <url>../keyfeatures.html</url>
  <content>Wichtigste Funktionen von iFolder Vor der Arbeit mit iFolder sollten Sie sich unbedingt mit folgenden wichtigen Funktionen vertraut machen: iFolder-Freigabe Wenn Sie an unterschiedlichen Orten tätig sind oder mit anderen zusammenarbeiten, ist die gewissenhafte Verwaltung von Dateiversionen unerlässlich. Mit iFolder können Sie die aktuellen Versionen Ihrer Dateien auf alle Computer mitnehmen, auf denen Sie den iFolder-Client installiert und einen iFolder-Ordner für diese Dateien erstellt haben. Mit iFolder können Sie außerdem mehrere iFolder-Ordner und die jeweiligen Inhalte für andere autorisierte Benutzer und LDAP-Gruppen freigeben. Weitere Informationen zu freigegebenen iFolder-Ordnern finden Sie unter . Der iFolder-Client unterstützt die Freigabe, indem von einem zentralen Server aus Dateien auf mehreren Computern synchronisiert werden. Außerdem können Sie: Dateien für mehrere Computer freigeben Dateien für andere Benutzer freigeben Eigentümer mehrerer iFolder-Ordner sein Mehrere iFolder-Ordner nutzen, die andere Benutzer für Sie freigeben Als Eigentümer oder Mitglied iFolder-Ordner mehrerer Konten nutzen Sie arbeiten mit iFolder-Ordnern direkt in Ihrem Dateimanager oder im iFolder-Browser, der Teil des Client ist. Innerhalb des iFolder-Ordners können Sie eine beliebige Struktur von Unterverzeichnissen erstellen, die Ihren persönlichen Gewohnheiten und den Bedürfnissen Ihres Unternehmens entspricht. Die Unterverzeichnisstruktur ist in allen iFolder-Mitgliedsordnern gleich. Freigegebene iFolder-Ordner Bei einem iFolder-Ordner handelt es sich um ein lokales Verzeichnis, das über einen zentralen Server die Freigabe und Synchronisierung von Dateien für eine benutzerdefinierte Gruppe von Benutzern vornimmt. Sämtliche iFolder-Mitglieder können auf die iFolder-Dateien zugreifen; Änderungen können von denjenigen Mitgliedern vorgenommen werden, die hierzu berechtigt sind. Sie können auf Ihre iFolder-Ordner über mehrere Arbeitsstationen zugreifen und diese sowohl für einzelne Benutzer als auch für LDAP-Gruppen freigeben. Sie steuern, welche Benutzer den jeweiligen iFolder-Ordner nutzen dürfen und welche Zugriffsstufe den einzelnen Mitgliedern zugewiesen wird. Ebenso können Sie freigegebene iFolder-Ordner nutzen, die sich im Besitz anderer Benutzer in Ihrer für die Zusammenarbeit konfigurierten Umgebung befinden. Wenn Sie einen iFolder-Ordner freigeben, können Mitglieder mit Schreibberechtigung die Verzeichnisstruktur bearbeiten und die vorgenommenen Änderungen haben für alle Kopien des iFolder-Ordners Gültigkeit. Jeder Benutzer kann den freigegebenen iFolder-Ordner an einem von ihm ausgewählten Ort speichern, sofern dieser die Anforderungen in erfüllt. iFolder-Zugriffsrechte Der iFolder-Client unterstützt das Eigentümer-Attribut sowie drei Zugriffsstufen für Mitglieder eines iFolder-Ordners: Mitglieder einer LDAP-Gruppe erben die für diese Gruppe festgelegten Zugriffsrechte. Eigentümer: Nur ein einziger Benutzer fungiert als Eigentümer eines iFolder-Ordners. Hierbei handelt es sich normalerweise um den Benutzer, der den iFolder-Ordner erstellt hat. Der Benutzer mit Eigentümer-Attribut kann über den iFolder-Client das Eigentum auf ein anderes Mitglied des iFolder-Ordners übertragen. Der Eigentümer eines iFolder-Ordners verfügt über das Recht "Vollständige Kontrolle". Dieser Benutzer verfügt über den Lese-/Schreibzugriff für den jeweiligen iFolder-Ordner, verwaltet die Mitgliedschaft sowie die Zugriffsrechte der Mitglieder und kann das Recht "Vollständige Kontrolle" für jedes Mitglied aufheben. Wenn eine LDAP-Gruppe einen iFolder-Ordner besitzt, besitzen alle Mitglieder der Gruppe das Recht "Vollständige Kontrolle". Vollständige Kontrolle: Ein Mitglied des freigegebenen iFolder-Ordners mit dem Zugriffsrecht "Vollständige Kontrolle". Dieses Mitglied verfügt über den Lese-/Schreibzugriff für den jeweiligen iFolder-Ordner, verwaltet die Mitgliedschaft sowie die Zugriffsrechte für alle Benutzer mit Ausnahme des Eigentümers. Lesen/Schreiben: Ein Mitglied des freigegebenen iFolder-Ordners mit dem Zugriffsrecht "Lesen/Schreiben" für die Verzeichnisse und Dateien im iFolder-Ordner. Dieses Mitglied kann eine Datei bearbeiten, die lokalen Änderungen werden jedoch mit den Kopien des iFolder-Ordners anderer Mitglieder synchronisiert. Nur Lesen: Ein Mitglied des freigegebenen iFolder-Ordners, mit dem Zugriffsrecht "Nur Lesen" für Verzeichnisse und Dateien im iFolder-Ordner. Dieses Mitglied kann eine Datei bearbeiten, die lokalen Änderungen werden jedoch nicht mit den Kopien des iFolder-Ordners anderer Mitglieder synchronisiert. Jeder iFolder-Benutzer und jede LDAP-Gruppe kann Eigentümer einiger iFolder-Ordner und Mitglied anderer iFolder-Ordner sein. Als Benutzer mit Eigentümer-Attribut verfügen Sie stets über das Recht "Vollständige Kontrolle". Als Benutzer mit Mitglied-Attribut verfügen Sie in jedem freigegebenen iFolder-Ordner möglicherweise über eine andere Zugriffsstufe, abhängig davon, welche Zugriffsrechte Ihnen ein Mitglied erteilt hat, das über das Recht "Volle Kontrolle" verfügt. Dateisynchronisierung Wenn Sie mit dem Server verbunden sind, kann iFolder die iFolder-Mitgliedschaft und -Dateien, während Sie arbeiten, im Hintergrund synchronisieren. Wenn Sie ein iFolder-Konto einrichten, können Sie Passwort nicht vergessen aktivieren, sodass iFolder das Passwort auf dem Computer speichern kann. Wenn Sie iFolder das nächste Mal starten, wird die Verbindung zum Server automatisch hergestellt und die Daten werden ohne erneute Angabe des Passworts synchronisiert. Sie können den iFolder-Client so konfigurieren, dass er jedes Mal automatisch ausgeführt wird, wenn Sie sich bei der Desktop-Umgebung Ihres Computers anmelden. Die Sitzung wird im Hintergrund ausgeführt, während Sie mit Dateien in Ihren lokalen iFolder-Ordnern arbeiten; dabei werden sämtliche von Ihnen vorgenommenen Änderungen verfolgt und protokolliert. Sie können die Dateien manuell oder in angegebenen Intervallen synchronisieren. iFolder verfügt über Delta-Synchronisierungsfähigkeiten. Wenn Sie Änderungen an einer iFolder-Datei vornehmen, werden nur die Deltas und Änderungen mit dem Server synchronisiert. In anderen Worten: Die Deltasynchronisierung ruft nur Aktualisierungen nach der letzten Synchronisierung zwischen dem iFolder-Client und dem Server ab. Auf diese Weise wird die Effizienz gesteigert, da die Synchronisierungszeit reduziert wird. Migration Novell iFolder bietet eine einfache, benutzerfreundliche Schnittstelle für die clientseitige Migration von iFolder2.x auf iFolder 3.6 und höher. Der auf dem iFolder-Client bereitgestellte Migrationsassistent hilft bei der schnellen und einfachen Migration der bestehenden iFolder 2. x -Daten auf iFolder 3.6 und höher. Weitere Informationen finden Sie unter . Verschlüsselung iFolder bietet höhere Sicherheit für Ihre vertraulichen iFolder-Dateien, um sie vor absichtlichem oder versehentlichem Zugriff durch unautorisierte Personen zu schützen. In der Vergangenheit wurde die Datensicherheit nicht auf Serverseite sichergestellt, sodass der Administrator oder Personen mit unautorisiertem Zugriff auf den Server auf die Daten zugreifen konnten. Außerdem besteht beim Zugriff auf iFolder-Dateien über einen ISP-Anbieter die Möglichkeit, dass eine unautorisierte Person unabsichtlich auf vertrauliche Dateien stoßen kann. Jetzt können Sie Ihre Dateien auf dem Server verschlüsseln und speichern sowie durch einen Passwortsatz abrufen, der nur Ihnen bekannt ist. Wenn Sie den Passwortsatz vergessen, hilft Ihnen der Wiederherstellungsagent, den Sie bei der Erstellung des verschlüsselten iFolder-Ordners ausgewählt haben, beim Wiederherstellen Ihrer Daten. Verschlüsselte iFolder-Ordner können nicht freigegeben werden. Weitere Informationen zur Verschlüsselung finden Sie unter . Upgrade Novell iFolder ermöglicht ein einfaches Upgrade von iFolder 3. x auf den iFolder-Client für Novell iFolder 3.6 und höhere Versionen. Weitere Informationen finden Sie unter . Zusammenführen Mithilfe der Funktion "Zusammenführen" können Sie die Daten in den iFolder-Ordnern konsolidieren und den Datentransfer zwischen dem iFolder-Client und dem Server minimieren. Mithilfe von "Zusammenführen" können Sie außerdem einen vorhandenen Ordner an eine andere Position auf dem Client-Computer verschieben. Weitere Informationen finden Sie unter . Standard-iFolder-Ordner iFolder ermöglicht Ihnen das Einrichten eines Standard-iFolder-Ordners beim Konfigurieren eines neuen Kontos. Immer wenn Sie ein neues iFolder-Konto konfigurieren, überprüft iFolder automatisch das Vorhandensein eines Standard-iFolder-Ordners. Falls Sie einen solchen Ordner noch nicht erstellt haben, fordert Sie iFolder zum Erstellen auf. Wenn er bereits vorhanden ist, fordert Sie der iFolder-Client zum Herunterladen auf. Sie können diese beiden Optionen auch ignorieren. Weitere Informationen hierzu finden Sie in in . Verbesserter Webzugriff iFolder bietet eine verbesserte Webschnittstelle, mit der Sie auf Ihre iFolder-Dateien auf Remoteservern zugreifen können. Mit der Webzugriffskonsole können Sie einen Webbrowser für den Zugriff auf Ihre Dateien auf dem iFolder-Server von allen Arbeitsstationen ohne iFolder-Client aus verwenden. Die Benutzeroberfläche für den Webzugriff ermöglicht Ihnen das Ausführen aller Vorgänge des iFolder-Clients. Im Vergleich zu den vorherigen iFolder-Versionen können Sie mit iFolder 3.6 und späteren Versionen iFolder-Ordner über die verbesserte Webzugriffskonsole erstellen, durchsuchen, freigeben, hochladen und löschen. Mobile Benutzer können diese Fähigkeit auch über das Web nutzen. Synchronisierungsprotokoll Aus dem Synchronisierungsprotokoll gehen die im Hintergrund ausgeführten iFolder-Aktivitäten hervor, beispielsweise das Herauf- und Herunterladen von Dateien für unterschiedliche iFolder-Ordner, Richtlinienverletzungen, ausgeschlossene Dateien und nicht synchronisierte Dateien. </content>
</topic>

<topic>
  <title>Weitere Schritte</title>
  <url>../ovwnext.html</url>
  <content>Weitere Schritte Weitere Informationen zum Konfigurieren des iFolder-Clients finden Sie unter: </content>
</topic>

<topic>
  <title>Verwalten von iFolder-Konten und Benutzerkonten und -einstellungen</title>
  <url>../accountsprefs.html</url>
  <content>Verwalten von iFolder-Konten und Benutzerkonten und -einstellungen In diesem Abschnitt werden die Konfiguration der iFolder-Konten und die Verwaltung von Einstellungen für den iFolder-Client erläutert. </content>
</topic>

<topic>
  <title>Starten des iFolder-Clients</title>
  <url>../startclient.html</url>
  <content>Starten des iFolder-Clients Wenn iFolder ausgeführt wird, wird das iFolder-Dienstesymbol im Benachrichtigungsbereich der Taskleiste angezeigt. iFolder wird in die Desktop-Umgebung integriert. Das iFolder-Emblem (ein grünes "i") erscheint auf iFolder-Ordnern, wenn diese in einem Dateimanager, auf dem Desktop oder im iFolder-Browser dargestellt werden. Der verschlüsselte iFolder-Ordner wird durch das Emblem (Ordner mit Schloss) dargestellt. Der Benachrichtigungsbereich auf der Taskleiste muss aktiviert sein, damit das iFolder-Dienstesymbol angezeigt wird, wenn iFolder ausgeführt wird. Sie können jederzeit lokal mit Dateien in Ihren lokalen iFolder-Ordnern arbeiten. Wenn der iFolder-Client ausgeführt wird, werden die Änderungen protokolliert, die Sie beim Arbeiten an den lokalen iFolder-Daten vornehmen. Wenn Sie Änderungen an lokalen iFolder-Daten vornehmen, während iFolder nicht ausgeführt wird, identifiziert und protokolliert iFolder die Unterschiede, wenn Sie iFolder zum nächsten Mal starten. Wenn iFolder nicht ausgeführt wird, werden iFolder-Ordner im Dateimanager oder auf dem Desktop angezeigt. Sie können auf Dateien in Ihrer lokalen Kopie eines iFolder-Ordners zugreifen, können iFolder-Ordner aber nicht verwalten. Außerdem müssen Sie sich bei einem Konto anmelden, um einen iFolder-Ordner zu erstellen oder seine Dateien zu synchronisieren. Während der Kontenerstellung erfolgt die Benutzeranmeldung über SSL. Wenn Sie aufgefordert werden, das Serverzertifikat zu akzeptieren, müssen Sie das Zertifikat bestätigen und akzeptieren, damit eine erfolgreiche Verbindung möglich ist. Informationen zum Stoppen des iFolder-Clients finden Sie in . Linux Automatisches Starten von iFolder bei der Anmeldung Um den automatischen Start von iFolder beim Anmelden am Desktop zu aktivieren, führen Sie einen der folgenden Schritte aus: Öffnen Sie das Anwendungsmenü, klicken Sie auf Weitere Anwendungen , suchen und klicken Sie mit der rechten Maustaste auf iFolder 3 und wählen Sie dann aus dem Menü Startprogrammen hinzufügen aus. Stellen Sie sicher, dass iFolder beim Abmelden ausgeführt wird, und speichern Sie dann das Sitzungssetup. Wählen Sie diese Sitzungsoption aus, wenn Sie sich am Desktop anmelden. Öffnen Sie ein Terminal-Fenster, melden Sie sich als Benutzer root an und führen Sie dann /opt/gnome/bin/gnome-session-properties aus, um iFolder als Programm hinzuzufügen, das bei Ihrer Anmeldung gestartet werden soll. Führen Sie einen der folgenden Schritte aus, um den automatischen Start von iFolder bei der Anmeldung zu deaktivieren: Öffnen Sie das Anwendungsmenü, suchen und klicken Sie mit der rechten Maustaste auf iFolder 3 und wählen Sie dann Aus Startprogrammen entfernen aus. Stellen Sie sicher, dass iFolder beim Abmelden nicht ausgeführt wird, und speichern Sie dann das Sitzungssetup. Wählen Sie diese Sitzungsoption aus, wenn Sie sich am Desktop anmelden. Manuelles Starten von iFolder Melden Sie sich unter der lokalen Linux-Benutzeridentität, mit der Sie iFolder-Ordner erstellen möchten, bei Ihrem Computer an. Wählen Sie zum Starten von iFolder eine der folgenden Vorgehensweisen: Öffnen Sie das Anwendungsmenü in der Taskleiste, klicken Sie auf Weitere Anwendungen , suchen Sie iFolder 3 , indem Sie durch die verfügbaren Optionen blättern, klicken Sie mit der rechten Maustaste auf "iFolder 3" und wählen Sie dann iFolder 3 starten aus. Öffnen Sie eine Terminal-Shell und geben Sie Folgendes ein: /usr/bin/ifolder Windows Automatisches Starten von iFolder bei der Anmeldung So starten Sie iFolder bei der Anmeldung am Desktop automatisch: Klicken Sie mit der rechten Maustaste auf das iFolder-Dienstesymbol und wählen Sie dann Einstellungen aus, um das Dialogfeld "iFolder-Einstellungen" aufzurufen und die Registerkarte Allgemein zu öffnen. Wählen Sie iFolder starten, wenn Anmeldung am Desktop erfolgt aus und klicken Sie dann auf Übernehmen . Klicken Sie auf OK , um das Dialogfeld "iFolder-Einstellungen" zu schließen. So deaktivieren Sie den automatischen Start von iFolder beim Anmelden am Desktop: Klicken Sie mit der rechten Maustaste auf das iFolder-Dienstesymbol und wählen Sie dann Einstellungen aus, um das Dialogfeld "iFolder-Einstellungen" aufzurufen und die Registerkarte Allgemein zu öffnen. Deaktivieren Sie iFolder starten, wenn Anmeldung am Desktop erfolgt und klicken Sie dann auf Übernehmen . Klicken Sie auf OK , um das Dialogfeld "iFolder-Einstellungen" zu schließen. Manuelles Starten von iFolder Melden Sie sich mit der lokalen Windows-Benutzeridentität bei Ihrem Computer an, mit der Sie iFolder-Ordner erstellen möchten. Wenn iFolder nach der erfolgreichen Anmeldung nicht automatisch gestartet wird, wählen Sie die Optionsfolge Start Programme iFolder 3 und wählen Sie dann die Anwendung iFolder 3-Client aus. Macintosh Automatisches Starten von iFolder bei der Anmeldung Wenn iFolder automatisch gestartet werden soll, wenn Sie sich bei Ihrem Macintosh-Computer anmelden, fügen Sie iFolder den Startelementen hinzu. Starten Sie iFolder. Klicken Sie im Dock mit der rechten Maustaste auf das iFolder-Symbol und wählen Sie die Option Bei Anmeldung öffnen aus. oder Drücken Sie im Dock die Strg-Taste, klicken Sie auf das iFolder-Symbol und wählen Sie Bei Anmeldung öffnen aus. Um das automatische Starten von iFolder zu deaktivieren, entfernen Sie iFolder aus den Startelementen . Klicken Sie im Dock mit der rechten Maustaste auf das iFolder-Symbol und deaktivieren Sie die Option Bei Anmeldung öffnen . oder Klicken Sie im Dock mit der rechten Maustaste oder bei gedrückter Strg-Taste auf das iFolder-Symbol und deaktivieren Sie die Option Bei Anmeldung öffnen . Manuelles Starten von iFolder Melden Sie sich unter der lokalen Macintosh-Benutzeridentität, mit der Sie iFolder-Ordner erstellen möchten, bei Ihrem Computer an. Wählen Sie zum Starten von iFolder eine der folgenden Vorgehensweisen: Öffnen Sie das Verzeichnis Anwendungen auf der Macintosh-Festplatte und wählen Sie Anwendungen aus. Doppelklicken Sie anschließend auf iFolder 3 . Geben Sie iFolder im Spotlight ein (Apple-Taste + Leertaste oder klicken Sie oben rechts auf die Lupe), klicken Sie anschließend unter "Anwendungen" auf iFolder 3 . Öffnen Sie eine Terminal-Shell, melden Sie sich als Root-Benutzer an und geben Sie /Applications/iFolder 3.app/Contents/MacOS/iFolder 3 </content>
</topic>

<topic>
  <title>Konfigurieren von iFolder-Konten</title>
  <url>../accounts.html</url>