<?xml version="1.0" encoding="UTF-8" ?>
<!-- saved from url=(0014)about:internet -->

<!DOCTYPE site [
 <!ELEMENT site (topic+)>
  <!ELEMENT topic (title,url,content)>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT url (#PCDATA)>
   <!ELEMENT content (#PCDATA)>
]>

<site>
<topic>
  <title>OES 2 SP1: Novell iFolder 3.7クロスプラットフォームのヘルプ</title>
  <url>../bookinfo.html</url>
  <content>OES 2 SP1: Novell iFolder 3.7クロスプラットフォームのヘルプ 3.7 October 2008 iFolderヘルプ Novell® iFolder®は、Linux*、Windows*、Macintosh*クライアント用のファイル共有アプリケーションです。iFolderを使用すると、オンライン、オフライン問わず、常に複数のコンピュータ上で、自動的にファイルをローカルで使用することが可能です。 複数のiFolderのファイルを異なるユーザで共用することができます。 iFolderに参加できるユーザとiFolder内のファイルへのアクセス権は制御可能です。 また、他のユーザが共用しているiFolderに参加することもできます。ｘ このヘルプシステムでは、iFolderクライアントの使用方法と管理方法を説明します。 対象読者 本ガイドはiFolderクライアントのユーザを対象とします。 追加のマニュアル iFolder 3.7クライアントをNovell iFolder 3.7エンタープライズサーバまたはWebアクセスサーバで使用している場合、 Novell iFolderマニュアルのWebサイト で『 iFolder 3.7 User Guide for Novell iFolder 3.7 』を参照してください。 マニュアルの表記規則 Novellのマニュアルでは、「より大きい」記号(&gt;)を使用して手順内の操作と相互参照パス内の項目の順序を示します｡ 商標記号(®、™など)は、Novellの商標を示します。 アスタリスク(*)は、サードパーティの商標を示します。 パス名の表記に円記号(\)を使用するプラットフォームとスラッシュ(/)を使用するプラットフォームがありますが、このマニュアルでは円記号を使用します。 Linux、UNIXなど、スラッシュを使う必要があるプラットフォームを使用しているユーザは、必要に応じてスラッシュを使用してください。 </content>
</topic>

<topic>
  <title>概要 - iFolder</title>
  <url>../overview.html</url>
  <content>概要 - iFolder Novell® iFolder®は、Linux、Windows、Macintoshクライアント用のファイル共有アプリケーションです。ファイルを複数のiFolderで、それぞれ異なるユーザまたはLDAPGroupと共有することができます。iFolderに参加できるメンバーと、各メンバーのアクセスレベルを制御します。 また、他のユーザが共用しているiFolderに参加することもできます。ｘ iFolder 3.7ではクライアント側のiFolder 2. x からiFolder 3.6以降への移行、およびクライアント側のiFolder 3. x からiFolder 3.6以降へのアップグレード用に、単純で使いやすいユーザインタフェースが用意されています。 このセクションではiFolderの多様な利点と機能を説明します。 </content>
</topic>

<topic>
  <title>iFolderのメリット</title>
  <url>../benefits.html</url>
  <content>iFolderのメリット iFolderには次のメリットがあります。 iFolderがネイティブデスクトップ環境に統合されるため、複数のiFolderの作成と管理が用意にできる。 拡張性と柔軟性が非常に高く、ユーザごとのiFolderの数やiFolderごとのメンバーの数に実際的な制限がない。 暗号化を有効にすることで、iFolderサーバへのデータの送信中、保存中にデータを保護する。 強化されたWebアクセスコンソールを使用すると、iFolderクライアントがなくても任意のワークステーションからiFolderサーバ上のファイルにアクセスし、Webブラウザを使用して、iFolderクライアントへのすべての操作を実行できる。 私的なファイルと業務上のファイルを選別して容易に共用できる。 iFolderではiFolderのデータを最新のバージョンに移行およびアップグレードできる。 iFolderではLDAPGroupがサポートされる。iFolderをLDAPGroupと共有できる。LDAPGroupのメンバーは、iFolderを作成および所有できるほか、他の個人ユーザまたはLDAPGroupとiFolderを共有できます。 自分が所有するiFolderの場合、そのiFolderのメンバーユーザのアクセスレベルを制御でき、iFolderメンバーのアクセス権を制御する権限を付与されている場合も同様に制御できる。 複数のワークステーション上にあるメンバーのiFolderへ、ファイルを透過的に更新できる。 iFolderの実行中は、オフラインで行った変更をトラッキングして記録し、ユーザがサーバに接続した際にそれらの変更を同期する. データを同期するためにiFolderにアクセスするメンバーに、安全な認証を実施する。 電子メールに代わるファイル交換方法を提供するため、電子メールの添付ファイルのサイズを考慮する必要がなくなり、電子メールの保管に必要な容量が削減される。 </content>
</topic>

<topic>
  <title>iFolderクライアント</title>
  <url>../bawqltp.html</url>
  <content>iFolderクライアント iFolderクライアントは、ネイティブなデスクトップ環境でiFolderサービスを提供するために、オペレーティングシステムを統合します。iFolderクライアントで、自分が所有するiFolderを管理したり、どの共有iFolderを各コンピュータ上にセットアップするかを選択できます。 iFolderは次のオペレーティングシステムをサポートしています。 SUSE® Linux Enterprise Desktop 10 SP1 Windows Vista SP1 Windows XP SP2 / Windows 2000 Professional SP4 openSUSE® 10.2以降 Apple Macintosh® 10.4以降 </content>
</topic>

<topic>
  <title>iFolderアカウント</title>
  <url>../bawqmpe.html</url>
  <content>iFolderアカウント iFolderアカウントは、iFolderサービスの管理者が1つのiFolderサーバに対し1つのiFolderユーザを設定した場合に作成されます。管理者はユーザにユーザ名とパスワードを付与します。企業の場合、こうした情報はユーザ名または電子メールアドレス、およびそれらに関連付けられたパスワードが使用される場合もあります。iFolderを作成するには、先にiFolderアカウントを少なくとも1つ設定する必要があります。詳細については、 を参照してください。 iFolderセッションは、iFolderサービスのアカウントにログインした時点で開始し、ログアウトするか、またはiFolderクライアントを閉じると終了します。 自分のiFolderが他のアクティブなiFolderとファイルを同期するのは、自分のiFolderセッションがアクティブで、オンラインで作業しているときだけです。 自分のローカルiFolderへは、アカウントにログインしているかどうかに関係なく、いつでもアクセスできます。 詳細については、 を参照してください。 </content>
</topic>

<topic>
  <title>クロスプラットフォームの注意事項</title>
  <url>../ovwxplat.html</url>
  <content>クロスプラットフォームの注意事項 iFolderクライアントのLinux、Windows、およびMacintoshバージョンは、プラットフォーム固有のインタフェース協定に準拠しています。一般的なタスクを実行する方法は各プラットフォームで共通ですが、ボタン、表示領域、機能ラベル、デスクトップ通知スペースの場所、iFolder起動の初期設定など、実行するタスクによって多少異なります。 手順が明らかに異なる場合を除いて、このガイドでは3つのプラットフォームに対して1つの方法で説明します。 次の表はクライアントインタフェースで特に異なる点と似ている点を一覧にしています。 タスク Linux Windows Macintosh iFolderメニュー/システムトレイアイコンの右クリックオプション ［Quit］ 終了 ［Quit］ ［iFolderの初期設定］ &gt; ［アカウント］ダイアログ ［追加］ボタン ［追加］ボタン ［+］ ボタン ［iFolderの初期設定］ &gt; ［アカウント］ダイアログ ［削除］ボタン ［削除］ボタン ［-］ ボタン 複数の場所 ［閉じる］ボタン 操作は実行時に確定されます。 ［OK］、［キャンセル］、および［適用］ボタン 操作は、［ 適用 ］または［ OK ］をクリックした場合のみ確定されます。 ［ OK ］および［ キャンセル ］ボタン 操作は実行時に確定されます。 ［iFolderの初期設定］ダイアログ デスクトップの スタートアッププログラムにiFolderを追加 ［デスクトップにログインしたときにiFolderを起動する ］を選択(有効にする) この機能は使用できません。 iFolderアカウントの設定 パスワードを保存 このコンピュータにパスワードを保存 パスワードを保存する 通知スペース 通知スペース ステータスおよび通知スペース 通知スペース ［通知］スペースで ［ アカウントの設定 ］を右クリック アカウント この機能は使用できません。 ［iFolder］ &gt; ［iFolder］メニュー プロパティ プロパティ Get Info (情報を取得) iFolderウィザード ［転送］ボタンと［戻る］ボタン ［ 次へ ］ボタンと［ 戻る ］ボタン 前後に移動するボタンはありません。ユーザ名、パスワード、およびサーバを1つのウィンドウで設定できます。 iFolderアカウントの設定 iFolderアカウントアシスタント iFolderアカウント作成ウィザード ［ 初期設定 ］&gt;［ アカウント ］ iFolderサーバ設定ウィザード iFolder Server(iFolderサーバ) iFolderサーバの選択 使用不可 iFolder識別設定ウィザード ID iFolderアカウント情報 使用不可 </content>
</topic>

<topic>
  <title>iFolderの主要機能</title>
  <url>../keyfeatures.html</url>
  <content>iFolderの主要機能 iFolderを使用する前に、次の主要機能について理解することが重要です。 iFolderの共有 一般に、複数の場所で作業したり、他人と共同で作業したりする場合は、ファイルのバージョンを綿密に管理する必要があります。 iFolderを使用すると、iFolderクライアントがインストールされ、特定ファイル用にiFolderが作成されたコンピュータであればどこからでも、そのファイルの最新バージョンにアクセスできます。また、iFolderでは複数のiFolderとそのコンテンツを他の許可されたユーザまたはLDAPGroupと共有することもできます。共有iFolderの詳細については、「 」を参照してください。 iFolderクライアントは、中央のサーバを介して複数のコンピュータ間のファイルを同期することによって、共有をサポートしています。 これにより、次のことが可能になります。 コンピュータ間でのファイルの共用 他のユーザとのファイルの共用 複数のiFolderの所有 他のユーザと共用する複数のiFolderへの参加 複数のアカウントへの所有者またはメンバーとしての参加 iFolderでの作業は、ファイルマネージャや、iFolderクライアントの一部であるiFolderブラウザで直接行います。iFolder内では、ユーザの好みや職場の慣行に合わせて、任意のサブディレクトリ構造を設定できます。 このサブディレクトリ構造は、iFolderのメンバー全員に同じものが提供されます。 共有iFolder iFolderは、中央のサーバを介して、ユーザが指定したユーザグループと、ファイルを選択して共有および同期するローカルディレクトリです。 iFolderファイルへはすべてのiFolderメンバーがアクセスでき、権利を付与されたメンバーはファイルの内容を変更できます。 複数のワークステーションを介してiFolderにアクセスしたり、他のユーザおよびLDAPGroupのどちらともそれを共有できます。 各iFolderに参加できるメンバーと、各メンバーのアクセスレベルを指定します。 同様に、コラボレーション環境内で他のユーザが所有している共有iFolderに参加することができます。 iFolderを共用しているときに、書き込み権を付与されたメンバーユーザがこのディレクトリを変更した場合、変更内容はiFolderのすべてのコピーに適用されます。 の要件を満たしている場合は、共有iFolderがコンピュータ上のどこにあっても、ユーザはこれを見つけることができます。 iFolderのアクセス権 iFolderクライアントでは、iFolderメンバーに対して所有者および3つのレベルのアクセス権をサポートしています。 LDAPGroupのメンバーはグループのアクセス権セットを継承します。 所有者: iFolderの所有者としての役割を果たす唯一のユーザです。通常はそのiFolderを作成したユーザになります。所有者ユーザは、iFolderクライアントを使用して、所有権をiFolderの他のメンバーに譲渡することができます。 iFolderの所有者にはフル制御のアクセス権があります。 このユーザはiFolderに対する読み書き可能アクセス権をもち、メンバーユーザのメンバーシップとアクセス権を管理したり、メンバーのフル制御アクセス権を削除したりできます。 iFolderの所有者がLDAPGroupの場合、グループに属すすべてのメンバーユーザにフル制御権が与えられます。 フル制御: フル制御のアクセス権を持つ共有iFolderのメンバーです。このメンバーはiFolderへの読み書き可能アクセス権をもち、所有者を除くすべてのユーザに対するメンバーシップとアクセス権を管理できます。 読み書き: 共有iFolderのメンバーで、iFolder内のディレクトリとファイルに対する読み書き可能アクセス権を持ちます。このメンバーはローカルでファイルを変更することが可能で、変更した内容はiFolderメンバーのコピーに同期されます。 読み込み専用: 共有iFolderのメンバーで、iFolder内のディレクトリとファイルに対する読み込み専用アクセス権を持ちます。このメンバーはファイルの変更はローカルでできますが、変更した内容はiFolderメンバーのコピーへは同期されません。 iFolderユーザまたはLDAPGroupはiFolderを所有したり、他のiFolderのメンバーになったりすることができます。 所有者ユーザの場合、常にフル制御のアクセス権を持ちます。 メンバーユーザの場合、各共有iFolderでのアクセスレベルはさまざまで、フル制御のアクセス権を持つメンバーによってアクセス権が付与されます。 ファイルの同期 サーバに接続されているときに作業を行うと、iFolderはiFolderのメンバーシップとファイルをバックグラウンドで同期します。iFolderアカウントを設定したときに、［ パスワードを保存 ］を有効にすると、そのコンピュータでのパスワードをiFolderに記憶させることができます。次回にiFolderを起動すると、サーバに自動的に接続され、データが同期されます。その際、パスワードの入力は求められません。 iFolderクライアントは、各自のコンピュータのデスクトップ環境へログインするたびにiFolderを自動的に実行するように設定できます。 セッションは、ユーザがローカルiFolder内のファイルで作業しているときはバックグラウンドで動作し、変更を追跡および記録します。 ファイルは手動で同期させたり、同期の間隔を指定したりできます。 iFolder には、デルタ同期機能もあります。iFolderファイルに変更を加えると、デルタ分、すなわち変更内容のみがサーバに同期されます。つまり、デルタ同期は、iFolderクライアントとサーバとの間で最後に同期してからの更新分のみを取得するということです。これにより、同期時間が短縮されるため、同期の効率が向上します。 マイグレーション Novell iFolderにはiFolder 2. x からNovell iFolder 3.7用iFolderクライアントへの容易でわかりやすい移行機能が備わっています。iFolderクライアントの移行ウィザードは既存のiFolder 2. x のデータをiFolder3.6およびそれ以降に、迅速かつ容易に移行するのに役立ちます。詳細については、 を参照してください。 暗号化 iFolder は、機密性の高いiFolderファイルに対する強力なセキュリティ提供します。意図されているかどうかに関係なく、許可されていないユーザによるアクセスから守ります。かつて、サーバ側のデータセキュリティは安全ではなく、管理者による、またはサーバへの不正なアクセス権を取得したユーザによるデータへのアクセスが可能でした。また、ISPプロバイダを介してiFolderにアクセスする際に、許可されていない人が不注意に機密ファイルを見てしまう可能性もあります。これを避けるため、ファイルは暗号化してサーバ上に保存し、自分だけが知っているパスフレーズを使用して取り出せるようになりました。パスフレーズを忘れた場合は、暗号化されたiFolderの作成時に選択した回復エージェントによって、データの回復が支援されます。次に示す図は、iFolderがどのように損失したデータを回復するかの概念を示します。 暗号化されたiFolderは共有できません。 暗号化の詳細については、「 」を参照してください。 アップグレード Novell iFolder 3.7には、iFolder 3. x からNovell iFolder 3.6およびそれ以上のバージョンのiFolderクライアントへ容易にアップグレードする機能が備わっています。詳細については、 を参照してください。 マージ マージを使用すると、iFolderのデータを統合し、iFolderサーバとクライアント間のデータ転送を最小化することができます。また、マージでは既存のフォルダをクライアントマシンの別の場所に移動することもできます。詳細については、 を参照してください。 デフォルトiFolder iFolder では、新しいアカウントを設定するときにデフォルトiFolderをセットアップできます。新しいiFolderアカウントを設定するといつでも、iFolderは自動的にデフォルトiFolderがあるかどうかを確認します。デフォルトiFolderが作成されていない場合、これを作成するためのプロンプトが表示されます。デフォルトiFolderがすでに存在する場合は、ダウンロードを求めるプロンプトが表示されます。これらのオプションは無視することもできます。詳細については、「 」の「 」を参照してください。 拡張されたWeb Access iFolder では、拡張されたWebインタフェースにより、リモートサーバ上のiFolderファイルにアクセスできます。Web Accessコンソールにより、iFolderクライアントのないワークステーションから、Webブラウザを使用してiFolderサーバ上のファイルにアクセスできます。Web Accessクライアントインタフェースでは、iFolderクライアントのすべての操作を実行できます。 以前のiFolderバージョンとiFolder 3.6以降の違いは、拡張されたWebアクセスコンソールからiFolderを作成、参照、共有、アップロードおよび削除できる点です。モバイルユーザも、この機能をWebから利用することができます。 同期ログ 同期ログには、除外されたファイルや未同期ファイルを除く、他のiFolderに対するファイルのアップロードやダウンロード、ポリシー違反などの、iFolderのバックグラウンド動作状況のログが表示されます。 </content>
</topic>

<topic>
  <title>次に行う作業</title>
  <url>../ovwnext.html</url>
  <content>次に行う作業 iFolderクライアントによる設定方法については、次を参照してください。 </content>
</topic>

<topic>
  <title>iFolderアカウントと初期設定の管理</title>
  <url>../accountsprefs.html</url>
  <content>iFolderアカウントと初期設定の管理 このセクションでは、iFolder クライアントのiFolder™アカウントを設定し、初期設定を管理する方法について説明します。 </content>
</topic>

<topic>
  <title>iFolderクライアントの起動</title>
  <url>../startclient.html</url>
  <content>iFolderクライアントの起動 iFolderが起動している場合、 iFolderサービスアイコン iFolderは、デスクトップ環境に統合されます。iFolderがファイルマネージャ、デスクトップまたはiFolderブラウザに表示されているときは、iFolderエンブレム(緑色の「i」) がiFolder上に表示されます。暗号化されたiFolderは、 エンブレム(ロックされたフォルダ)で表示されます。 タスクバーの［通知］スペースは、iFolderの実行中に iFolderサービス アイコンが表示されるようにするため、有効にしておく必要があります。 ローカルiFolder内のファイルに対しては、いつでもローカルで作業できます。 iFolderクライアントの実行中は、ローカルiFolderデータに変更を加えると、その内容が常に記録されます。iFolderが実行中でないときにローカルiFolderデータに変更を加えると、次回にiFolderを起動したときに、内容の相違点が認識され、記録されます。 iFolderが実行していない場合、iFolderはファイルマネージャまたはデスクトップ上に表示されます。iFolderのローカルコピー内のファイルにはアクセスできますが、iFolderを管理することはできません。また、iFolderを作成したり、ファイルを同期するには、アカウントにログインする必要があります。 アカウントを作成する場合は、SSLを介したユーザログインを行う必要があります。サーバ証明書を受け入れるためのプロンプトが表示されたら、正常な接続を確立するために証明書を検証して受け入れる必要があります。 iFolderクライアントの停止についての詳細は、「 」を参照してください。 Linux ログイン時にiFolderを自動的に起動する デスクトップにログインしたときにiFolderを自動的に起動するには、次のいずれかを実行します。 アプリケーションメニューを開き、［ More Applications (その他のアプリケーション)］をクリックして、［iFolder 3 ］を右クリックしてから、メニューから［Add to Startup Programs(スタートアッププログラムに追加する) ］を選択します。 ログアウトするときにiFolderが実行中であることを確認し、その後でセッションの設定を保存します。 デスクトップにログインするときに、このセッションのオプションを選択します。 ターミナルウィンドウを開き、 root ユーザとしてログイン後、 /opt/gnome/bin/gnome セッションプロパティを実行して、コンピュータにログインしたときのスタートアッププログラムにiFolderを追加します。 iFolderをログイン時に自動的に起動しないようにするには、次のいずれかを実行します。 アプリケーションメニューを開き、［iFolder 3 ］を右クリックしてから、［Remove from Startup Programs (スタートアッププログラムから削除する) ］を選択します。. ログアウトするときにiFolderが実行中でないことを確認し、その後でセッションの設定を保存します。デスクトップにログインするときに、このセッションのオプションを選択します。 iFolderを手動で起動する iFolderを作成するときに使用する、ローカルのLinuxユーザIDでコンピュータにログインします。 次のいずれかの方法でiFolderを起動します。 タスクバーで、アプリケーションメニューを開き、［More Applications (その他のアプリケーション) ］をクリックし、使用可能なオプションをスクロールして［iFolder 3 ］を見つけます。［iFolder 3］を右クリックしてから、［Start iFolder 3 (iFolder 3の起動) ］を選択します。 ターミナルシェルを開いて、次のように入力します。 /opt/novell/ifolder3/bin/ifolder Windows ログイン時にiFolderを自動的に起動する デスクトップへのログイン時にiFolderが自動的に開始されるようにするには、次の手順に従います。 Right-click the iFolder Services icon, then select Preferences to open the iFolder Preferences dialog box to the General tab. ［デスクトップにログインしたときにiFolderを起動する ］を選択し、［適用 ］をクリックします。. ［OK ］をクリックして［iFolderの初期設定］ダイアログボックスを閉じます。 デスクトップにログオンしたときに、iFolderを自動的に起動しないようにするには、次の手順に従います。 iFolderサービス アイコンを右クリックして［ 初期設定 ］を選択し、［iFolderの初期設定］ダイアログボックスの［ 一般 ］タブを開きます。 ［デスクトップにログインしたときにiFolderを起動する ］を選択解除し、［適用 ］をクリックします。. ［OK ］をクリックして［iFolderの初期設定］ダイアログボックスを閉じます。 iFolderを手動で起動する iFolderを作成するときに使用するユーザIDでコンピュータにログオンします。 If iFolder does not start automatically on successful logon, start iFolder by clicking Start Programs iFolder 3 , then select the iFolder 3 Client application. Macintosh ログイン時にiFolderを自動的に起動する Macintoshコンピュータにログインしたときに自動的にiFolderを起動する場合は、iFolderを［ スタートアップアイテム ］に追加します。 iFolderを起動します。 ドックでiFolderアイコンを右クリックし、［ Open at Login (ログイン時に開く) ］をクリックします。 または ドックでCtrlキーを押し、iFolderアイコンをクリックして、［ Open at Login (ログイン時に開く) ］をクリックします。 iFolderが自動的に開始しないようにするには、［ スタートアップアイテム ］からiFolderを削除します。 ドックでiFolderアイコンを右クリックし、［ Open at Login (ログイン時に開く) ］を選択解除します。 または ドックでCtrlを右クリックするか、iFolderアイコンをクリックして、［ Open at Login (ログイン時に開く) ］を選択解除します。 iFolderを手動で起動する iFolderを作成するときに使用する、ローカルのMacintoshユーザIDでコンピュータにログインします。 次のいずれかの方法でiFolderを起動します。 Macintosh HDで、［ アプリケーション］ディレクトリを開き、［アプリケーション ］を選択して、［iFolder 3 ］をダブルクリックします。 スポットライトで(Appleボタン + スペースバーまたは右上部にある虫メガネ型のアイコンをクリック) 「iFolder」と入力し、続いてアプリケーションの下で［ iFolder 3］をクリックします。 端末シェルを開いてルートユーザとしてログインし、次のように入力します。 /Applications/iFolder 3.app/Contents/MacOS/iFolder 3 </content>
</topic>

<topic>
  <title>iFolderアカウントの設定</title>
  <url>../accounts.html</url>
  <content>iFolderアカウントの設定 新しいアカウントを追加して設定するには、iFolderアカウントアシスタントを使用します。システム上でiFolderの作成またはiFolderの共用を行う前に、少なくとも1つのiFolderアカウントを設定する必要があります。 iFolderホストサービスごとに作成できるアカウントは1つだけですが、アカウントは複数持つことができます。 各アカウントには個別にログインできるため、複数のアカウントに同時にログインすることができます。 複数のユーザは異なるローカルログインIDを使用することで、同じコンピュータ上でiFolderを所有できます。ローカルユーザIDでiFolderクライアントをはじめて起動すると、そのユーザのアカウントをセットアップするためのプロンプトが表示されます。 iFolder 3.7ではiFolder管理者がアカウントを作成および設定する際に役立つ、自動アカウント作成機能が新しく導入されました。iFolder管理者が自動アカウント作成機能を有効にしている場合、ユーザがアカウントを設定する必要はありません。iFolderの初回起動時、パスワードの入力が求められます。パスワードを入力して、アカウントの設定を完了します。 新しいアカウントを設定するには、次の手順に従います。 次のいずれかの方法で、 iFolderアカウントアシスタント にアクセスします。 現在のローカルログインIDでiFolderをはじめて起動すると、iFolderアカウントをセットアップするためのプロンプトが表示されます。［ 転送］をクリックして、 iFolderアカウントアシスタントを直接開きます。 ［通知］スペースでiFolderサービス icon in the notification area, select Accounts to open the iFolder Preferences dialog box to the Accounts tab, then click Add to open the iFolder Account Assistant . 画面の指示に従って次の値を指定します。 パラメータ 説明 Server Address (サーバアドレス) アカウントを作成するiFolderエンタープライズサーバのDNS名またはIPアドレスです。 この情報は、iFolder管理者から入手してください。 例を次に示します。 svr21.example.com または 192.168.1.1 サーバ名はIPアドレスとともに、iFolderのユーザインタフェースに常に表示されます。例: iFolder - 192.162.1.1 iFolder 3.7クライアントを使用してiFolder 3.2サーバに接続することはできません。 Make this my default server (このサーバをデフォルトにする) 複数のサーバがある場合は、［ Make this my default server (このサーバをデフォルトにする)］を選択すると、iFolderを作成したりiFolderにアップロードしたりするときに、このサーバがドロップダウンリストでデフォルトとして選択されます。 ［ユーザ名］ このアカウントのユーザIDを入力します。 使用するユーザIDの形式は、iFolder管理者によって、ネットワークユーザID (LDAPの一般名)、または電子メールアドレスのいずれかに決定されます。 たとえば、John Smithという人のユーザIDが「jsmith」、電子メールアドレスが「john.smith@example.com」である場合、管理者はサーバを設定するときに、認証を行うための［ ユーザ名 ］フィールドでどちらの形式を受け入れるかを決定します。 ［パスワード］ ユーザ名に対するパスワードを指定します。 認証は、保護されたチャネル(SSL)を介して実行されます。サーバ証明書を検証して受け入れるためのプロンプトが表示されます。 パスワードを保存 コンピュータにログインしたときに、このiFolderアカウントに自動的にログインするには［ Remember My Password (パスワードを保存)］を選択します。 ネットワークパスワードを変更すると、次にiFolderアカウントへのログインを試みたときの自動認証は失敗します。新しいパスワードでログインするためのメッセージが表示され、新しいパスワードの指定と保存ができます。 ［ パスフレーズ ］フィールドに秘密のパスフレーズを入力し、確認のために同じパスフレーズを再び入力します。 管理者が暗号化ポリシーを オン に設定済みである場合、パスフレーズの入力とパスフレーズ回復エージェントの選択を促すプロンプトが表示されます。パスフレーズ管理の詳細については、「 」を参照してください。 ［ パスフレーズを保存する ］を選択して、現在のセッション中、暗号化されたiFolderデータに自動的にアクセスできるようにします。このオプションを選択すると、パスフレーズをiFolderに記憶させておくことができます。 次回、ログインプロセスの開始時に、このパスフレーズが自動的に処理され、ダイアログボックスは表示されません。 リストから目的の回復エージェントを選択し、［ OK］をクリックします。 入力した情報が正しいことを確認し、必要に応じて前のページに戻って訂正します。その後で［ 接続］をクリックすると、iFolderサーバへのログイン情報が検証されます。 ［ このサーバの証明書を受け入れますか?］というプロンプトが表示されたら、［ 詳細］をクリックして証明書情報を確認し、［ OK］をクリックして証明書を受け入れます。 証明書を受け入れないと、パスフレーズを設定できません。 接続に成功すると、その時点でiFolderが存在しないと、デフォルトのiFolderの作成を確認するメッセージが表示されます。 デフォルトのiFolderを作成する場所を指定します。 デフォルトのiFolder名は、 Default_username で、 username は、このアカウントのユーザIDを指します。たとえば、現在のアカウントのユーザ名が test1 で、デフォルトのiFolder名が Default_test1 であるとします。 デフォルトでは、デフォルトのiFolderは &lt;ユーザホームディレクトリ&gt;/ifolder/server_name/user_name に格納されます。この場所は変更できます。 作成するデフォルトiFolderのタイプを選択します。［ 暗号化 ］を選択すると、パスフレーズの入力を求めるプロンプトが表示されます。詳細については、 を参照してください。 共有できるのは通常のiFolderだけです。暗号化されたiFolderは共有できません。 iFolder管理者が現在のアカウントでの暗号化を有効にしていない場合は、通常のiFolderだけを作成できます。［ 通常］オプションはデフォルトで選択されています。このような場合、いずれの［ セキュリティ ］オプションも無効になっています。 作成しているiFolder内のファイルを安全に同期する場合は、［ SecureSync］を選択します。 保護されたチャネルは、通常のiFolderと暗号化されたiFolderの両方で有効にできます。このオプションを選択すると、サーバ上のiFolderとローカルマシン上のiFolderを同期する際に、保護されたチャネルが使用されます。 あるフォルダをデフォルトのiFolderに指定した後は、サーバからそのフォルダを削除しない限り、タイプを変更することはできません。サーバ上のデフォルトiFolderを削除すると、次回にシッククライアントからアカウントを設定するときに、デフォルトiFolderを作成するためのプロンプトが再度表示されます。 デフォルトiFolderをセットアップ済みの場合は、ローカルコンピュータ上にダウンロードするように求められます。 デフォルトiFolderをダウンロードしたら、［ 次へ ］をクリックしてアカウントの設定を終了します。 接続が成功したら、［ 完了］をクリックしてiFolderアカウントアシスタントを閉じます。 指定されたアカウントのユーザリストが同期され、ダウンロード可能なiFolderが認識されます。このような初期のダウンロードは、アカウントのユーザリストのサイズによっては、数秒から数分かかる場合があります。 セットアップしたアカウントがアカウントのリストに表示されていることを確認します。 Right-click the iFolder Services icon in the notification area, then select Preferences from the menu to open the iFolder Preferences dialog box to the Accounts tab. iFolderに接続されている場合は、［ オンライン］チェックボックスがオンになっています。 ［iFolderの初期設定］ダイアログボックスを閉じます。 次の方法のいずれかを使用して、このアカウントのiFolderをセットアップします。 ［通知］スペースで［ iFolderサービス ］アイコンを右クリックし、［ iFolder ］を選択してiFolderブラウザを開きます。 に進みます。 このアカウントのiFolderがサーバからダウンロードできる場合、［iFolder］ウィンドウの「&lt; iFolder_server_name &gt;」のiFolderの下に表示されます。ダウンロードアイコン で、iFolderがダウンロードできることが示されます。 に進みます。 </content>
</topic>

<topic>
  <title>iFolderアカウントへのログイン</title>
  <url>../login.html</url>
  <content>iFolderアカウントへのログイン iFolderディレクトリ内のファイルに対しては、いつでもローカルで作業できます。ユーザリストの同期、iFolderデータの同期、新しいiFolderのアップロード、共有iFolderのダウンロード、iFolderの共有およびiFolderの管理を実施するには、iFolderアカウントにログインする必要があります。各アカウントには個別にログインできるため、複数のアカウントに同時にログインすることができます。 各アカウントで、次のログイン方法のいずれかを使用します。 Log In Automatically: 自動的なログイン: iFolderクライアントの起動時に自動的にログインする場合は、そのiFolderアカウントの［ パスワードを保存］を有効にします。［ パスワードを保存］は、アカウントを設定するとき、または後でアカウント設定を変更するときに有効にできます。 パスワードを変更した場合は常に、次回にそのiFolderアカウントにログインしようとすると自動認証は失敗します。ログインを求めるプロンプトが表示されたら、新しいパスワードを入力します。必要に応じて、［ パスワードを保存］を再び有効にします。 Log In As Needed: 必要に応じてログイン: 必要なときにのみiFolderアカウントにログインする場合は、［ パスワードを保存］を無効にします。 既存のiFolderアカウントの［ パスワードの保存］を有効、または無効にするには、次の手順に従います。 Right-click the iFolder Services icon in the notification area, then select Accounts to open the iFolder Preferences dialog box to the Accounts tab. iFolderアカウントを選択し、［ プロパティ］をクリックして、［プロパティ ］ダイアログボックスの設定を表示します。 ［識別子 ］タブをクリックします。 ［ パスワードを保存］を選択(有効)、または選択解除(無効)します。 ［OK ］をクリックして設定を変更します。. 変更を保存してサーバにログインするには、［iFolderプロパティ ］ダイアログボックスで［OK ］をクリックします。 iFolderアカウントにログインするには、次の手順に従います。 Right-click the iFolder Services icon in the notification area, then select Accounts . iFolderアカウントを選択し、そのアカウントの横にある［オンライン ］チェックボックスをオンにします。 パスワードの入力を求められたら、パスワードを指定し、［接続 ］をクリックします。. アカウントの［パスワードを保存 ］が有効になっている場合は、そのパスワードの有効期限が切れていない限り、パスワードの入力用プロンプトは表示されません。 ログインに失敗すると、パスワードの失敗など、失敗の原因になったエラーメッセージが表示されます。 接続が成功したら、［iFolderの初期設定 ］ダイアログボックスを閉じます。 </content>
</topic>

<topic>
  <title>iFolderアカウント設定の表示と変更</title>
  <url>../accountdetails.html</url>
  <content>iFolderアカウント設定の表示と変更 ［アカウントの設定］ダイアログボックスと［アカウントプロパティ］ダイアログボックスに、次のパラメータが表示されます。 パラメータ 説明 ディレクトリ ユーザによる変更の可否(はい/いいえ) ［オンライン］ 現在、アカウントがiFolderサーバに接続されているかどうかを示します。 このアカウントでiFolderサーバに接続するには、アカウントの横にある［オンライン ］チェックボックスをオンにします。 iFolderサーバから接続を切断するには、アカウントの横にある［オンライン ］チェックボックスをオフにします。 ［iFolderの初期設定］ &gt; ［アカウント］タブ はい 名前 そのアカウントのiFolderが格納されているiFolderサーバの識別名を表示します。この名前はサーバによって指定され、iFolder管理者によって制御されます。 ユーザはこの設定を変更できません。 ［iFolderの初期設定］ &gt; ［アカウント］タブ ［アカウントプロパティ］ &gt; ［サーバ］タブ いいえ ［ユーザ名］ ネットワークユーザID (LDAPの共通名)または電子メールアドレスなど、このアカウントのユーザIDが表示されます。この設定は変更できません。 iFolderアカウントアシスタントでアカウントをセットアップするときは、ユーザ名が指定されます。既存のアカウントのユーザ名は変更できません。 同じサーバ上で別のユーザ名を使用するには、そのアカウントを削除してから、別のアカウントを作成してください。 ［iFolderの初期設定］ &gt; ［アカウント］タブ ［アカウントプロパティ］ &gt; ［識別情報］タブ いいえ Server Address (サーバアドレス) アカウントを作成するiFolderエンタープライズサーバのDNS名またはIPアドレスが表示されます。 この情報は、iFolder管理者から入手してください。 例を次に示します。 svr21.example.com または 192.168.1.1 アドレスは変更できますが、変更するときはiFolderサーバへの接続を切断する必要があります。 ［アカウントプロパティ］ &gt; ［サーバ］タブ はい ［パスワード］ ユーザ名にパスワードを指定することができます。 ［アカウントプロパティ］ &gt; ［識別情報］タブ はい パスワードを保存する iFolderの起動時に、iFolderがユーザに代わって自動的にログインするかどうかを示します。アカウントの［ 自動的に接続する］パラメータが有効(デフォルト)になっている場合は、iFolderは保存されたパスワードを使用して接続を試みます。 コンピュータにログインしたときに、このiFolderアカウントに自動的にログインするには［ このコンピュータにパスワードを保存する］を選択します。 ネットワークパスワードを変更すると、次にiFolderアカウントへのログインを試みたときの自動認証は失敗します。新しいパスワードでログインするためのメッセージが表示され、新しいパスワードの指定と保存ができます。 ［アカウントプロパティ］ &gt; ［識別情報］タブ はい 割り当て量 エンタープライズサーバ上のiFolderアカウントに割り当てられた総容量を示します。 この値は、すべてのユーザに設定されたデフォルトの割り当て量、またはユーザごとの割り当て量になります。 割り当て量が設定されていない場合、この値は空であるか、または「 N/A 」(使用不可)になります。 ［アカウントプロパティ］ &gt; ［ディスク容量］タブ いいえ 使用済み このアカウントに属す、すべてのiFolderで現在使用している総容量を示します。 この値には、他のユーザが所有している共有のiFolderで占有する容量は含まれません。接続先のサーバごとに、使用されている容量をiFolderメインウィンドウに表示することもできます。 ［アカウントプロパティ］ &gt; ［ディスク容量］タブ いいえ 使用可能 このiFolderアカウントで現在使用できるiFolderの総容量を示します。 この値は、使用済み容量を差し引いた値になります。接続先のサーバごとに、使用可能な容量をiFolderメインウィンドウに表示することもできます。 ［アカウントプロパティ］ &gt; ［ディスク容量］タブ いいえ 自動的に接続する この値が選択されている(有効な)場合、iFolderは起動時に、このアカウントに自動的に接続します。アカウントに接続しないようにするには、この設定を選択解除します。 この設定は、クライアント側からのみアカウントを有効または無効にする機能です。 Novell® iFolder® 3.7サーバでiFolderを使用する場合、iFolderシステム管理者がiFolderアカウントをサーバ側で無効にすることができます(通常は一時的な措置)。この操作を実行すると、次のような動作になります。 ユーザがログインしているときにサーバ側でそのユーザのアカウントが無効にされると、ユーザがログアウトするか同期を無効にしてセッションを終了する、またはサーバによりセッションが切断される場合のいずれかが起こるまで、iFolderとiFolderデータを管理および同期し続けることができます。 アカウントがサーバ側で無効にされた場合にログインを試みると、ポップアップメッセージが表示され、アカウントが無効になったことが知らされます。その場合は、iFolderシステム管理者に問い合わせてください。 ［アカウントのプロパティ］ のすべてのタブ上 はい アカウントをデフォルトにする 複数のアカウントがある場合は、このアカウントの ［アカウントをデフォルトにする］チェックボックスをオンにすると、iFolderを作成したりiFolderにアップロードしたりするときに、このアカウントがアカウントのドロップダウンリスト内でデフォルトとして選択されます。 この値は、アカウントが1つしかない場合には変更できません。 ［アカウントプロパティ］ のすべてのタブ上 はい(複数のアカウントがある場合) ［暗号化］設定 暗号化設定は［ セキュリティ ］メニューで、設定とリセットができます。暗号化設定の詳細については、「 」を参照してください。 ［セキュリテイ］メニュー ユーザはパスフレーズをリセットできる Right-click the iFolder Services icon in the notification area, then select Account Settings to open iFolder Preferences to the Accounts tab. ［アカウント］タブでは、アカウントごとに次のパラメータを管理できます。 オンライン(選択すると接続され、選択解除すると接続が切断される) 名前(表示のみ) ユーザ名(表示のみ) 管理するiFolderアカウントを選択し、［ プロパティ］をクリックして［ アカウントプロパティ］ダイアログボックスの［サーバ ］タブを開きます。 ［サーバ］タブでは、選択したアカウントに対し、次のパラメータを管理できます。 名前(表示のみ) アドレス(接続時は表示のみ、切断時は変更可能) サーバの説明(表示のみ。すべての情報を表示する場合はスクロールする) 自動的に接続する(選択すると有効、選択解除すると無効) アカウントをデフォルトにする(選択すると有効。複数のアカウントが存在する場合にのみ使用可能) ［ 識別情報］タブを選択すると、選択されたアカウントに対し、次のパラメータを管理できます。 ユーザ名(表示のみ) パスワード(パスワードを指定) このコンピュータにパスワードを保存する(選択すると有効、選択解除すると無効) 自動的に接続する(選択すると有効、選択解除すると無効) アカウントをデフォルトにする(選択すると有効。複数のアカウントが存在する場合にのみ使用可能) ［ ディスク容量］タブを選択すると、選択されたアカウントに関する次のパラメータが表示されます。 割り当て量(表示のみ) 使用量(表示のみ) 使用可能(表示のみ) 自動的に接続する(選択すると有効、選択解除すると無効) アカウントをデフォルトにする(選択すると有効。複数のアカウントが存在する場合にのみ使用可能) 設定が終了したら、［ アカウントプロパティ］ダイアログボックスを閉じてから、［ iFolderの初期設定］ダイアログボックスを閉じます。 </content>
</topic>

<topic>
  <title>クライアントのiFolder初期設定を行う</title>
  <url>../preferences.html</url>
  <content>クライアントのiFolder初期設定を行う Right-click the iFolder Services icon in the notification area, then select Preferences to open the iFolder Preferences dialog box to the General tab. 次の初期設定を指定します。 パラメータ 説明 デスクトップにログインしたときにiFolderを起動する (Windowsクライアントでのみ使用可) このオプション選択すると、iFolderアカウントをセットアップしたローカルのユーザ名でログインするときは、常にiFolderが起動します。 ［ パスワードを保存 ］を有効にしたアカウントでは、バックグラウンドで、指定した同期間隔で同期を行います。 iFolderを手動で開始するには、このオプションを選択解除します。 iFolderの作成時に確認ダイアログを表示 このオプションを選択すると、iFolderが表示されるiFolderのリストに加え、iFolderを作成するたびに確認メッセージが表示されます。 確認メッセージの表示を停止するには、このオプションを選択解除します。 共有iFolderの通知 このオプションを選択すると、iFolderを共用する新規の招待を受け取るたびに、［通知］スペースでポップアップメッセージが表示されます。 現在のコンピュータでダウンロードできるiFolderのリストを表示するには、iFolderの実行中にiFolderブラウザで［ Show Available iFolders (使用可能なiFolderを表示) ］を選択します。 Hide iFolder Tray Icon (iFolderトレイアイコンを隠す) このオプションは［通知］スペースでiFolderトレイアイコンを隠すために選択します。 ［通知］スペースの右クリックオプションを使用して、iFolderトレイアイコンを隠すこともできます。［通知］スペースで iFolderサービス アイコンを右クリックし、［隠す ］をクリックします。 iFolderの実行中にこのオプションを選択解除し、iFolderトレイアイコンを表示します。 競合の通知 Select this option to enable a pop-up message in the notification area whenever a conflict occurs when synchronizing files. Deselect this option to disable the pop-up messages for synchronization conflicts. Whenever conflicts occur, the iFolder Error icon is displayed on the iFolder when iFolder is running. Notify When a User Joins Select this option to enable a pop-up message in the notification area whenever a user accepts an invitation to share an iFolder. Acceptance is keyed to when the user actually sets up the iFolder on his or her own computer. Deselect this option to disable the pop-up messages for user share confirmation. You can view a complete list of iFolder users whenever iFolder is running by selecting the iFolder, then clicking Share with to open the iFolder Properties dialog box to the Sharing tab. Synchronization Automatically Synchronize iFolders: Select this check box to enable synchronization for all iFolders on this computer under your current local login or logon identity. Deselect the check box to disable synchronization. Synchronize iFolders Every: Specify the minimum interval to use for synchronizing iFolders on this computer under your current local login or logon identity. Specify the value and units. The default is 5 minutes if this option is enabled. The minimum interval can be lowered to 5 seconds. If you use the iFolder client with Novell iFolder 3.7, the effective minimum synchronization interval is always the largest value of the following settings: The system policy default of zero ( 0 ), unless there is a user policy set. If a user policy is set, the user policy overrides the system policy, whether the user policy is larger or smaller in value. The local machine policy, or the setting on the client machine synchronizing with the server. The iFolder (collection) policy. When you are done, click Apply to apply your changes. Click OK to close the iFolder Preferences dialog box. </content>
</topic>

<topic>
  <title>iFolderトラフィックに対するローカルファイアウォールの設定</title>
  <url>../firewall.html</url>
  <content>iFolderトラフィックに対するローカルファイアウォールの設定 ローカルファイアウォールを使用する場合、iFolderがローカルのダイナミックポートを選択できるようにファイアウォールを設定するか、またはiFolderクライアントにローカルのスタティックポートを設定してローカル(同じコンピュータ)でMono® XSP Serverと通信できるようにします。iFolderはMono XSP Webサービスを使用して、iFolderアカウントを保持するNovell iFolderエンタープライズサーバとHTTP経由で通信します。iFolderの管理者は、iFolderサービスを設定して、ユーザ環境でHTTPを使用して通信するかどうかを指定します。 Mono XSPはトラフィックに対して標準的なHTTPポートを使用するので、お使いのファイアウォールが、Mono XSPとNovell iFolderエンタープライズサーバ間のトラフィックをブロックすることはありません。 ただし、クライアントとMono XSP間のトラフィックをブロックすると、クライアントはサーバと通信する手段を失います。 ユーザはiFolderアカウントにログインして、iFolderデータを同期できなくなります。 最初は、iFolder環境設定でクライアントとMono XSPとの通信で使用する特定のポートを指定しません。 iFolderをはじめて実行すると、Mono XSPからの要求をリッスンして、データをMono XSP経由でサーバに送信するための、使用可能なローカルポートが開かれます。 そのポート番号が環境設定ファイルに書き込まれ、それ以降iFolderを開始するときは、ポートが使用不可でない限り、常にこのポートが使用されます。 そのポートが別のアプリケーションで使用されている場合、iFolderは使用可能な別のポートを選択し、環境設定ファイルにそのポートを再設定し、以降はその新しいポートを使用します。たとえば、iFolderが停止中に他のアプリケーションがそのポートを使用すると、iFolderは再起動時に別のポートを選択してこれを使用するように設定する必要があります。 ローカルダイナミックポートの使用 お使いのコンピュータでローカルファイアウォールを使用する場合、iFolderがサーバに接続してユーザのリストとiFolderデータを同期するときは、ファイアウォールは常にiFolderとMono XSPサーバ間のローカルトラフィックを検出する必要があります。 このセッションでiFolderトラフィックを許可するには［ 許可］を選択します。トラフィックを永続的に許可すると、再度ファイアウォールによって通知されることはなく、iFolder起動時のポップアップ警告も表示されなくなります。 iFolderとMono XSPとの間のトラフィックをブロックすると、ファイアウォールによってiFolderサーバとの接続が切断されるため、ファイルを同期できなくなります。iFolderは、トラフィックがファイアウォールによってブロックされたことを検出せず、iFolderサーバ上のアカウントに接続できないことだけを報告します。 ローカルスタティックポートの使用 必要に応じて、 xspport.cfg ファイルのportセクションにWeb Service Portパラメータを追加することで、Mono XSPサーバがこのローカルトラフィック用にスタティックポートを使用するようにできます。これにより、ファイアウォールでこのポートが開かれ、Mono XSPとの通信が可能になります。 xspport.cfg ファイルは、次の場所にあります。 オペレーティングシステム Simias.configファイルの場所 Linux /home/ username /.local/share/simias/xspport.cfg Windows C:\Documents and Settings\ username \Local Settings\Application Data\simias\xspport.config Macintosh /Users/username/.local/share/simias/xspport.cfg システムを設定するには、特定のポートを使用します: ファイアウォールを、iFolderトラフィックで使用するポートでのトラフィックを許可するように設定します。 ファイアウォールのポートを開く方法については、お使いのファイアウォールのマニュアルを参照してください。 iFolderアイコンを右クリックしてから［ 終了］を選択して、iFolderクライアントを停止します。 Service ManagerセクションにWeb Service Port Rangeパラメータを追加することで、xspport.cfgファイルを変更します。 &lt;XspPortConfiguration&gt; &lt;Port&gt; monoxsp_port &lt;/Port&gt; &lt;/XspPortConfiguration&gt; monoxsp_port をポート番号に置き換えます: 単一のスタティックポートを使用する場合は、単一の4桁のポート番号の値(1234など)を指定します。 例を次に示します。 &lt;Port&gt; 1234 &lt;/Port&gt; iFolderクライアントを起動します。 詳細については、 を参照してください。 </content>
</topic>

<topic>
  <title>iFolderトラフィックに対するローカルウィルススキャナの設定</title>
  <url>../virusscan.html</url>
  <content>iFolderトラフィックに対するローカルウィルススキャナの設定 お使いのコンピュータでウィルススキャンソフトウェアを使用している場合は、 ..\simias\WorkArea\ ディレクトリをウィルススキャンの対象から除外してください。 たとえば、Windowsでの ..\simias\WorkArea\ ディレクトリの場所は、 c:\documents and settings\ username \local settings\application data\simias\WorkArea\.simias.wf. guid です。 ..\simias\WorkArea\ ディレクトリには、iFolderがサーバからダウンロードするファイルが配置されます。 iFolderファイルにウィルスが添付されている場合、そのファイルが ..\simias\WorkArea ディレクトリにある間はウィルススキャンソフトウェアがスキャンすることで、ウィルスが見つかったことを示すポップアップメッセージが表示され、そのファイルは隔離されます。その後で、iFolderは再度そのファイルを同期しようとします。 WorkAreaをスキャンしないことで、同期を終了させることができます。感染したファイルは正常にダウンロードされ、ローカルのiFolderに移動されます。次に、ウィルススキャナはiFoler内の感染ファイルを検出し、コンピュータが感染しないように、ファイルをそのフォルダから移動して隔離します。iFolderは、ファイルが削除されたことを確認し、次回の同期が開始すると、そのファイルをサーバおよびメンバーのコンピュータから削除します。 ただし、そのファイルがダウンロードされたiFolderが読み込み専用の場合は、ローカルでの削除はサーバと他のメンバーのコンピュータに対して実行されません。 そのウィルスは、変更内容の同期が許可されている他の場所で検出される必要があります。 多くの場合、ユーザのウィルススキャナによってウィルスの存在が警告されるので、ユーザは他のiFolderメンバーに、ウィルスについて警告する必要があります。 </content>
</topic>

<topic>
  <title>iFolderアカウントの削除</title>
  <url>../delacct.html</url>