<?xml version="1.0" encoding="UTF-8" ?>
<!-- saved from url=(0014)about:internet -->

<!DOCTYPE site [
 <!ELEMENT site (topic+)>
  <!ELEMENT topic (title,url,content)>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT url (#PCDATA)>
   <!ELEMENT content (#PCDATA)>
]>

<site>
<topic>
  <title>OES 2 SP1: ayuda interplataforma Novell iFolder 3.7</title>
  <url>../bookinfo.html</url>
  <content>OES 2 SP1: ayuda interplataforma Novell iFolder 3.7 3.7 October 2008 Ayuda de iFolder Novell® iFolder® es una aplicación para el uso compartido de archivos destinada a clientes Linux*, Windows* y Macintosh*. Con iFolder podrá disponer de los archivos locales automáticamente en cualquier lugar (con o sin conexión y en cualquier momento) en distintos equipos. Es posible compartir archivos en varias carpetas iFolder, cada una con diferentes usuarios. El usuario controla quién puede participar en una carpeta iFolder y los derechos de acceso a los archivos que contiene. También puede participar en carpetas iFolder que otros comparten con usted. Este sistema de ayuda describe cómo utilizar y gestionar el Cliente iFolder. Usuarios a los que va dirigida Esta guía está dirigida a usuarios del Cliente iFolder. Documentación adicional Si utiliza el Cliente iFolder 3.7 con un servidor empresarial o de acceso Web de Novell iFolder 3.7, consulte la iFolder 3.7 User Guide for Novell iFolder 3.7 (Guía del usuario de Novell iFolder 3.6) en el sitio Web de documentación de Novell iFolder . Convenciones de la documentación En la documentación de Novell, los símbolos mayor que (&gt;) se utilizan para separar acciones dentro de un paso y elementos en una ruta de referencia cruzada. Un símbolo de marca comercial (®, ™, etc.) indica una marca comercial de Novell. Un asterisco (*) sirve para identificar una marca comercial de otro fabricante. Cuando un nombre de vía de acceso se pueda escribir con una barra invertida para algunas plataformas y una barra normal para otras plataformas, el nombre de la vía de acceso aparecerá con una barra invertida. Los usuarios de plataformas que requieran la barra normal, como Linux o UNIX, deberán emplear la barra normal propia de su software. </content>
</topic>

<topic>
  <title>Descripción general de iFolder</title>
  <url>../overview.html</url>
  <content>Descripción general de iFolder Novell® iFolder® es una aplicación para el uso compartido de archivos destinada a clientes Linux, Windows y Macintosh. Es posible compartir archivos en varias carpetas iFolder, cada una con diferentes usuarios o grupos LDAP. El propietario controla quién puede participar en una carpeta iFolder y el nivel de acceso de cada miembro. También puede participar en carpetas iFolder que otros comparten con usted. iFolder 3.7 proporciona una interfaz sencilla y directa para la migración del cliente de iFolder 2. x a iFolder 3.6 y versiones posteriores, así como para la actualización del cliente de iFolder 3.. x a iFolder 3.6 y versiones posteriores. En esta sección aprenderá las distintas ventajas y funciones de iFolder: </content>
</topic>

<topic>
  <title>Ventajas de iFolder</title>
  <url>../benefits.html</url>
  <content>Ventajas de iFolder iFolder ofrece las siguientes ventajas: iFolder se integra con el entorno del escritorio nativo, lo que facilita la creación y la gestión de varias carpetas iFolder. iFolder es muy flexible y puede ampliarse fácilmente, con un número prácticamente ilimitado de carpetas iFolder por usuario o de miembros por carpeta iFolder. Si la opción de cifrado está habilitada, iFolder protege los datos que viajan a través del cable y los almacena en el servidor iFolder. Gracias a la consola de acceso Web mejorado, puede acceder a los archivos del servidor iFolder desde cualquier estación de trabajo que no disponga del Cliente iFolder y, mediante un navegador Web, realizar todas las operaciones que haría con el Cliente iFolder. Permite compartir archivos personales y comerciales de forma fácil y selectiva. iFolder puede migrar los datos de iFolder y actualizarlos a la versión más reciente. iFolder admite grupos LDAP. Permite compartir carpetas iFolder con grupos LDAP. Los miembros del grupo LDAP pueden crear y poseer carpetas iFolder, y compartirlas con otros usuarios individuales u otros grupos LDAP. Permite controlar el nivel de acceso de los usuarios miembro de las carpetas iFolder que posee o en las que dispone de los derechos necesarios para controlar los derechos de acceso de los miembros. iFolder actualiza los archivos de forma transparente en las carpetas iFolder miembro en varias estaciones de trabajo. Cuando se ejecuta iFolder, realiza un seguimiento de los cambios realizados mientras estaba desconectado y los registra, además de sincronizarlos en el momento de conectarse al servidor. iFolder proporciona la autenticación segura de los miembros que acceden a una carpeta iFolder para sincronizar sus datos. iFolder ofrece una alternativa al intercambio de archivos a través del correo electrónico, con lo que evita los límites de tamaño de los archivos adjuntos de los mensajes de correo electrónico y reduce los requisitos de almacenamiento del correo electrónico. </content>
</topic>

<topic>
  <title>El Cliente iFolder</title>
  <url>../bawqltp.html</url>
  <content>El Cliente iFolder El Cliente iFolder se integra con el sistema operativo para proporcionar servicios de iFolder en el entorno nativo de su escritorio. El Cliente iFolder permite gestionar las carpetas iFolder y seleccionar las carpetas iFolder compartidas que se van a configurar en cada equipo. iFolder es compatible con los siguientes sistemas operativos: SUSE® Linux Enterprise Desktop 10 SP1 Windows Vista SP1 Windows XP SP2/2000 Professional SP4 openSUSE® 10.2 y versiones posteriores Apple Macintosh® 10.4 y versiones posteriores </content>
</topic>

<topic>
  <title>Cuenta de iFolder</title>
  <url>../bawqmpe.html</url>
  <content>Cuenta de iFolder Se creará una cuenta de iFolder cuando un administrador de servicios de iFolder le asigne como usuario de iFolder en un servidor iFolder. El administrador le proporcionará un nombre de usuario y una contraseña. En el caso de una empresa, podrá tratarse del nombre de usuario o de la dirección de correo electrónico y la contraseña asociada. Debe configurar una cuenta de iFolder como mínimo antes de crear carpetas iFolder. Para obtener más información, consulte la . Una sesión de iFolder empieza al entrar en una cuenta de servicios de iFolder y finaliza al salir de la misma, o bien al salir del Cliente iFolder. Las carpetas iFolder sólo sincronizan archivos con otras carpetas iFolder activas cuando la sesión está activa y está funcionando en línea. Puede acceder a los datos de las carpetas iFolder locales en cualquier momento, independientemente de si ha entrado en la cuenta o no. Para obtener más información, consulte la . </content>
</topic>

<topic>
  <title>Consideraciones de interplataforma</title>
  <url>../ovwxplat.html</url>
  <content>Consideraciones de interplataforma Las interfaces de usuario de las versiones para Linux, Windows y Macintosh del Cliente iFolder siguen las convenciones de interfaz de sus plataformas individuales. La forma de realizar las tareas habituales es paralela en cada plataforma, pero es posible que se observen ligeras diferencias en los botones, el área de visualización, las etiquetas de función, la ubicación del área de notificación del escritorio, la preferencia de inicio de iFolder, etc., a medida que éstas se llevan a cabo. Excepto en los casos en que los procedimientos varían explícitamente, esta guía proporciona instrucciones para una de las tres plataformas únicamente. En la tabla siguiente se enumeran algunas de las diferencias y similitudes típicas de la interfaz del cliente: Tarea Linux Windows Macintosh Menú iFolder / Opción del botón derecho del ratón en el icono de la bandeja del sistema Salir Salir Salir Preferencias de iFolder &gt; Diálogo Cuentas Botón Añadir Botón Añadir Botón Más ( + ) Preferencias de iFolder Diálogo Cuentas Botón Eliminar Botón Eliminar Botón Menos ( - ) Varias ubicaciones Botón Cerrar Las acciones se confirman al llevar a cabo la acción Botones Aceptar , Cancelar y Aplicar Las acciones sólo se confirman al hacer clic en Aplicar o en Aceptar Botones Aceptar y Cancelar Las acciones se confirman al llevar a cabo la acción Diálogo Preferencias de iFolder Añada iFolder a los Programas de inicio del escritorio Seleccione (habilite) la opción Iniciar iFolder al entrar en el escritorio Esta característica no está disponible Configuración de una cuenta de iFolder Recordar mi contraseña Recordar contraseña en este equipo Recordar contraseña Área de notificaciones Área de notificaciones Estado y área de notificaciones Área de notificaciones Haga clic con el botón derecho en el área de notificaciones Ajustes de cuenta Cuentas Esta característica no está disponible iFolder de iFolder Propiedades Propiedades Obtener información Asistentes de iFolder Botones Adelante y Atrás Botones Siguiente y Atrás No hay botones para mover hacia delante y hacia atrás. Se puede configurar el nombre de usuario, la contraseña y el servidor en una sola ventana. Configuración de una cuenta de iFolder Asistente de cuenta iFolder Asistente de creación de cuentas de iFolder Preferencias &gt; Cuenta Asistente de configuración del servidor iFolder Servidor iFolder Seleccione un servidor iFolder No disponible Asistente de configuración de identidades de iFolder Identidad Información de cuenta de iFolder No disponible </content>
</topic>

<topic>
  <title>Funciones clave de iFolder</title>
  <url>../keyfeatures.html</url>
  <content>Funciones clave de iFolder Antes de comenzar a utilizar iFolder, es importante comprender las siguientes funciones clave: Compartición de carpetas iFolder Por lo general, al trabajar en varias ubicaciones o en colaboración con otros usuarios, debe gestionar con detenimiento las versiones de archivos. Con iFolder, podrá contar con la versión más reciente de sus archivos en cualquier equipo en el que tenga instalado el Cliente iFolder y haya creado una carpeta iFolder para ellos. iFolder también permite compartir varias carpetas iFolder y su contenido independiente con otros usuarios autorizados o grupos LDAP. Para obtener más información sobre carpetas iFolder compartidas, consulte . Es posible compartir archivos con el Cliente iFolder mediante la sincronización de archivos en varios equipos a través de un servidor central. iFolder permite realizar las acciones siguientes: Compartir archivos en varios equipos Compartir archivos con otros usuarios Poseer varias carpetas iFolder Participar en varias carpetas iFolder compartidas con otros usuarios Participar como propietario o como miembro de carpetas iFolder en varias cuentas Puede trabajar con las carpetas iFolder directamente en el gestor de archivos o en el navegador de iFolder que forma parte del cliente. En la carpeta iFolder, es posible configurar cualquier estructura de subdirectorios que se adecue a los hábitos de trabajo personales o de la empresa. La estructura de subdirectorios es constante en todas las carpetas iFolder miembro. Carpetas iFolder compartidas Una carpeta iFolder es un directorio local que comparte y sincroniza archivos de forma selectiva través de un servidor central con un grupo de usuarios especificado por el usuario. Todos los miembros en la carpeta iFolder pueden acceder a los archivos de iFolder, así como modificarlos si disponen de los derechos necesarios. Puede acceder a las carpetas iFolder en distintas estaciones de trabajo y compartirlas tanto con usuarios individuales como con grupos LDAP. El propietario decide quién participa en cada carpeta iFolder y el nivel de acceso de cada miembro. De forma similar, es posible participar en carpetas iFolder compartidas propiedad de otros usuarios de su entorno de colaboración. Al compartir una carpeta iFolder, los usuarios miembro con permiso de escritura pueden modificar la estructura de directorios. Los cambios realizados se aplicarán a todas las copias de dicha carpeta iFolder. Cada usuario puede buscar la carpeta iFolder compartida en cualquier ubicación de su equipo si cumple con los requisitos de . Derechos de acceso a iFolder El Cliente iFolder es compatible con el propietario y tres niveles de acceso para miembros en una carpeta iFolder: Los miembros de un grupo LDAP heredan el conjunto de derechos de acceso de dicho grupo. Propietario: Sólo un usuario puede ser el propietario de una carpeta iFolder. Por lo general, se trata del usuario que crea la carpeta iFolder. El usuario propietario puede utilizar el Cliente iFolder para transferir la propiedad a otro miembro de la carpeta iFolder. El propietario de una carpeta iFolder tiene el derecho de control total. Este usuario tiene acceso de lectura/escritura a la carpeta iFolder, gestiona la pertenencia y los derechos de acceso de los usuarios miembro, y puede quitar el derecho de control total a cualquier miembro. Si un grupo LDAP es propietario de una carpeta iFolder, todos los usuarios miembro de dicho grupo disponen del derecho de control total. Control total: Miembro de una carpeta iFolder compartida con derecho de acceso de control total. Este miembro tiene acceso de lectura/escritura a la carpeta iFolder y gestiona la pertenencia y los derechos de acceso de todos los usuarios, excepto del propietario. Lectura/Escritura: Miembro de una carpeta iFolder compartida con derecho de acceso de lectura/escritura a los directorios y archivos de dicha carpeta iFolder. Este miembro puede modificar un archivo, pero los cambios locales se sincronizarán con las copias de otros miembros de la carpeta iFolder. Sólo lectura: Miembro de una carpeta iFolder compartida con derecho de acceso de sólo lectura a los directorios y archivos de dicha carpeta iFolder. Este miembro puede modificar un archivo, pero los cambios locales no se sincronizarán con las copias de otros miembros de la carpeta iFolder. Cualquier usuario de iFolder puede ser el propietario de varias carpetas iFolder y ser miembro de otras. El usuario propietario siempre posee el derecho de control total. En calidad de usuario miembro, el nivel de acceso a cada carpeta iFolder compartida puede variar en función del acceso que le haya otorgado cualquier miembro con derecho de control total. Sincronización de archivos Cuando está conectado al servidor, iFolder puede sincronizar la pertenencia a una carpeta iFolder y los archivos de ésta en segundo plano mientras el usuario realiza su trabajo. Al configurar una cuenta de iFolder, puede habilitar la opción Recordar mi contraseña para que iFolder recuerde la contraseña en ese equipo. De este modo, la próxima vez que inicie iFolder, la conexión con el servidor se establecerá automáticamente y se sincronizarán los datos sin que se le solicite la contraseña. Es posible configurar el Cliente iFolder para que se ejecute automáticamente cada vez que entre al entorno de escritorio del equipo. La sesión se ejecuta en segundo plano mientras se trabaja con los archivos de las carpetas iFolder locales, y se lleva a cabo el registro y seguimiento de los cambios efectuados. Es posible sincronizar los archivos manualmente o a intervalos especificados. iFolder también incluye funciones de sincronización delta. Cuando realiza algún cambio en un archivo de una carpeta iFolder, sólo se sincronizan los delta o los cambios con el servidor. O, lo que es lo mismo, la sincronización delta sólo recupera las actualizaciones desde la última sincronización efectuada entre el Cliente iFolder y el servidor. De este modo se incrementa la eficacia, ya que se reduce el tiempo de sincronización. Migración Novell iFolder proporciona una migración sencilla y sin problemas de iFolder 2. x al Cliente iFolder de Novell iFolder 3.7. El Asistente de migración incluido en el Cliente iFolder permite migrar los datos existentes de iFolder 2. x a iFolder 3.6 de una manera sencilla y rápida. Para obtener más información, consulte la . Cifrado iFolder proporciona una mayor seguridad para los archivos de carpetas iFolder confidenciales con el fin de protegerlos de posibles accesos por parte de usuarios no autorizados, ya sea de manera intencionada o no intencionada. Anteriormente, la protección de los datos no estaba del todo asegurada en el servidor, por lo que el administrador o cualquier usuario que obtuviera acceso no autorizado al servidor podía acceder a los datos. Asimismo, al acceder a los archivos de carpetas iFolder a través de un proveedor ISP, existe el riesgo de que un usuario no autorizado pueda acceder sin darse cuenta a sus archivos confidenciales. Ahora, sin embargo, puede cifrar y guardar los archivos en el servidor y recuperarlos por medio de una contraseña codificada que sólo usted conoce. Si la olvida, el agente de recuperación que haya seleccionado durante la creación de la carpeta iFolder cifrada le ayudará a recuperar los datos. La ilustración siguiente le proporciona una idea de cómo iFolder puede recuperar los datos perdidos. No es posible compartir las carpetas iFolder cifradas Para obtener más información sobre el cifrado, consulte . Actualizar iFolder 3.7 de Novell permite realizar una sencilla actualización de iFolder 3. x al Cliente iFolder de iFolder 3.6 de Novell y versiones posteriores. Para obtener más información, consulte la . Fusionar Mediante la opción de fusión, puede consolidar los datos de iFolder y minimizar la transferencia de datos entre el Cliente y el servidor iFolder. Esta opción también le permite cambiar la ubicación de una carpeta en el equipo cliente. Para obtener más información, consulte la . Carpeta iFolder por defecto iFolder permite definir una carpeta iFolder por defecto durante la configuración de una cuenta nueva. Al configurar una cuenta de iFolder nueva, iFolder comprueba automáticamente la presencia de una carpeta iFolder por defecto. Si no ha creado ninguna, iFolder le pedirá que lo haga. Si ya existe, el Cliente iFolder le solicitará que la descargue. Si lo desea, también puede omitir ambas opciones. Para obtener más información, consulte el en . Acceso Web mejorado iFolder incluye una interfaz Web mejorada que permite acceder a los archivos de carpetas iFolder ubicados en servidores remotos. Con la consola de Web Access, puede utilizar un navegador Web para acceder a los archivos del servidor iFolder desde cualquier estación de trabajo sin disponer del Cliente iFolder. La interfaz de Web Access permite realizar todas las operaciones del Cliente iFolder. En comparación con las versiones anteriores de iFolder, iFolder 3.6 y las versiones posteriores permiten crear, examinar, compartir, cargar y suprimir carpetas iFolder a través de la consola mejorada de Web Access. Los usuarios móviles también podrán beneficiarse de esta funcionalidad a través de Internet. Registro de sincronización El registro de sincronización muestra un registro de la actividad en segundo plano de la carpeta iFolder como, por ejemplo, la carga y descarga de archivos de distintas carpetas iFolder, las infracciones de directivas, los archivos excluidos o los archivos no sincronizados. </content>
</topic>

<topic>
  <title>Pasos siguientes</title>
  <url>../ovwnext.html</url>
  <content>Pasos siguientes Para obtener información acerca de la configuración mediante el Cliente iFolder, consulte las secciones siguientes: </content>
</topic>

<topic>
  <title>Gestión de cuentas y preferencias de iFolder</title>
  <url>../accountsprefs.html</url>
  <content>Gestión de cuentas y preferencias de iFolder En esta sección se describe cómo configurar las cuentas de iFolder™ y cómo gestionar las preferencias del Cliente iFolder </content>
</topic>

<topic>
  <title>Inicio del Cliente iFolder</title>
  <url>../startclient.html</url>
  <content>Inicio del Cliente iFolder Cuando se ejecuta iFolder, el icono Servicios de iFolder aparecerá en el área de notificaciones de la barra de tareas. iFolder se integra así en el entorno del escritorio. El emblema de iFolder (una “i” verde) aparece en las carpetas iFolder cuando se visualizan en un gestor de archivos, en el escritorio o en el navegador de iFolder. La carpeta iFolder cifrada se indica por el emblema (carpeta bloqueada). El área de notificaciones de la barra de tareas debe estar habilitada para que se muestre el icono Servicios de iFolder cuando se ejecuta iFolder. Es posible trabajar en local con archivos de las carpetas iFolder locales en cualquier momento. Cuando se ejecute el Cliente iFolder, éste registrará los cambios que realice el usuario en los datos de la carpeta iFolder local a medida que se produzcan. Si realiza cambios en los datos de la carpeta iFolder local sin que se esté ejecutando iFolder, éste identificará y registrará las diferencias la próxima vez que se inicie. Cuando no se ejecuta, las carpetas de iFolder aparecerán en el gestor de archivos o en el escritorio. Es posible acceder a los archivos de la copia local de una carpeta iFolder, aunque no se podrán gestionar las carpetas iFolder. Asimismo, deberá entrar en una cuenta para poder crear una carpeta iFolder o sincronizar archivos. Durante la creación de cuentas, la entrada del usuario se produce a través de SSL. Cuando el sistema le solicita que acepte el certificado del servidor, debe validar el certificado y aceptarlo para que la conexión se realice correctamente. Para obtener información acerca de la detención del Cliente iFolder, consulte Linux Inicio automático de iFolder al entrar Para permitir que iFolder se inicie automáticamente al entrar al escritorio, realice una de las siguientes acciones: Abra el menú de aplicaciones, haga clic en Más aplicaciones , localice iFolder 3 , haga clic con el botón derecho en él y, a continuación, seleccione Añadir a los programas de inicio en el menú que aparece. Asegúrese de que iFolder se esté ejecutando cuando salga y, a continuación, guarde la configuración de la sesión. Seleccione esta opción de sesión cuando entre al escritorio. Abra una ventana de terminal, entre como usuario root y, a continuación, ejecute /opt/gnome/bin/gnome-session-properties para añadir iFolder como programa de inicio cuando entre en el equipo. Para evitar que iFolder se inicie automáticamente al entrar, realice una de las siguientes acciones: Abra el menú de aplicaciones, localice iFolder 3 , haga clic con el botón derecho en él y, a continuación, seleccione Eliminar de los programas de inicio . Asegúrese de que iFolder no se esté ejecutando cuando salga y, a continuación, guarde la configuración de la sesión. Seleccione esta opción de sesión cuando entre al escritorio. Inicio manual de iFolder Entre en el equipo con la identidad de usuario local de Linux que desee utilizar al crear carpetas iFolder. Para iniciar iFolder, utilice uno de los métodos siguientes: En la barra de tareas, abra el menú de aplicaciones, haga clic en Más aplicaciones , localice iFolder 3 mediante una búsqueda o desplazándose por las opciones disponibles, haga clic con el botón derecho en iFolder 3 y, finalmente, seleccione Iniciar iFolder 3 . Abra un shell de terminal y, a continuación, introduzca /opt/novell/ifolder3/bin/ifolder Windows Inicio automático de iFolder al entrar Para que iFolder se inicie automáticamente al entrar al escritorio: Haga clic con el botón derecho en el icono Servicios de iFolder y, a continuación, seleccione Preferencias para abrir la pestaña General del recuadro de diálogo Preferencias de iFolder. Seleccione Iniciar iFolder al entrar en el escritorio y, a continuación, haga clic en Aplicar . Haga clic en Aceptar para cerrar el recuadro de diálogo Preferencias de iFolder. Para evitar que iFolder se inicie automáticamente al iniciar sesión en el escritorio: Haga clic con el botón derecho en el icono Servicios de iFolder y, a continuación, seleccione Preferencias para abrir la pestaña General del recuadro de diálogo Preferencias de iFolder. Deseleccione la opción Iniciar iFolder al entrar en el escritorio y, a continuación, haga clic en Aplicar . Haga clic en Aceptar para cerrar el recuadro de diálogo Preferencias de iFolder. Inicio manual de iFolder Entre al equipo con la identidad de usuario de Windows local que desea utilizar al crear carpetas iFolder. Si iFolder no se inicia automáticamente al entrar correctamente, haga clic en Inicio Programas iFolder 3 y, a continuación, seleccione la aplicación Cliente iFolder 3 . Macintosh Inicio automático de iFolder al entrar Si desea que iFolder se inicie automáticamente al entrar al equipo Macintosh, añada iFolder a los elementos del menú Inicio . Inicie iFolder. En el Dock (muelle), haga clic con el botón derecho en el icono iFolder y seleccione la opción Abrir al entrar a la sesión . O bien En el Dock (muelle) pulse la tecla Control, haga clic en el icono iFolder y, a continuación, seleccione Abrir al entrar a la sesión . Para que iFolder no se inicie de manera automática, elimine iFolder de los elementos del menú Inicio . En el Dock (muelle), haga clic con el botón derecho en el icono iFolder y deseleccione la opción Abrir al entrar a la sesión . O bien En el Dock (muelle), haga clic con el botón derecho o con la tecla Control en el icono iFolder y, a continuación, deseleccione la opción Abrir al entrar a la sesión . Inicio manual de iFolder Entre al equipo con la identidad de usuario local de Macintosh que desee utilizar al crear carpetas iFolder. Para iniciar iFolder, utilice uno de los métodos siguientes: Abra el directorio Aplicaciones en el disco de Macintosh , seleccione Aplicaciones y, a continuación, haga doble clic en iFolder 3 . Escriba iFolder en el Spotlight (foco) (botón Apple + barra espaciadora o haga clic en el icono de lupa de la parte superior derecha) y, a continuación, haga clic en la carpeta iFolder 3 en Aplicaciones. Abra un shell de terminal, entre como usuario Root (raíz) y, a continuación, especifique /Applications/iFolder 3.app/Contents/MacOS/iFolder 3 </content>
</topic>

<topic>
  <title>Configuración de una cuenta de iFolder</title>
  <url>../accounts.html</url>