<?xml version="1.0" encoding="UTF-8" ?>
<!-- saved from url=(0014)about:internet -->

<!DOCTYPE site [
 <!ELEMENT site (topic+)>
  <!ELEMENT topic (title,url,content)>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT url (#PCDATA)>
   <!ELEMENT content (#PCDATA)>
]>

<site>
<topic>
  <title>Novell iFolder 3.8 跨平台帮助</title>
  <url>../bookinfo.html</url>
  <content>Novell iFolder 3.8 跨平台帮助 3.8 iFolder 帮助 Novell® iFolder® 是用于 Linux*、Windows* 和 Macintosh* 客户端的文件共享应用程序。使用 iFolder，您的本地文件将跨过多台计算机自动跟随在您的左右，无论您处于联机还是脱机状态，都始终相伴，形影不离。您可以在多个 iFolder 中共享文件，每个 iFolder 都有不同的用户。您可以控制哪些用户可以加入 iFolder 以及他们对 iFolder 中文件的访问权限。您还可以加入其他用户与您共享的 iFolder。 本帮助系统介绍如何使用和管理 iFolder 客户程序。 适用对象 本指南适用于 iFolder 客户程序的用户。 其他文档 如果在 Novell iFolder 3.7 或更高版本 Enterprise Server 或万维网访问服务器上使用 iFolder 3.7 或更高版本客户程序，请参见 Novell iFolder 文档网站 上的 iFolder 3.8 用户指南 。 文档约定 在 Novell 文档中，大于号 (&gt;) 用于分隔步骤内的操作和交叉参照路径中的项目。 商标符号（®、™ 等）代表一个 Novell 商标。星号 (*) 表示第三方商标。 如果某个路径名的书写对某些平台需使用反斜线而对另一些平台需使用正斜线，则使用反斜线表示该路径名。在要求用正斜线的平台（例如 Linux 或 UNIX）上，用户应根据软件的要求使用正斜线。 </content>
</topic>

<topic>
  <title>iFolder 概述</title>
  <url>../overview.html</url>
  <content>iFolder 概述 Novell® iFolder® 是用于 Linux、Windows 和 Macintosh 客户端的文件共享应用程序。您可在多个具有不同用户或 LDAP 组的 iFolder 中共享文件。您可以控制哪些用户可以加入 iFolder 以及每个成员的访问级别。您还可以加入其他用户与您共享的 iFolder。 iFolder 提供了一个简单易用的用户界面，可在客户端上从 iFolder 2. x 迁移到 iFolder 3.6 和更高版本，并可在客户端从 iFolder 3. x 升级到 iFolder 3.6 和更高版本。 本节旨在让您熟悉一下 iFolder 的各种优点和功能： </content>
</topic>

<topic>
  <title>iFolder 的优点</title>
  <url>../benefits.html</url>
  <content>iFolder 的优点 iFolder 具有以下优点： iFolder 与您的本机桌面环境相集成，从而更易于创建和管理多个 iFolder。 iFolder 高度灵活且可伸缩，对于每个用户的 iFolder 数或每个 iFolder 的成员数都没有任何实际限制。 启用加密功能后，iFolder 将在数据跨网移动和储存在 iFolder 服务器上时保护数据的安全。 使用增强的万维网访问控制台，您可从未安装 iFolder 客户程序的任何工作站访问您存放在 iFolder 服务器上的文件，并可使用万维网浏览器执行 iFolder 客户程序的所有操作。 您可轻松选择共享个人文件或业务文件。 iFolder 可将您的 iFolder 数据迁移和升级到最新版本。 iFolder 支持 LDAP 组。您可与 LDAP 组共享 iFolder。LDAP 组的成员可以创建和拥有 iFolder 并可与其他单个用户或其他 LDAP 组共享 iFolder。 您可控制您拥有的 iFolder 的成员用户的访问级别，或者，如果您有必需的权限，还可控制成员的访问权限。 iFolder 透明地将您的文件更新到多个工作站上的成员 iFolder。 iFolder 运行时，可跟踪和记录您脱机工作时所作的更改，并在连接到服务器时同步这些更改. iFolder 为访问 iFolder 以同步其数据的成员进行安全鉴定。 iFolder 提供了一种通过电子邮件交换文件的替代方法，从而避免了电子邮件附件的文件大小限制并降低了电子邮件储存要求。 </content>
</topic>

<topic>
  <title>iFolder 客户程序</title>
  <url>../bawqltp.html</url>
  <content>iFolder 客户程序 iFolder 客户程序可与您的操作系统集成以在本机桌面环境中提供 iFolder 服务。通过使用 iFolder 客户程序，您可以管理自己的 iFolder，并且可以选择要在每台计算机上设置的共享 iFolder。iFolder 支持以下操作系统： SUSE® Linux Enterprise Desktop 10 SP1和 SP2 SUSE Linux Enterprise Desktop 11 Windows Vista SP1 Windows XP SP2 OpenSUSE 11.1 Apple Macintosh® 10.4 和更高版本 </content>
</topic>

<topic>
  <title>iFolder 帐户</title>
  <url>../bawqmpe.html</url>
  <content>iFolder 帐户 iFolder 帐户是在 iFolder 服务管理员将您设置为 iFolder 服务器的一个 iFolder 用户时创建的。管理员会向您提供用户名和口令。对于企业而言，这可能是您的用户名或电子邮件地址以及相关的口令。在创建 iFolder 之前，您必须至少配置一个 iFolder 帐户。有关更多信息，请参见 。 当您登录到某个 iFolder 服务帐户时，即会开始一个 iFolder 会话；当您注销该帐户或退出 iFolder 客户程序时，iFolder 会话就结束。仅当您的会话处于活动状态且您正在联机工作时，iFolder 才与其他活动 iFolder 同步文件。无论您是否已登录到帐户，都可随时访问本地 iFolder 中的数据。有关信息，请参见 。 </content>
</topic>

<topic>
  <title>跨平台注意事项</title>
  <url>../ovwxplat.html</url>
  <content>跨平台注意事项 Linux、Windows 和 Macintosh 版本的 iFolder 客户程序的用户界面符合各自平台的界面规范。在每个平台中执行普通任务的方式都相同，但您在执行任务时可能会发现一些细微的差异，这些差异体现在按钮、显示区域、功能标签、桌面通知区域的位置、启动 iFolder 首选设置等方面。除了步骤存在明显差异的地方外，本指南只提供这三个平台中一个平台的说明。 下表列出了客户端界面中的典型不同和相似之处。 任务 Linux Windows Macintosh iFolder 菜单 退出 退出 退出 “iFolder 首选设置” &gt; “帐户”对话框 “添加” 按钮 “添加” 按钮 “加号” ( + ) 按钮 “iFolder 首选设置” &gt; “帐户”对话框 “去除” 按钮 “去除” 按钮 “减号” ( - ) 按钮 多个位置 “关闭” 按钮 执行操作后即提交操作 “确定” 、 “取消” 和 “应用” 按钮 仅当单击 “应用” 或 “确定” 后才提交操作 “确定” 和 “取消” 按钮 执行操作后即提交操作 “iFolder 首选设置” 对话框 将 iFolder 添加到桌面的 启动程序 选择（启用） “登录到桌面时启动 iFolder” 此功能不可用 配置 iFolder 帐户 保存我的口令 在此计算机上保存口令 保存口令 “通知”区域 “通知”区域 “状态和通知”区域 “通知”区域 右击通知区域 帐户设置 帐户 此功能不可用 iFolder iFolder 菜单 属性 属性 获取信息 iFolder 向导 “向前” 按钮和 “后退” 按钮 “下一个” 按钮和 “上一个” 按钮 没有用于前后移动的按钮。您可在一个窗口中配置用户名、口令和服务器。 配置 iFolder 帐户 iFolder 帐户助理 iFolder 帐户创建向导 首选设置 &gt; 帐户 iFolder 服务器配置向导 iFolder 服务器 选择一个 iFolder 服务器 不可用 iFolder 身份配置向导 身份 iFolder 帐户信息 不可用 </content>
</topic>

<topic>
  <title>iFolder 的主要功能</title>
  <url>../keyfeatures.html</url>
  <content>iFolder 的主要功能 在开始使用 iFolder 之前，必须先了解以下主要功能： iFolder 共享 通常，当您在多个地点工作或与其他人合作时，您必须认真负责地管理文件版本。 使用 iFolder，您就可以将最新版本的文件放置到您安装了 iFolder 客户程序并且为这些文件创建了一个 iFolder 的任何计算机上。iFolder 还允许您与其他授权用户或 LDAP 组共享多个 iFolder 及其各自的内容。有关共享 iFolder 的更多信息，请参见 。 iFolder 客户程序通过中央服务器同步多台计算机上的文件，从而实现对共享的支持。它允许您执行以下操作： 在多台计算机上共享文件 与其他用户共享文件 拥有多个 iFolder 参与其他用户共享给您的多个 iFolder 以 iFolder 的拥有者或成员的身份通过多个帐户参与 可以直接在文件管理器中或 iFolder 浏览器（iFolder 客户程序的一部分）中处理 iFolder。在 iFolder 中，您可以根据个人或公司的工作习惯设置任何子目录结构。子目录结构在所有成员 iFolder 中是稳定的。 共享的 iFolder 一个 iFolder 是一个本地目录，可选择性地通过中央服务器与用户指定的用户共享和同步文件。所有 iFolder 成员都可以访问 iFolder 文件，具有适当权限的成员可以更改 iFolder 文件。您可跨多个工作站来访问 iFolder 并可与单个用户和 LDAP 组共享它们。 您可以决定每个 iFolder 有哪些用户参与以及每个成员的访问级别。同样，您也可以参与协作环境中其他用户拥有的共享 iFolder。当您共享 iFolder 时，具有“写入”权限的成员用户可以修改目录结构，并且这些更改将应用于 iFolder 的所有副本。如果共享 iFolder 符合 的要求，则每个用户都可以将其放在自己计算机的任何位置上。 iFolder 访问权限 iFolder 客户程序支持拥有者和三种 iFolder 成员访问级别： LDAP 组的成员将继承该组的访问权限集。 拥有者： 只有一个用户担当 iFolder 的拥有者。这通常是创建该 iFolder 的用户。拥有者用户可以使用 iFolder 客户程序将所有权转让给 iFolder 的另一个成员。 iFolder 的拥有者具有“完全控制”权限。此用户对该 iFolder 具有读/写权限，管理成员用户的成员资格和访问权限并可去除任何成员的完全控制权限。 如果某一 LDAP 组拥有一个 iFolder，则该组的所有成员用户将被授予完全控制权限。 完全控制： 共享 iFolder 的成员，具有“完全控制”访问权限。此成员对该 iFolder 具有读/写权限，管理拥有者之外的所有用户的成员资格和访问权限。 读/写： 共享 iFolder 的成员，对 iFolder 中的目录和文件具有“读/写”访问权限。此成员可以修改文件，但所做的本地更改也会被同步到其他成员的 iFolder 副本。 只读： 共享 iFolder 的成员，对 iFolder 中的目录和文件具有“只读”访问权限。此成员可以修改文件，但所做的本地更改不会被同步到其他成员的 iFolder 副本。 任何 iFolder 用户或 LDAP 组都可拥有某些 iFolder 并可以是其他 iFolder 的成员。作为拥有者用户，您始终具有“完全控制”权限。作为成员用户，您在每个共享 iFolder 中的访问级别可能各不相同，具体取决于由具有“完全控制”权限的成员授予您的访问权限。 文件同步 当您连接到服务器时，iFolder 可以在您工作时在后台同步 iFolder 成员资格和文件。设置 iFolder 帐户后，即可启用 “保存我的口令” 以便 iFolder 在该计算机上保存口令，当您下次起动 iFolder 时，它将自动连接到服务器并同步数据而不提示输入口令。 您可以将 iFolder 客户程序配置为在每次登录计算机的桌面环境时自动运行。当您对本地 iFolder 中的文件进行处理时，该会话在后台运行，跟踪并记录您所做的任何更改。 可以手动或者以指定的间隔同步文件。 iFolder 也具有增量同步功能。对 iFolder 文件进行更改后，只将增量或更改同步到服务器。换句话说，增量同步只检索自 iFolder 客户程序和服务器上次同步后的更新。这将会提高效率，因为减少了同步时间。 迁移 Novell iFolder 提供了一个简单易用的用户界面，可在客户端上从 iFolder 2.x 迁移至 iFolder 3.6 和更高版本。iFolder 客户程序中提供的迁移向导可帮助您将现有的 iFolder 2. x 数据简便快速地迁移到 iFolder 3.6 和更高版本。有关更多信息，请参见 。 加密 iFolder 为您的机密 iFolder 文件提供了更高的安全性，可防止未授权用户有意或无意地访问这些文件。过去在服务器一端，数据安全无法保障，所以数据可以被管理员或对服务器拥有未经授权的访问权限的任何人访问。此外，当您通过 ISP 提供商访问 iFolder 时，未经授权的个人可能会有机会发现您的机密文件。现在，您可以对文件加密并将其保存到服务器上，然后通过只有您知道的通行口令来检索它们。如果您忘记通行口令，则在创建加密 iFolder 过程中选择的恢复代理可帮助您恢复数据。 无法共享加密的 iFolder。 有关加密的更多信息，请参见 。 升级 Novell iFolder 提供了一种简单的升级方法，可从 iFolder 3. x 升级到 Novell iFolder 3.6 和更高版本的客户程序。有关更多信息，请参见 。 合并 使用合并功能，您可以合并 iFolder 数据并将 iFolder 客户程序和服务器之间的数据传输量降至最低。另外，您还可以使用此功能将现有文件夹移动到客户机上的其他位置。有关更多信息，请参见 。 默认 iFolder iFolder 允许您在配置新帐户时设置默认 iFolder。当您配置新的 iFolder 帐户时，iFolder 将自动检查是否存在默认 iFolder。如果您尚未创建默认 iFolder，则 iFolder 将提示您创建一个。如果已存在默认值，则 iFolder 客户程序将提示您进行下载。您也可以忽略这两个选项。有关更多信息，请参见 中的 。 增强型万维网访问 iFolder 提供一个增强型万维网界面，它允许您访问远程服务器上您的 iFolder 文件。使用万维网访问控制台，您可使用万维网浏览器从未安装 iFolder 客户程序的任何工作站来访问您在 iFolder 服务器上的文件。使用万维网访问界面，您可执行 iFolder 客户程序的拥有操作。 与以前的 iFolder 版本相比较，iFolder 3.6 和更高版本允许您通过增强的万维网访问控制台来创建、浏览、共享、上载和删除 iFolder。移动用户也可以通过万维网使用此功能。 同步日志 同步日志显示您的 iFolder 后台活动的日志，如为不同 iFolder 上载和下载文件、违反策略、已排除的文件以及未同步的文件。 </content>
</topic>

<topic>
  <title>下一步</title>
  <url>../ovwnext.html</url>
  <content>下一步 有关使用 iFolder 客户程序进行配置的信息，请参见以下内容： </content>
</topic>

<topic>
  <title>管理 iFolder 帐户和首选设置</title>
  <url>../accountsprefs.html</url>
  <content>管理 iFolder 帐户和首选设置 本节介绍如何配置 iFolder™ 帐户和如何管理 iFolder 客户程序的首选设置。 </content>
</topic>

<topic>
  <title>启动 iFolder 客户程序</title>
  <url>../startclient.html</url>
  <content>启动 iFolder 客户程序 当 iFolder 运行时， “iFolder 服务” 图标将显示在任务栏的通知区域上。iFolder 已集成到桌面环境中。当在文件管理器、桌面或 iFolder 浏览器中查看 iFolder 时，iFolder 徽标（绿色的“i”） 会显示在 iFolder 上。加密的 iFolder 由 徽标（锁定的文件夹）表示。 必须启用任务栏的通知区域，才能在 iFolder 运行时显示 iFolder 服务 图标。 您可以随时对本地 iFolder 中的文件进行本地操作。无论 iFolder 客户程序是否正在运行，它都会记录您在操作期间对本地 iFolder 数据所作的更改。如果您在未运行 iFolder 时对本地 iFolder 数据作了更改，则 iFolder 会在您下次启动它时标识和记录这些差异。 当 iFolder 未在运行时，iFolder 将显示在文件管理器或桌面上。您可以访问 iFolder 本地拷贝中的文件，但不能管理 iFolder。此外，您必须登录到一个帐户才能创建 iFolder 或同步其文件。 创建帐户期间，用户通过 SSL 进行登录。当系统提示您是否接受服务器证书时，必须验证并接受该证书，才能成功连接。 有关停止 iFolder 客户程序的信息，请参见 。 Linux 登录时自动启动 iFolder 若要启用在登录到桌面时自动启动 iFolder，请执行下列操作之一： 打开应用程序菜单，单击 “更多应用程序” ，找到 “iFolder 3” 并右击，然后从菜单中选择 “添加到启动程序” 。 确保注销时 iFolder 正在运行，然后保存会话设置。当您登录到桌面时选择此会话选项。 打开一个终端窗口，以 root 用户身份登录，然后运行 /opt/gnome/bin/gnome-session-properties 可将 iFolder 添加为登录到计算机时要启动的程序。 若要禁止在登录时自动启动 iFolder，请执行下列操作之一： 打开应用程序菜单，找到 “iFolder 3” 并右击，然后选择 “从启动程序中去除” 。 确保注销时 iFolder 未运行，然后保存会话设置。当您登录到桌面时选择此会话选项。 手动启动 iFolder 以创建 iFolder 时要使用的本地 Linux 用户身份登录到计算机。 使用以下方法之一启动 iFolder： 在任务栏中，打开应用程序菜单，单击 “更多应用程序” ，通过搜索或滚动可用选项查找 “iFolder 3” ，右击“iFolder 3”，然后选择 “启动 iFolder 3” 。 打开终端壳层，然后输入 /usr/bin/ifolder Windows 登录时自动启动 iFolder 要在登录到桌面时自动启动 iFolder： 右击 “iFolder 服务” 图标，然后选择 “首选设置” 以打开“iFolder 首选设置”对话框并进入 “常规” 选项卡。 选择 “登录到桌面时启动 iFolder” ，然后单击 “应用” 。 单击 “确定” 关闭“iFolder 首选设置”对话框。 禁止“登录到桌面时自动启动 iFolder”： 右击 iFolder 服务 图标，然后选择 “首选设置” 以打开“iFolder 首选设置”对话框并进入 “一般” 选项卡。 取消选择 “登录到桌面时启动 iFolder” ，然后单击 “应用” 。 单击 “确定” 关闭“iFolder 首选设置”对话框。 手动启动 iFolder 使用创建 iFolder 时要使用的本地 Windows 用户身份登录到计算机。 如果成功登录时 iFolder 未自动启动，则通过单击 “开始” “程序” “iFolder 3” 来启动 iFolder，然后选择 “iFolder 3 客户程序” 应用程序。 Macintosh 登录时自动启动 iFolder 要在登录到 Macintosh 计算机时自动启动 iFolder，应将 iFolder 添加到 “启动项目” 。 启动 iFolder。 从对接台右击 iFolder 图标并选择 “登录时打开” 选项。 或 从对接台按下 Ctrl 键，单击 iFolder 图标，然后选择 “登录时打开” 。 要禁用自动启动 iFolder，请从 “启动项目” 中去除 iFolder。 从对接台右击 iFolder 图标，然后取消选择 “登录时打开” 。 或 从对接台右击或按下 Ctrl 并单击 iFolder 图标，然后取消选择 “登录时打开” 。 手动启动 iFolder 使用要在创建 iFolder 时使用的本地 Macintosh 用户身份登录到计算机。 使用以下方法之一启动 iFolder： 打开 Macintosh HD 上的 “应用程序” 目录，选择 “应用程序” ，然后双击 “iFolder 3” 。 在聚光灯中键入 iFolder （Apple 按钮 + 空格键或单击右上部的放大镜图标），然后单击“应用程序”下的 “iFolder 3” 。 打开终端壳层，以根用户身份登录，然后输入 /Applications/iFolder 3.app/Contents/MacOS/iFolder 3 </content>
</topic>

<topic>
  <title>配置 iFolder 帐户</title>
  <url>../accounts.html</url>
  <content>配置 iFolder 帐户 使用 iFolder 帐户创建向导 添加并配置新帐户。您必须至少配置一个 iFolder 帐户才能创建 iFolder 或在系统上共享 iFolder。在任何给定时间均可使用一个帐户连接到 iFolder 服务器。但如果要连接到多个 iFolder 服务器，则可以配置多个帐户。您可以分别登录到每个帐户，也可以同时登录多个帐户。 持有不同本地登录身份的多个用户可以在同一台计算机上拥有 iFolder。在您第一次使用当前本地登录身份启动 iFolder 时，iFolder 会提示您设置一个 iFolder 帐户。 iFolder 3.7 和更高版本增加了一种称为自动创建帐户的新功能，可帮助 iFolder 管理员为您创建和配置帐户。如果您的 iFolder 管理员已启用了自动帐户创建功能，则不必为您自己配置帐户。当您首次启动 iFolder 时，将出现提示要求您输入口令。输入您的口令并完成帐户配置。 配置新帐户： 使用下列方法之一，访问 iFolder 帐户创建向导 ： 在您第一次使用当前本地登录身份启动 iFolder 时，iFolder 会提示您设置一个 iFolder 帐户。单击 “向前” 直接转到 “iFolder 帐户创建向导” 。 右击通知区域中的 iFolder 服务 图标，选择“帐户” 以打开“iFolder 首选设置”对话框，进入 “帐户” 选项卡，然后单击 “添加” 以打开 “iFolder 帐户创建向导” 。 遵循屏幕指导指定以下值： 参数 说明 服务器地址 您帐户所在的 iFolder Enterprise Server 的 DNS 名称或 IP 地址。从 iFolder 管理员处获取此信息。 例如： svr21.example.com 或 192.168.1.1 服务器名始终随同其 IP 地址一起显示在 iFolder 用户界面上。例如：iFolder - 192.168.1.1 您不能使用 iFolder 3.7 或更高版本客户程序连接到 iFolder 3.2 服务器。 将此服务器设置为我的默认服务器 如果帐户连接有多个服务器，选中 “将此服务器设置为我的默认服务器” 复选框，将服务器下拉列表中选定的服务器设置为创建或上载 iFolder 时的默认服务器。 用户名 指定此帐户对应的用户身份。iFolder 管理员决定您应使用的格式是网络用户 ID（LDAP 常用名）还是电子邮件地址。 例如，如果您的姓名是 John Smith，用户 ID 是 jsmith，电子邮件地址是 john.smith@example.com ，则管理员将为服务器配置一个设置以确定 “用户名” 字段接受两种格式中的哪一种来进行鉴定。 口令 指定用户名的口令。 通过安全通道 (SSL) 进行鉴定。系统提示您是否验证并接受服务器证书。 记住口令 选中 此计算机上的“记住口令” 复选框，可以在登录到计算机时自动登录到此 iFolder 帐户。 如果更改了网络口令，则在下一次 iFolder 尝试登录到 iFolder 帐户时，自动鉴定将失败。iFolder 将提示您用新口令登录并且允许您指定和保存新口令。 校验您输入的信息。要进行任何更改，单击 “返回” 按钮，重新访问之前的页面。单击 “连接” 以继续并验证与服务器的连接。 如果提示您 “接受此服务器的证书” ，则单击 “细节” 查看证书信息，然后单击 “确定” 接受该证书信息。 创建帐户期间，用户通过 SSL 进行登录。当系统提示您接受服务器证书时，必须验证并接受该证书，才能成功连接。 如果管理员已启用加密策略 ，iFolder 会提示您输入通行口令。 在 “通行口令” 字段中输入通行口令。 在 “重新键入通行口令” 字段中重新输入通行口令。 选中 “记住通行口令” 复选框以在当前会话过程中自动访问加密的 iFolder 数据。如果选择此选项，iFolder 可在下次登录过程中记住您的通行口令。此通行口令交换会自动进行。 从列表中选择所需的恢复代理，然后单击 “确定” 。 指定用于创建默认 iFolder 的位置。 默认情况下，默认 iFolder 存储在 &lt;用户主目录&gt;/ifolder/服务器名/用户名 。 选择您希望创建的默认 iFolder 的类型。如果选择 “加密” ，则系统会提示您提供通行口令。 您只能共享常规 iFolder。无法共享加密的 iFolder。 如果 iFolder 管理员尚未对您的当前帐户启用加密，您只能创建常规 iFolder，而如果启用加密，则默认情况下， “常规” 选项处于选中状态。 选择 “安全同步” 可对所创建的 iFolder 中的文件启用安全同步。 您可以同时对常规 iFolder 和加密 iFolder 启用安全通道。在选中此选项时，iFolder 允许使用安全通道在服务器上的 iFolder 与本地计算机上的 iFolder 间进行同步。 如果您去除服务器上的默认 iFolder，则下次从任何富客户端配置该帐户时，iFolder 将会提示您再次创建一个默认 iFolder。 但如果从本地计算机去除默认的 iFolder，则下次配置帐户时 iFolder 会提示您下载默认的 iFolder。 如果已设置了一个默认 iFolder，那么您可以将其下载到本地计算机。 下载默认 iFolder，单击 “下一步” 继续。 如果系统中已存在与默认 iFolder 同名的文件夹，则您会收到合并两个文件夹或将默认 iFolder 下载至其他位置的提示。 单击 “确定” 合并两个文件夹或单击 “取消” 将默认 iFolder 下载至其他位置 单击 “完成” ，关闭 iFolder 帐户创建向导。 iFolder 同步指定帐户的用户列表，并且标识可用于下载的 iFolder。初次下载可能需要花费一些时间，这取决于帐户的用户列表的大小。 校验您设置的帐户是否出现在帐户列表中。 在通知区域中右击 “iFolder 服务” 图标，然后从菜单中选择 “首选设置” 以打开 “iFolder 首选设置” 对话框并进入 “帐户” 选项卡。 当连接到 iFolder 服务器时，将选中 “联机” 复选框。 关闭“iFolder 首选设置”对话框 使用以下两种方法之一为帐户设置 iFolder： 右击通知区域中的 iFolder 服务 图标，然后选择 “iFolder” 以打开 iFolder 浏览器。继续 。 如果此帐户的 iFolder 可从服务器下载，则将在 &lt; iFolder 服务器名 &gt; 上 iFolder 窗口的“iFolder”下列出来。下载图标 指示 iFolder 可供下载。继续 。 </content>
</topic>

<topic>
  <title>登录 iFolder 帐户</title>
  <url>../login.html</url>
  <content>登录 iFolder 帐户 可以随时在本地访问 iFolder 目录中的文件。您必须登录 iFolder 帐户以同步用户列表、同步 iFolder 数据、上载新的 iFolder、下载共享 iFolder、共享 iFolder 以及管理 iFolder。可以分别登录也可以同时登录多个帐户。 对每个帐户使用以下登录方法之一： 自动登录： 如果您希望在 iFolder 客户端启动的时候自动登录，则启用 iFolder 帐户的 “记住口令” 。当您配置帐户或在以后修改帐户设置时，可以启用 “在此计算机上记住口令” 。 只要更改了口令，自动鉴定就会在您下次试图登录到 iFolder 帐户时失败。在 iFolder 提示您登录时，可以输入新口令，且如果需要的话，再次选中 “记住口令” 复选框。 按需登录： 如果希望仅在需要时登录到 iFolder 帐户，请取消选中 “记住口令” 复选框。 要对现有 iFolder 帐户启用或禁用 “记住口令” 功能： 在通知区域中右击 “iFolder 服务” 图标，然后选择 “帐户” 以打开“iFolder 首选设置”对话框并进入 “帐户” 选项卡。 选择 iFolder 帐户，然后单击 “属性” 以查看其在 “属性” 对话框中的设置。 单击 “身份” 选项卡。 选择（启用）或取消选择（禁用） “记住口令” 。 在 “口令” 字段输入口令。 单击 “关闭” 即可成功完成。 单击 “iFolder 属性” 对话框中的 “关闭” 保存更改并登录到服务器。 要登录 iFolder 帐户，请执行以下操作： 在通知区域中右击 “iFolder 服务” 图标，然后选择 “帐户” 。 选择 iFolder 帐户，然后选择它旁边的 “联机” 复选框。 如果提示需要输入口令，则指定口令，然后单击 “连接” 。 如果已启用该帐户的 “记住口令” ，除非您的口令已过期，否则不会提示您输入口令。 如果登录失败，则出现报告原因的错误讯息，例如口令失败。 连接成功后，关闭 “iFolder 首选设置” 对话框。 </content>
</topic>

<topic>
  <title>查看和修改 iFolder 帐户设置</title>
  <url>../accountdetails.html</url>
  <content>查看和修改 iFolder 帐户设置 可在“帐户设置”和“帐户属性”对话框中查看以下参数： 参数 说明 位置 可由用户修改（是/否） 联机 指示当前您是否连接到某个帐户的 iFolder 服务器。 选中该帐户旁边的 联机 复选框以连接到该帐户的 iFolder 服务器。 取消选中该帐户旁边的 “联机” 复选框以断开与 iFolder 服务器的连接。 “iFolder 首选设置” “帐户” 选项卡 是 服务器名 显示为帐户储存 iFolder 所在的 iFolder 服务器的描述名称。此名称由该服务器提供并由 iFolder 管理员进行控制。 用户不可修改此设置。 “iFolder 首选设置” “帐户” 选项卡 “帐户属性” &gt; “服务器” 选项卡 否 用户名 显示此帐户的用户身份，如网络用户 ID（LDAP 常用名）或电子邮件地址。不可修改此设置。 在“iFolder 帐户助理”中设置帐户时指定用户名。不可为现有帐户修改用户名。 要在同一服务器上使用不同的用户名，必须删除现有帐户，然后为该用户名创建一个不同的帐户。 “iFolder 首选设置” “帐户” 选项卡 “帐户属性” &gt; “身份” 选项卡 否 地址 显示您的帐户所在的 iFolder Enterprise Server 的 DNS 名称或 IP 地址。从 iFolder 管理员处获取此信息。 例如： svr21.example.com 或 192.168.1.1 您可以修改地址，但进行更改时，必须中断与 iFolder 服务器的连接。 “帐户属性” &gt; “服务器” 选项卡 是 口令 允许为用户名指定口令。 “帐户属性” &gt; “身份” 选项卡 是 保存口令 指示 iFolder 启动时 iFolder 是否自动登录。如果帐户的 “自动连接” 参数已启用（默认），则帐户会尝试使用保存的口令进行连接。 选中 保存口令 可以在登录计算机时自动登录到此 iFolder 帐户。 如果更改了网络口令，则在下一次 iFolder 尝试登录 iFolder 帐户时，自动鉴定将失败。iFolder 将提示您用新口令登录并且允许您指定和保存新口令。 “帐户属性” &gt; “身份” 选项卡 是 定额 报告 Enterprise Server 上分配给您的 iFolder 帐户的空间总量。此值可能是为所有用户设置的默认定额，也可能是用户特有的定额。如果未设置定额，则该值为空或为 N/A （不适用）。对于已连接的每个服务器，还可以在 iFolder 主窗口中查看可用空间。 “帐户属性” &gt; “磁盘空间” 选项卡 否 已用空间 报告此帐户上您拥有的所有 iFolder 当前正在使用的空间总量。不包括与您共享但为其他人拥有的 iFolder 所使用的空间。 “帐户属性” &gt; “磁盘空间” 选项卡 否 可用空间 报告此 iFolder 帐户上您当前可用于 iFolder 的空间总量。此值等于定额减去已使用空间。 “帐户属性” &gt; “磁盘空间” 选项卡 否 自动连接 如果选择（启用）了此值，则 iFolder 启动时将自动连接到此帐户。取消选中该设置可禁用连接到帐户。 该设置仅管理客户端启用或禁用帐户的能力。 当您同时使用 iFolder 和 Novell® iFolder® 3.7 或更高版本服务器时，iFolder 系统管理员可禁用您在服务器端的 iFolder 帐户（通常是临时的）。禁用发生时可能出现以下情况： 如果从服务器端禁用帐户时您已登录，则您可以管理 iFolder，并且您的 iFolder 数据继续与服务器保持同步，直到您通过注销或禁用同步结束会话，或者服务器断开您的会话（以先发生的为准）为止。 如果帐户在服务器端被禁用，则您在尝试登录时将收到一个弹出讯息，通知您该帐户已被禁用。请与您的 iFolder 系统管理员联系以获取帮助。 所有选项卡上的 “帐户属性” 是 帐户为默认 当您有多个帐户时，请选中 “帐户为默认” 复选框以在创建和上载 iFolder 时使此帐户成为帐户下拉列表中默认选择的帐户。 如果只有一个帐户，则不能修改此值。 所有选项卡上的 “帐户属性” 是，如果有多个帐户 加密设置 您可以设置和重设置可从 “安全性” 菜单查看的加密设置。有关加密设置的更多信息，请参见 “安全性” 菜单 用户可以重设置通行口令 在通知区域中右击 “iFolder 服务” 图标，然后选择 “帐户设置” 以打开“iFolder 首选设置”并进入 “帐户” 选项卡。 在“帐户”报告中，可以管理每个帐户的以下参数： 联机（选中可进行连接；取消选中可中断连接） 服务器名（仅供查看） 用户名（仅供查看） 选择要管理的 iFolder 帐户，然后单击 “属性” 打开 “帐户 属性”对话框，显示 “服务器” 选项卡。 在 “服务器” 选项卡上，可以管理所选帐户的以下参数： 名称（仅供查看） 地址（如果已连接则仅可查看；如果已中断连接，则可修改） 服务器说明（仅查看；滚动以查看所有信息） 自动连接（选中可启用；取消选中可禁用） 帐户为默认（选中可启用；只有存在多个帐户时才可用） 选择 “身份” 选项卡可管理所选帐户的以下参数： 用户名（仅供查看） 口令（指定口令） 记住口令（选中可启用；取消选中可禁用） 自动连接（选中可启用；取消选中可禁用） 帐户为默认（选中可启用；只有存在多个帐户时才可用） 选择 “磁盘空间” 选项卡可查看所选帐户的以下参数： 定额（仅查看） 已用（仅查看） 可用（仅查看） 自动连接（选中可启用；取消选中可禁用） 帐户为默认（选中可启用；只有存在多个帐户时才可用） 完成后，请关闭 “帐户属性” 对话框，然后关闭 “iFolder 首选设置” 对话框。 </content>
</topic>

<topic>
  <title>为客户程序配置 iFolder 首选设置</title>
  <url>../preferences.html</url>
  <content>为客户程序配置 iFolder 首选设置 在通知区域中右击 “iFolder 服务” 图标，然后选择 “首选设置” 以打开“iFolder 首选设置”对话框并进入 “一般” 选项卡。 指定以下选项的首选设置： 参数 说明 登录到桌面时启动 iFolder（仅在 Windows 客户端中可用） 选中此选项可在您使用本地用户名登录到设置 iFolder 帐户的位置时启动 iFolder。对于已启用“保存我的口令”的帐户，同步过程将按指定的同步间隔在后台进行。 取消选中此选项以手动启动 iFolder。 成功创建 iFolder 时显示确认讯息 选中此复选框可在每次创建 iFolder 时除了接收常规可视提示（如 iFolder 出现在 iFolder 列表中）外，还接收确认讯息。 取消选中此复选框可停止接收确认讯息。 启动时隐藏 iFolder 主窗口 取消选中此复选框以便在启动时显示 iFolder 窗口。 如果希望在启动时隐藏 iFolder 窗口，请选中此复选框。 显示同步日志 如果希望在启动时显示同步日志，请选中此复选框。 如果希望在启动时隐藏同步日志，请取消选中此复选框。 显示违反策略行为的通知 选中此复选框以便在违反策略时，在通知区域中显示弹出讯息。 在共享 iFolder 时通知 选中此复选框以便在接收到新的邀请以共享 iFolder 时，在通知区域中显示弹出讯息。 要查看当前计算机上可用于下载的 iFolder 的列表，请在 iFolder 运行时在 iFolder 浏览器中选择 “显示可用 iFolder” 。 出现冲突时通知 选中此复选框，以便同步文件时出现冲突时，在通知区域中显示弹出讯息。 取消选中此复选框以禁用同步冲突的弹出讯息。 当 iFolder 运行过程中出现冲突时，iFolder 上将显示出 iFolder 错误 图标。 用户加入 iFolder 域时通知 选中此复选框以便在用户接受共享 iFolder 的邀请时，在通知区域中显示弹出讯息。 取消选中此复选框以禁用弹出讯息。 您可选择一个 iFolder 以在它运行时查看其用户的完整列表，然后单击 “共享对象” 以打开“iFolder 属性”对话框来进入 “共享” 选项卡。 同步 自动同步 iFolder： 选中此复选框，可为此计算机上您在当前本地登录的、或您的登录身份下的所有 iFolder 启用同步。取消选中此复选框以禁用同步。 同步 iFolder 间隔： 指定用于同步此计算机上当前本地登录或登录身份下的 iFolder 的最小间隔。指定值和单位。如果启用了此选项，则默认值为 5 分钟。最小时间间隔可设置为 5 秒。 如果将此 iFolder 客户程序与 Novell iFolder 3.7 或更高版本的服务器一起使用，则有效的最小同步间隔始终是以下设置的最大值： 系统策略默认为零 ( 0 )，除非已设置用户策略。如果设置了用户策略，无论用户策略的值是大于还是小于系统策略的值，此用户策略都将覆盖系统策略。 本地计算机策略或客户机上的设置与服务器同步。 iFolder（集合）策略。 单击 “关闭” 来关闭“iFolder 首选设置”对话框。 </content>
</topic>

<topic>
  <title>为 iFolder 通讯配置本地防火墙设置</title>
  <url>../firewall.html</url>
  <content>为 iFolder 通讯配置本地防火墙设置 如果您使用的是本地防火墙，则必须设置您的防火墙以允许 iFolder 选择本地动态端口，或为 iFolder 客户程序配置本地静态端口以与 Mono® XSP 服务器进行本地（同一台计算机）通讯。iFolder 使用 Mono XSP 万维网服务通过 HTTP 与您拥有 iFolder 帐户的 Novell iFolder Enterprise Server 进行通讯。iFolder 管理员配置 iFolder 服务以确定是否在您的环境中使用 HTTP。 您的防火墙未阻止 Mono XSP 与 Novell iFolder Enterprise Server 之间的通讯，这是因为 Mono XSP 使用了标准的 HTTP 端口进行通讯。但是，如果您阻止客户端与 Mono XSP 之间的通讯，则客户端将无法与服务器进行通讯。您无法登录到您的 iFolder 帐户以及同步 iFolder 数据。 最初，iFolder 配置并未指定用于客户程序与 Mono XSP 通讯的特定端口。iFolder 首次运行时，将打开一个可用的本地端口以监听来自 Mono XSP 的请求，然后通过 Mono XSP 将数据发送到服务器上。iFolder 将端口号写入配置文件，除非此端口不可用，否则以后每当 iFolder 启动时都会使用此端口。如果有其他应用程序正在使用此端口，iFolder 会选择其他可用端口，并在配置文件中重新配置端口，之后使用新的端口。例如，如果 iFolder 关闭后由另一个应用程序使用该端口，则 iFolder 必须选择并配置重启动 iFolder 时要用的其他端口。 使用本地动态端口 如果在计算机上使用本地防火墙，则只要 iFolder 联系服务器同步其用户列表和 iFolder 数据时，该防火墙都应检测到 iFolder 与 Mono XSP 服务器之间的本地通讯。选择 “允许” 以允许此会话的 iFolder 通讯。如果您始终允许通讯，则防火墙应该不会再次提醒您，而且每次 iFolder 启动时，您都可以避免收到弹出式警报。 如果您阻止 iFolder 与 Mono XSP 的通讯，则您的防火墙将阻止您连接到 iFolder 服务器，而您也无法同步文件。iFolder 不会检测到通讯受防火墙阻止；它仅报告无法连接到您在 iFolder 服务器上的帐户。 使用本地静态端口 可以选择将万维网服务端口范围参数添加到 Simias.config 文件的“服务管理器”部分，以允许 Mono XSP 服务器使用静态端口或一组端口进行此本地通讯。此端口或这组端口随即可在防火墙中打开，以实现 Mono XSP 的通讯。 您可以在以下位置找到 Simias.config ： 操作系统 Simias.config 文件的位置 Linux /home/ username /.local/share/simias/Simias.config Windows C:\Documents and Settings\ username \Local Settings\Application Data\simias\Simias.config 配置系统以使用特定端口或一组端口： 配置防火墙，以允许在想要用于 iFolder 通讯的端口或一组端口上进行通讯。 有关如何在防火墙中打开端口的信息，请参见防火墙的文档。 通过右击 iFolder 图标，然后选择 “退出” ，可停止 iFolder 客户程序。 通过将“万维网服务端口范围”参数添加到 “服务管理器” 部分，可修改 Simias.config 文件。 &lt;configuration&gt; &lt;section name="ServiceManager"&gt; &lt;setting name="WebServicePortRange" value=" monoxsp_port " /&gt; &lt;/section&gt; &lt;/configuration&gt; 用一个或一组端口号替换 monoxsp_port ： 指定一个四位数字端口号的值（如 1234）以使用单个静态端口。例如： &lt;setting name="WebServicePortRange" value=" 1234 " /&gt; 指定一组端口（如“1234-1236”）可使用指定范围端口中的任意可用端口。例如： &lt;setting name="WebServicePortRange" value=" 1234-1236 " /&gt; 启动 iFolder 客户程序。 有关更多信息，请参见 。 </content>
</topic>

<topic>
  <title>为 iFolder 通讯配置本地病毒扫描程序设置</title>
  <url>../virusscan.html</url>
  <content>为 iFolder 通讯配置本地病毒扫描程序设置 如果您在计算机上使用病毒扫描软件，请从病毒扫描中排除 ..\simias\WorkArea\ 目录。例如，Windows 上 ..\simias\WorkArea\ 目录的位置是 c:\documents and settings\ username \local settings\application data\simias\WorkArea\.simias.wf. guid 。 此 ..\simias\WorkArea\ 目录是从服务器中下载 iFolder 阶段文件的位置。如果 iFolder 文件附带有病毒，并且您的病毒扫描软件扫描出该病毒文件位于 ..\simias\WorkArea 目录中时，病毒扫描程序就会弹出一条讯息，说明已找到病毒，并将文件移到隔离区，然后 iFolder 会再次尝试同步该文件。 不扫描“工作区”允许完成同步。受到感染的文件被成功下载并移到本地 iFolder 中。然后病毒扫描程序检测出 iFolder 中受到感染的文件，并将它从该文件夹移到隔离区，以保护计算机免遭感染。iFolder 将检测该文件的删除情况，在下一次同步开始时，iFolder 将该文件从服务器和成员计算机上去除。 但是，如果从中下载文件的 iFolder 为只读，则不会对服务器和其他成员计算机实施本地删除。必须在允许同步更改的其他地方检测病毒。用户的病毒扫描程序可能会警告用户有病毒，因此该用户应该警告其他 iFolder 成员有关病毒的情况。 </content>
</topic>

<topic>
  <title>删除 iFolder 帐户</title>
  <url>../delacct.html</url>
  <content>删除 iFolder 帐户 您可以指定是仅从当前计算机中去除帐户，还是同时从服务器中去除您的 iFolder。 如果仅从计算机中去除 iFolder 帐户，则： 此帐户的本地 iFolder 将恢复为常规文件夹。如果不需要数据的本地拷贝，则使用文件管理器查找并删除它们。 您可以继续从具有 iFolder 客户程序的其他计算机中访问 iFolder。 将 iFolder 客户程序与 Novell iFolder 3.7 或更高版本 Enterprise Server 一起使用时，您还可从支持 Novell iFolder 3.7 或更高版本万维网访问功能的任何地方访问文件。 如果从服务器中去除 iFolder 帐户，则： 对您拥有的所有 iFolder 取消共享。 成员计算机上的 iFolder 本地拷贝将恢复为常规文件夹。如果不需要数据的本地拷贝，则使用文件管理器查找并删除它们。 将从服务器中去除 iFolder 及其内容。 从其他用户共享给您的 iFolder 中去除您的成员资格。 将从本地计算机中去除此帐户。 如果您决定在此计算机或另一台计算机上再次使用此帐户，则必须像对待新帐户那样重新设置该帐户及其 iFolder。 删除 iFolder 帐户： 在通知区域中右击 “iFolder 服务” 图标，然后选择 “帐户设置” 以打开“iFolder 首选设置”对话框并进入 “帐户” 选项卡。 选择要删除的 iFolder 帐户，然后单击 “去除” 。 出现讯息提示您确定去除操作的作用范围。 执行以下操作之一： 只从当前计算机去除 iFolder 帐户： 确保未选中 “从服务器去除我的 iFolder 和文件” ，然后单击“ 是” 。 从服务器去除 iFolder 帐户与 iFolder 和文件： 选择 “从服务器去除我的 iFolder 和文件 ，然后单击 “是” 。 取消删除： 单击 “否” 以取消删除操作。您的帐户及其 iFolder 保持不变。 </content>
</topic>

<topic>
  <title>注销 iFolder 帐户</title>
  <url>../logout.html</url>
  <content>注销 iFolder 帐户 如果要脱机工作，则注销 iFolder 帐户。 Macintosh 在对接台中单击 iFolder 服务 图标，然后选择 “帐户” 以打开“iFolder 首选设置”对话框。 从工具栏单击 “帐户” 图标以查看当前 iFolder 域中的帐户列表。 找到要管理的帐户，然后单击 “注销” 以从 iFolder 服务器断开。 Linux 在通知区域中右击 “iFolder 服务” 图标，然后选择 “帐户” 以打开“iFolder 首选设置”对话框并进入 “帐户” 选项卡。 找到您希望管理的帐户，然后取消选择它旁边的 “联机” 复选框以断开与 iFolder 服务器的连接。 单击 “关闭” 可关闭“iFolder 首选设置”对话框。 Windows 在通知区域中右击 “iFolder 服务” 图标，然后选择 “帐户” 以打开“iFolder 首选设置”对话框并进入 “帐户” 选项卡。 找到您希望管理的帐户，然后取消选择它旁边的 “联机” 复选框。 单击 “应用” 断开与 iFolder 服务器的连接，然后单击 “确定” 关闭“iFolder 首选设置”对话框。 </content>
</topic>

<topic>
  <title>退出 iFolder 客户程序</title>
  <url>../stopclient.html</url>
  <content>退出 iFolder 客户程序 要退出 iFolder 客户程序，请按以下给定的任一选项操作。 在通知区域中右击 “iFolder 服务” 图标，然后选择 “退出” 。 单击 “iFolder”&gt;“退出” 当您选择 “退出” 时，iFolder 将显示出一条确认讯息。单击 “是” 确认操作。 仅在您连接到 iFolder 服务器后文件才会与 iFolder 服务器帐户同步。您可以通过注销帐户来停止同步。脱机方式下，iFolder 继续在后台运行。有关信息，请参见 。 您可具有多个在不同主机服务器（域）上创建的帐户。 </content>
</topic>

<topic>
  <title>下一步</title>
  <url>../b9lvmk9.html</url>
  <content>下一步 有关使用 iFolder 客户程序的信息，请参见以下内容： </content>
</topic>

<topic>
  <title>管理 iFolder</title>
  <url>../myifolders.html</url>
  <content>管理 iFolder iFolder™ 是用于有选择地与用户指定的成员共享和同步文件的本地目录。那些具有特权的成员可修改和读取 iFolder 文件。 本节讨论 iFolder 的以下任务： </content>
</topic>

<topic>
  <title>iFolder 的位置和用途的准则</title>
  <url>../locguide.html</url>
  <content>iFolder 的位置和用途的准则 通常情况下，当您创建 iFolder 或者设置共享的 iFolder 时，可以将 iFolder 放置在您的本地硬盘驱动器的任何地方。但是，有一些实际和特定的限制。在您的计算机上放置和使用 iFolder 时请考虑以下规范： 在您放置 iFolder 的目录中，iFolder 的名称必须是一个唯一的文件夹名。 iFolder 的名称不能包含以下这些无效的字符： \/:*?"&lt;&gt;|; 有关其他命名规则，请参阅 。 iFolder 必须位于本地磁盘驱动器上；该位置不能在网络驱动器或非物理驱动器上。 iFolder 不能位于硬盘驱动器的根位置。 可以仅从文件夹中创建 iFolder，而且您对该文件夹中的文件拥有读和写的文件系统访问权限。当在计算机上设置共享的 iFolder 时，您必须对要放置 iFolder 的文件夹拥有文件系统访问权限。 iFolder 不能包含应用程序文件夹（例如，“Program Files”文件夹），也不能驻留在其中。 iFolder 不能包含 iFolder 元数据文件夹，也不能驻留在其中。元数据文件夹的默认位置如下： Linux： 在您的主文件夹（ &lt;用户主目录&gt;\.local\share simias ）子目录中 Windows： 在 C:\Documents and Settings\\ WindowsLogonUsername \Local Settings\Application Data\simias 目录中 Macintosh： 在 $HOME/.local/share/simias 中 iFolder 不能包含或属于其他 iFolder，包括 Novell iFolder 2. x iFolder。 iFolder 不支持作为 iFolder 的网络文件夹。例如，iFolder 无法成为用户映射到用户工作站的基于网络的目录/主目录。iFolder 也不支持用户通过 WebDAV 从桌面访问 iFolder 服务器的用户数据卷上的 iFolder 集合。 虽然您可以一次同时登录到多个 iFolder 帐户中，但 iFolder 仅可以与一个 iFolder 帐户相关联。无法将一个 iFolder 和多个帐户进行同步。创建一个 iFolder 时，只能与同一个 iFolder 服务器或域中配置的其他用户和 LDAP 组共享该 iFolder。 与一个 LDAP 组共享某一 iFolder 时，该 LDAP 组的所有成员都可以使用该 iFolder。 当多名用户共享一台计算机时，如果文件系统支持隐私功能并且您将系统配置为使用这些隐私功能，则您的 iFolder 本地副本对于磁盘上的储存空间是私用的。 在 Window 上，NTFS 包括内置安全性功能，例如文件和文件夹许可权限，以及加密文件系统 (EFS)，这些功能是用于在 NTFS 卷上储存加密文件的技术。FAT32 文件系统上不支持这些安全性功能。确保用户的本地登录身份（当然是非管理员身份）不具有管理员的权限或与其等效的权限。管理员用户有访问计算机上所有文件和目录的权限。对于每个用户都很注重隐私和安全性的共享计算机，用户可以使用 EFS 或第三方文件系统加密对其 iFolder 数据的本地副本进行加密。 Linux 和 Macintosh 文件系统专用于多用户环境。使用文件权限可以控制用户、用户组及其他人员的访问权限。通常，使用用户的完全权限设置用户的个人文件，组和其他设置没有访问权限。 如果您将 iFolder 储存在本地 Linux 的 FAT32 卷上，则需要特殊处理，因为 FAT32 文件系统与 POSIX* 不兼容。有关信息，请参见 。 如果同一台计算机的多个用户共享 iFolder，则该计算机上将存在 iFolder 的多个副本，以便每个用户可以从服务器上下载一个副本。不同的本地登录身份不能共享一个共享 iFolder 的位置。 </content>
</topic>

<topic>
  <title>不进行同步的文件类型和大小的准则</title>
  <url>../typeguide.html</url>
  <content>不进行同步的文件类型和大小的准则 使用 iFolder 客户程序时，您的 iFolder 管理员可能会指定系统级、用户级、LDAP 组级或 iFolder 级的文件类型限制和最大文件大小限制。您的帐户可能也会限制在可用于自己拥有的 iFolder 中的数据的空间数量之内。您加入其他 iFolder 时，在服务器上占用的空间也视为被此 iFolder 的拥有者所耗用。 某些文件类型不适合进行同步，如操作系统文件、文件管理器创建的隐藏文件，作为已链接文件集实施的数据库等。您可以仅包括用于业务的主要的文件类型，或者排除可能与业务无关的文件，如 .mp3 文件。 操作系统文件 您不应将系统目录转换为 iFolder。大多数系统文件很少更改，最好保留基本系统和主要软件的映象文件，而不是尝试将那些文件与服务器上的文件同步。 隐藏文件 如果您的文件系统使用隐藏文件来跟踪显示首选设置，则您的管理员可能限制这些文件类型以排除它们被同步到您的系统上。通常，隐藏文件仅与创建它们的特定计算机有关，每次访问文件或目录时它们都会发生改变。您无需保留这些文件，同步它们会导致重复的文件冲突错误。 例如，iFolder 自动排除两个称为 thumbs.db 和 .DS_Store 的隐藏文件管理器文件。 数据库文件 iFolder 同步各个文件或各个文件的已更改部分；它不会将文件作为文件集来同步。如果您有作为已链接文件集实施的数据库文件，不要尝试在 iFolder 中同步它们。 不要尝试通过使 GroupWise 存档、超速缓存或远程目录进入 iFolder 来同步 GroupWise® 数据。如果这样做，在对文件进行几次同步后 GroupWise 数据文件将会损坏。GroupWise 需要将存档中的文件作为文件集保存。 </content>
</topic>

<topic>
  <title>iFolder 及其文件夹和文件的命名约定</title>
  <url>../nameconv.html</url>
  <content>iFolder 及其文件夹和文件的命名约定 iFolder 客户程序强用考虑 Linux 和 Windows 文件系统的共同限制的命名约定。iFolder、文件夹或文件在可以同步之前必须拥有符合命名约定的有效名称。 为您的 iFolder 及其中的文件夹和文件使用以下命名约定： iFolder 支持使用 UTF-8 编码设置的 Unicode * 字符。 不要在 iFolder 的名称，或其中的文件夹和文件的名称中使用以下无效字符： \/:*?"&lt;&gt;|; 如果在文件或文件夹名称中使用无效字符，iFolder 会创建名称冲突。在文件或文件夹可以同步前必须解决此冲突。 单个路径部件的最大长度取决于客户机文件系统。对于文件名来说，最大长度包括点 (.) 和文件扩展名。 当您尝试下载或同步其名称长度超出文件系统支持的最大长度的 iFolder 时，iFolder 将显示出一条错误讯息。 iFolder、文件夹和文件的名称不区分大小写；但是，应保留大小写。如果文件名仅大小写不同，则 iFolder 将创建名称冲突。在文件或文件夹可以同步前必须解决此冲突。 如果在 Linux 的 FAT32 文件系统中创建 iFolder，避免全部用大写字符命名文件。在 Linux 上的 VFAT 或 FAT32 文件处理将自动更改全部是大写字符的文件名，并将所有的大写字符全部更改为小写字符，使其符合 MS-DOS 8.3 文件格式。如果该 iFolder 设置为只读访问权限，这会引起这些文件的同步问题。 </content>
</topic>

<topic>
  <title>了解 iFolder 图标</title>
  <url>../ificons.html</url>
  <content>了解 iFolder 图标 下表说明了 iFolder 图标及相关任务。 iFolder 图标 说明 在桌面应用程序菜单中显示 iFolder 3 客户程序的 iFolder 服务 图标。 运行 iFolder 时， iFolder 服务 图标还出现在桌面任务栏的通知区域。右击该图标可获取一个可能任务的菜单，其中包括 iFolder 浏览器、帐户设置、同步日志、首选设置以及帮助。 创建 iFolder 图标显示在 iFolder 浏览器中。 您可以创建新的 iFolder 或将现有文件夹转换为 iFolder。如果您拥有多个帐户，则必须指定要使用的帐户；iFolder 只可以属于一个帐户。有关信息，请参见 。 当指定服务器上有您可用的 iFolder，而您尚未下载至本地计算机时会显示 iFolder 下载 图标。 可以将不同帐户下的任何 iFolder 组合下载到本地计算机上。有关信息，请参见 。 加密的 iFolder 图标（锁定的 iFolder）指出该 iFolder 是加密的，此图标显示在 iFolder 浏览器中。 登录时提供的通行口令可让您检索加密的 iFolder 中的文件。有关加密的更多信息，请参见 。 iFolder 徽标（绿色的“i”），在文件管理器、桌面或 iFolder 浏览器中查看 iFolder 时，只要运行 iFolder 服务应用程序，都会在 iFolder 上显示该徽标。 iFolder 不运行时，如果在文件浏览器或桌面上查看 iFolder，它显示为常规文件夹 。当 iFolder 不运行时，iFolder 浏览器不可用。 在仅包含 iFolder 的单个目录中组织 iFolder 的本地集合是个很好的做法。这样可以在 iFolder 未运行且未提供将它们标记为 iFolder 的图标时轻松记住哪些文件夹为 iFolder。 iFolder 警告 图标指出服务器不可用。iFolder 正在运行，但您未连接到 iFolder 服务器上。可能的原因有： 您没有登录到 iFolder 帐户。有关信息，请参见 。 客户端禁用该帐户；即已禁用 “自动连接” 参数。有关信息，请参见 中的 “自动连接” 。 服务器已关闭或已禁用服务器端的帐户。与 iFolder 管理员联系以获取帮助。 防火墙阻止 iFolder 通讯。有关解决此问题的信息，请参见 。 网络连接已关闭。请检查本地网络设置。 iFolder 冲突 图标指示在本地拷贝和服务器拷贝之间存在文件冲突。通过指示要保留文件的哪个版本即可解决该冲突。有关文件冲突的更多信息，请参见 。 iFolder 等待同步 图标指出 iFolder 包含要与服务器同步的文件且同步过程尚未开始。 iFolder 每次同步一个 iFolder，并对同步任务进行排队。要确保本地 iFolder 中的文件已与服务器中的文件同步，请等待直到同步开始并成功完成再关闭 iFolder，如图标中的变化所示。 iFolder 正在同步 图标指出 iFolder 中的文件当前正在与服务器同步。 iFolder 错误 图标指示因文件大小限制或 iFolder 数量限制而产生策略冲突，致使 iFolder 中的一个或多个文件尚未进行同步。 在“共享”对话框中， iFolder 拥有者用户 图标指出该用户拥有该共享 iFolder。 在“共享”对话框中， iFolder 当前用户 图标指示该用户当前正在管理该 iFolder。如果当前用户是拥有者，则将显示 拥有者用户 图标。 </content>
</topic>

<topic>
  <title>iFolder 浏览器</title>
  <url>../bkjj1f9.html</url>
  <content>iFolder 浏览器 您可以使用 iFolder 浏览器来管理 iFolder。下面给出的表格总结了 iFolder 浏览器的元素： 元素名称 说明 创建 iFolder 用于将本地计算机的文件夹转换为 iFolder，并将其上载至所连接的 iFolder 服务器。 有关详细信息，请参见 立即同步 用于立即启动本地计算机和服务器间的 iFolder 同步。 共享 用于和其他用户共享您的 iFolder。 有关详细信息，请参见 恢复为常规文件夹 用于将 iFolder 恢复为常规文件夹。还可从服务器删除 iFolder。有关详细信息，请参见 服务器 显示所连接 iFolder 服务器的 IP 地址。 名称 显示选定 iFolder 的名称。 拥有者 显示选定 iFolder 的拥有者名字。 权限 显示 iFolder 拥有者所拥有的权限。 等待同步的文件/文件夹 指出等待同步的文件或文件夹的数量。 上次成功同步时间 指出上次成功同步的时间和日期 下载 iFolder 用于从 iFolder 服务器将 iFolder 下载到本地计算机。 有关详细信息，请参见 iFolder 类型 指出选定的 iFolder 是经过加密的还是常规的。 iFolder 大小 显示选定 iFolder 的大小。 合并 合并功能可帮助您合并 iFolder 数据并将 iFolder 服务器和客户端之间的数据传输量降至最低。您可将服务器上 iFolder 中的内容与本地计算机上现有文件夹的内容合并在一起。有关详细信息，请参见 从服务器中删除 用于从服务器中删除选定的 iFolder。 域列表 显示帐户配置的服务器列表。 连接/断开连接 用于连接或断开与 iFolder 服务器的连接。如果已与 iFolder 服务器连接，则会显示 “断开连接” 按钮，如果未连接，则显示 “连接” 按钮。 解析 用于解决文件冲突。要解决文件版本的冲突，您必须在 “冲突解决方案” 对话框中选择正确的版本。有关详细信息，请参见 用户 显示登录到选定 iFolder 服务器用户的名称。 iFolder 数量 显示选定 iFolder 服务器上与本地计算机上的 iFolder 总数。 磁盘定额 显示“已用空间”和“可用空间”字段的值。 已用空间 显示所选 iFolder 服务器上的所有文件和目录当前所占用的服务器磁盘空间的总量。 可用空间 显示选定的 iFolder 服务器上，当前已由其上所有文件和目录可用的服务器磁盘空间。 自动同步 显示两个连续自动同步周期间的时间间隔 </content>
</topic>

<topic>
  <title>创建和上载 iFolder</title>
  <url>../createifolder.html</url>