<?xml version="1.0" encoding="UTF-8" ?>
<!-- saved from url=(0014)about:internet -->

<!DOCTYPE site [
 <!ELEMENT site (topic+)>
  <!ELEMENT topic (title,url,content)>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT url (#PCDATA)>
   <!ELEMENT content (#PCDATA)>
]>

<site>
<topic>
  <title>Novell iFolder 3.7 — Pomoc wieloplatformowa</title>
  <url>../bookinfo.html</url>
  <content>Novell iFolder 3.7 — Pomoc wieloplatformowa 3.7 Pomoc programu iFolder Program Novell® iFolder® umożliwia współużytkowanie plików przez klientów systemów Linux*, Windows* i Macintosh*. Program iFolder zapewnia nieprzerwany dostęp do lokalnych plików z każdego miejsca — w trybie online, offline i o każdej porze — przy użyciu różnych komputerów. Pozwala na współużytkowanie plików w wielu iFolderach przeznaczonych dla różnych użytkowników. Użytkownik określa osoby, które mogą używać iFolderu oraz definiuje prawa dostępu do plików. Sam może także korzystać z iFolderów udostępnionych przez innych użytkowników. W tym systemie pomocy opisano sposób korzystania z klienta programu iFolder i zarządzania nim. Odbiorcy Ten podręcznik jest przeznaczony dla użytkowników klienta programu iFolder. Dodatkowa dokumentacja W przypadku korzystania z klienta programu iFolder 3.7 z serwerem Novell iFolder 3.7 lub serwerem Web access patrz Podręcznik użytkownika programu iFolder 3.7 dla serwera Novell iFolder 3.7 w witrynie sieci Web Dokumentacja Novell iFolder . Konwencje zastosowane w dokumentacji W dokumentacji firmy Novell znak większości (&gt;) jest używany do oddzielania czynności wchodzących w skład jednego punktu oraz elementów ścieżki odniesień. Symbol znaku towarowego (®, ™ itp.) oznacza znak towarowy firmy Novell. Gwiazdka (*) oznacza znak towarowy innej firmy. W nazwach ścieżek, w których w niektórych systemach operacyjnych jest stosowany ukośnik, a w innych ukośnik odwrócony, zawsze stosowany jest ukośnik odwrócony. W przypadku platform, gdzie wymagany jest zwykły ukośnik, na przykład w przypadku systemu Linux lub UNIX, należy stosować zwykły ukośnik. </content>
</topic>

<topic>
  <title>Przegląd programu iFolder</title>
  <url>../overview.html</url>
  <content>Przegląd programu iFolder Program Novell® iFolder® umożliwia współużytkowanie plików przez klientów systemów Linux, Windows i Macintosh. Pozwala na współużytkowanie plików w wielu iFolderach przeznaczonych dla różnych użytkowników lub grup LDAP. Użytkownik określa osoby, które mogą używać iFolderu oraz definiuje poziomy dostępu każdego członka. Sam może także korzystać z iFolderów udostępnionych przez innych użytkowników. Program iFolder 3.7 zapewnia prosty, niesprawiający problemów interfejs użytkownika dla migracji po stronie klienta z programu iFolder 2. x do programu iFolder 3.6 i nowszego oraz dla uaktualnienia po stronie klienta z programu iFolder 3. x do programu iFolder 3.6 i nowszego. W tej części opisano zalety i funkcje programu iFolder: </content>
</topic>

<topic>
  <title>Zalety programu iFolder</title>
  <url>../benefits.html</url>
  <content>Zalety programu iFolder Program iFolder ma następujące zalety: Integracja z macierzystym środowiskiem graficznym ułatwiająca tworzenie wielu iFolderów i zarządzanie nimi. Wysoka skalowalność i elastyczność oraz możliwość utworzenia praktycznie nieograniczonej liczby iFolderów dla każdego użytkownika i przypisania nieograniczonej liczby członków do każdego iFolderu. Przy włączonej funkcji szyfrowania chroni dane przesyłane oraz przechowywane na serwerze iFolder. Dzięki rozszerzonej konsoli dostępu do sieci Web można uzyskać dostęp do plików na serwerze iFolder z dowolnej stacji roboczej bez zainstalowanego klienta programu iFolder oraz używać przeglądarki internetowej do wykonywania wszystkich operacji klienta programu iFolder. Łatwe i wybiórcze współużytkowanie plików osobistych i służbowych. Pozwala przeprowadzić migrację oraz uaktualnienie danych iFolderu do najnowszej wersji. Obsługuje grupy LDAP. Umożliwia współużytkowanie iFolderów z grupami LDAP. Członkowie grupy LDAP mogą tworzyć iFoldery, określać ich własność oraz współużytkować je z pozostałymi użytkownikami indywidualnymi lub innymi grupami LDAP. Pozwala nadzorować poziomy dostępu do iFolderów użytkownika oraz folderów, w których użytkownik ma uprawnienia niezbędne do kontrolowania praw dostępu. Dyskretne synchronizowanie plików użytkownika z plikami we współużytkowanych iFolderach na wielu stacjach roboczych. Śledzenie i zapisywanie w dzienniku zmian wykonanych podczas pracy bez połączenia oraz synchronizowanie tych zmian po uzyskaniu połączenia z serwerem. Bezpieczne uwierzytelnienie użytkowników, którzy uzyskują dostęp do iFolderu w celu synchronizacji danych. Alternatywa dla wymiany plików za pomocą poczty elektronicznej — wyeliminowanie ograniczeń związanych z rozmiarem załączników wiadomości e-mail oraz mniejsze wymagania dotyczące magazynowania poczty. </content>
</topic>

<topic>
  <title>Klient programu iFolder</title>
  <url>../bawqltp.html</url>
  <content>Klient programu iFolder Klient iFolder integruje się z systemem operacyjnym, oferując usługi iFolder w macierzystym środowisku roboczym. Klient programu iFolder umożliwia zarządzanie własnymi iFolderami oraz określenie współużytkowanych iFolderów do skonfigurowania na każdym komputerze. Program iFolder współpracuje z następującymi systemami operacyjnymi: SUSE® Linux Enterprise Desktop 10 SP1 i SP2 SUSE® Linux Enterprise Desktop 11 Windows Vista SP1 Windows XP SP2 OpenSUSE 11.1 Apple Macintosh® wersja 10.4 i nowsze </content>
</topic>

<topic>
  <title>Konto iFolder</title>
  <url>../bawqmpe.html</url>
  <content>Konto iFolder Konto iFolder zostaje utworzone w momencie, gdy administrator usług iFolder dopuszcza użytkownika do serwera iFolder jako użytkownika iFolderu. Administrator nadaje użytkownikowi nazwę i hasło. W przypadku firmy może to być nazwa użytkownika lub adres e-mail oraz skojarzone z nim hasło. Przed utworzeniem iFolderu należy skonfigurować przynajmniej jedno konto iFolder. Więcej informacji można znaleźć w dokumencie . Sesja programu iFolder rozpoczyna się z chwilą zalogowaniu użytkownika na koncie usług iFolder, a kończy wraz z wylogowaniem albo z zamknięciem klienta iFolder. Synchronizowanie plików w iFolderach użytkownika z innymi aktywnymi iFolderami odbywa się tylko wtedy, gdy sesja jest aktywna i użytkownik jest połączony z siecią. Dostęp do danych w lokalnych iFolderach można uzyskać w dowolnym czasie, bez względu na to, czy użytkownik jest zalogowany. Więcej informacji można znaleźć w dokumencie . </content>
</topic>

<topic>
  <title>Kwestie dotyczące wykorzystania różnych platform</title>
  <url>../ovwxplat.html</url>
  <content>Kwestie dotyczące wykorzystania różnych platform Interfejsy użytkownika klienta programu iFolder dla systemów Linux, Windows i Macintosh są zgodne z konwencjami interfejsu obowiązującymi na danej platformie. Zwyczajowe zadania są realizowane tak samo na wszystkich platformach, ale nieznacznie różnić mogą się m.in. przyciski, obszary wyświetlania, etykiety funkcji, położenie obszaru powiadomień lub preferencje uruchamiania klienta programu iFolder. W tym podręczniku zawarto tylko instrukcje dla jednej z trzech platform — z wyjątkiem procedur, które znacznie się różnią. Poniższa tabela zawiera listę wybranych typowych różnic i podobieństw między interfejsami klienta: Zadanie Linux Windows Macintosh Menu iFolder Zakończ Zakończenie pracy Zakończ Okno dialogowe Preferencje programu iFolder &gt; Konta Przycisk Dodaj Przycisk Dodaj Przycisk Plus ( + ) Okno dialogowe Preferencje programu iFolder Konta Przycisk Usuń Przycisk Usuń Przycisk Minus ( - ) Wiele lokalizacji Przycisk Zamknij Działania są zatwierdzane po wykonaniu operacji przez użytkownika Przyciski OK , Anuluj i Zastosuj Działania są zatwierdzane dopiero po kliknięciu przycisku Zastosuj lub OK Przyciski OK i Anuluj Działania są zatwierdzane po wykonaniu operacji przez użytkownika Okno dialogowe Preferencje programu iFolder Dodaj program iFolder do folderu Autostart na pulpicie Zaznacz (włącz) opcję Uruchom iFolder podczas logowania do pulpitu Ta opcja jest niedostępna Konfigurowanie konta programu iFolder Zapamiętaj moje hasło Zapamiętaj hasło na tym komputerze Zapamiętaj hasło Obszar powiadomień Obszar powiadomień Obszar stanu i powiadomień Obszar powiadomień Kliknij prawym przyciskiem myszy obszar powiadomień Ustawienia konta Konta Ta opcja jest niedostępna Menu iFoldery iFolder Właściwości Właściwości Pobierz informacje Kreatory iFolderów Przycisk Dalej i przycisk Wstecz Przycisk Dalej i przycisk Wstecz Brak przycisków do przechodzenia do przodu i wstecz. Nazwę użytkownika, hasło i serwer można skonfigurować w pojedynczym oknie. Konfigurowanie konta programu iFolder Asystent konta iFolder Kreator tworzenia konta iFolder Preferencje &gt; Konto Kreator konfigurowania serwera iFolder Serwer iFolder Wybierz serwer iFolder Niedostępne Kreator konfigurowania tożsamości iFolder Tożsamość Informacje o koncie iFolder Niedostępne </content>
</topic>

<topic>
  <title>Podstawowe funkcje programu iFolder</title>
  <url>../keyfeatures.html</url>
  <content>Podstawowe funkcje programu iFolder Przed przystąpieniem do używania programu iFolder należy poznać jego podstawowe funkcje: Współużytkowanie iFolderów Zazwyczaj praca w wielu lokalizacjach lub współpraca z wieloma osobami wymaga starannego zarządzania wersjami plików. W przypadku iFolderu najbardziej aktualne wersje plików mogą podążać za użytkownikiem do dowolnego komputera, na którym został zainstalowany klient programu iFolder i utworzono dla nich iFolder. Program iFolder umożliwia również współużytkowanie wielu iFolderów i ich oddzielnych zawartości z innymi uprawnionymi użytkownikami i grupami LDAP. Więcej informacji dotyczących współużytkowanych iFolderów można znaleźć w temacie . Klient programu iFolder obsługuje współużytkowanie plików poprzez ich synchronizację na wielu komputerach za pośrednictwem komputera centralnego. Dostępne funkcje: Współużytkowanie plików na różnych komputerach Współużytkowanie plików z innymi użytkownikami Posiadanie wielu iFolderów Korzystanie z wielu iFolderów udostępnionych przez innych użytkowników Korzystanie z plików jako właściciel lub członek iFolderów na wielu kontach Operacje na iFolderach są przeprowadzane bezpośrednio w menedżerze plików lub przeglądarce iFolderów, która jest zintegrowana z klientem. W iFolderze można skonfigurować dowolną strukturę katalogów zgodną z osobistymi lub firmowymi zasadami pracy. Struktura katalogów jest stała dla wszystkich iFolderów będących członkami. Współużytkowane iFoldery iFolder jest katalogiem lokalnym, w którym pliki są selektywnie współużytkowane i synchronizowane za pośrednictwem serwera centralnego z określoną grupą użytkowników. Pliki w iFolderze są dostępne dla wszystkich jego członków i mogą być modyfikowane przez użytkowników, którzy mają odpowiednie uprawnienia. Dostęp do iFolderów jest możliwy z wielu stacji roboczych, a można je współużytkować z pojedynczymi użytkownikami lub grupami LDAP. Użytkownik decyduje o tym, kto może być członkiem iFolderu oraz jaki poziom dostępu przysługuje takiej osobie. Użytkownik może także korzystać z udostępnionych iFolderów, które należą do innych osób pracujących we wspólnym środowisku. W przypadku współużytkowania iFolderu użytkownicy, którzy są jego członkami i mają prawa zapisu, mogą modyfikować strukturę katalogów, a te zmiany odnoszą się do wszystkich kopii iFolderu. Każdy użytkownik może umieścić współużytkowany iFolder w dowolnej lokalizacji na komputerze, o ile są spełnione wymagania opisane w temacie . Prawa dostępu do iFolderów Klient programu iFolder obsługuje uprawnienia właściciela i trzy poziomy dostępu członków iFolderu: Członkowie grupy LDAP dziedziczą zestaw praw dostępu danej grupy. Właściciel: Właścicielem iFolderu może być tylko jeden użytkownik. Zazwyczaj jest nim użytkownik, który utworzył iFolder. Właściciel może użyć klienta programu iFolder w celu przeniesienia prawa własności na innego członka iFolderu. Właściciel iFolderu ma nad nim pełną kontrolę. Może odczytywać i zapisywać dane w iFolderze, zarządzać listą członków i prawami dostępu oraz odbierać członkom pełną kontrolę nad iFolderem. Jeśli właścicielem iFolderów jest grupa LDAP, prawa pełnej kontroli mają wszyscy członkowie. Pełna kontrola: Członek współużytkowanego iFolderu mający pełne prawa dostępu. Może odczytywać i zapisywać dane w iFolderze oraz zarządzać listą członków i prawami dostępu wszystkich użytkowników poza właścicielem. Odczyt/Zapis: Członek współużytkowanego iFolderu z prawem odczytu/zapisu do katalogów i plików zawartych w iFolderze. Taki użytkownik może modyfikować plik, ale zmiany lokalne zostaną zsynchronizowane z kopiami pliku pozostałych członków iFolderu. Tylko do odczytu: Członek współużytkowanego iFolderu, który ma wyłącznie prawo do odczytu katalogów i plików w iFolderze. Taki użytkownik może modyfikować plik, ale zmiany lokalne nie zostaną zsynchronizowane z kopiami pliku pozostałych członków iFolderu. Każdy użytkownik programu iFolder lub grupa LDAP może być właścicielem i członkiem różnych iFolderów. Właściciel ma zawsze pełną kontrolę nad danymi. Poziom dostępu do współdzielonych iFolderów może się różnić w zależności od praw określonych przez innego użytkownika o pełnych uprawnieniach. Synchronizacja plików W trakcie połączenia z serwerem, program iFolder może zsynchronizować członkostwo iFolderów i pliki w tle. Podczas konfigurowania konta iFolder można włączyć opcję Zapamiętaj moje hasło , dzięki czemu program iFolder może pamiętać hasło na tym komputerze i przy następnym uruchomieniu programu iFolder nastąpi automatyczne połączenie z serwerem i synchronizacja danych bez wyświetlania prośby o podanie hasła. Klient iFolder może być automatycznie uruchamiany podczas każdorazowego logowania użytkownika w systemie operacyjnym na stacji roboczej. Sesja programu jest uruchamiana w tle, dzięki czemu użytkownik może pracować z plikami w lokalnych iFolderach, a wszystkie zmiany są śledzone i rejestrowane. Pliki można synchronizować ręcznie lub w określonych przedziałach czasowych. Program iFolder jest również wyposażony w funkcję synchronizacji delta. W razie dokonania jakichkolwiek zmian w pliku z iFolderu synchronizacji podlegają jedynie delty i zmiany. Innymi słowy, synchronizacja delta powoduje odtworzenie aktualizacji tylko od czasu poprzedniej synchronizacji między klientem programu iFolder i serwerem. Powoduje to zwiększenie efektywności, ponieważ skrócony zostaje czas synchronizacji. Migration (migracja) Program Novell iFolder zapewnia prostą, bezproblemową migrację z wersji iFolder 2. x do klienta programu iFolder dla programu Novell iFolder 3.7. Kreator migracji udostępniany przez klienta programu iFolder pomaga w migrowaniu istniejących danych programu iFolder 2. x do programu iFolder 3.6 w szybki i łatwy sposób. Więcej informacji można znaleźć w dokumencie . Szyfrowanie Program iFolder zapewnia najwyższy stopień bezpieczeństwa dla poufnych plików w iFolderach, chroniąc je przed zamierzonym lub niezamierzonym dostępem ze strony nieupoważnionych osób. W przeszłości bezpieczeństwo danych po stronie serwera nie było zagwarantowane, ponieważ dane te były dostępne zarówno dla administratora jak i dla każdego, kto uzyskał nieautoryzowany dostęp do serwera. Na dodatek w przypadku dostępu do plików w iFolderach za pośrednictwem dostawcy usług internetowych istnieje możliwość nieświadomego dostępu nieupoważnionej osoby do poufnych plików użytkownika. Obecnie można szyfrować i zapisywać pliki na serwerze, a także odtwarzać je za pomocą zwrotu szyfrowania, znanego tylko użytkownikowi. W przypadku zapomnienia zwrotu szyfrowania wybrany podczas tworzenia szyfrowanego folderu iFolderu agent odzyskiwania pomoże odtworzyć dane. Szyfrowanych iFolderów nie można współużytkować. Więcej informacji dotyczących szyfrowania można znaleźć w temacie . Uaktualnienie Program Novell iFolder 3.7 zapewnia proste uaktualnienie z programu iFolder 3. x do klienta programu iFolder dla programu Novell iFolder 3.6 i nowszych wersji. Więcej informacji można znaleźć w dokumencie . Scalanie Za pomocą scalania można połączyć dane iFolderu i zminimalizować przesyłanie danych między klientem programu iFolder a serwerem. Scalanie umożliwia także przeniesienie istniejącego folderu w inne miejsce na komputerze klienta. Więcej informacji można znaleźć w dokumencie . Domyślny iFolder Program iFolder umożliwia skonfigurowanie domyślnego iFolderu w trakcie konfigurowania nowego konta. Podczas konfigurowania nowego konta iFolder program iFolder automatycznie sprawdza obecność domyślnego iFolderu. Jeśli domyślny iFolder nie został utworzony, program iFolder wyświetla monit z prośbą o jego utworzenie. Jeśli już istnieje, klient programu iFolder wyświetla monit z prośbą o pobranie. Obie te opcje można jednak zignorować. Więcej informacji można znaleźć w punkcie w temacie . Rozszerzony dostęp do sieci Web Program iFolder zapewnia rozszerzony interfejs sieci Web, umożliwiający dostęp do plików iFolder na zdalnych serwerach. Za pomocą konsoli dostępu do sieci Web można skorzystać z przeglądarki internetowej, aby uzyskać dostęp do plików na serwerze iFolder z dowolnej stacji roboczej bez konieczności instalowania klienta programu iFolder. Konsola dostępu do sieci Web umożliwia wykonanie wszystkich operacji klienta programu iFolder. W porównaniu z poprzednimi wersjami programu iFolder program iFolder 3.6 i wersje późniejsze umożliwiają tworzenie, przeglądanie, współużytkowanie, przekazywanie i kasowanie iFolderów za pośrednictwem konsoli dostępu do sieci Web. Użytkownicy mobilni mogą również skorzystać z tego udogodnienia za pośrednictwem sieci Web. Dziennik synchronizacji Dziennik synchronizacji wyświetla informacje o wykonywanych w tle działaniach programu iFolder, takich jak przekazywanie i pobieranie plików dla różnych iFolderów, naruszenia założeń, wykluczonych plików oraz niezsynchronizowanych plików. </content>
</topic>

<topic>
  <title>Co dalej</title>
  <url>../ovwnext.html</url>
  <content>Co dalej Informacje na temat konfigurowania z wykorzystaniem klienta programu iFolder można znaleźć w następujących sekcjach: </content>
</topic>

<topic>
  <title>Zarządzanie kontami i preferencjami programu iFolder</title>
  <url>../accountsprefs.html</url>
  <content>Zarządzanie kontami i preferencjami programu iFolder W tej sekcji opisano sposoby konfigurowania kont iFolder™ oraz metody zarządzania preferencjami dla klienta programu iFolder </content>
</topic>

<topic>
  <title>Uruchamianie klienta programu iFolder</title>
  <url>../startclient.html</url>
  <content>Uruchamianie klienta programu iFolder Gdy program iFolder jest uruchomiony, w obszarze powiadomień paska zadań wyświetlona jest ikona Usługi iFolder Program iFolder jest zintegrowany ze środowiskiem roboczym. Symbol iFolderu (zielona litera „i”) pojawia się na iFolderze, gdy jest on wyświetlany w menedżerze plików, na pulpicie lub w przeglądarce iFolderów. Zaszyfrowany iFolder jest oznaczony symbolem (folder zablokowany). Obszar powiadomień na pasku zadań musi być włączony, aby ikona Usługi iFolder mogła być wyświetlana w czasie działania programu iFolder. Z plikami w lokalnych iFolderach w dowolnej chwili można pracować lokalnie. Uruchomiony klient programu iFolder zawsze zapisuje zmiany dokonywane w czasie pracy użytkownika na danych lokalnego iFolderu. Jeśli zmiany w danych lokalnego iFolderu dokonywane są w sytuacji, gdy program iFolder nie jest uruchomiony, program iFolder zidentyfikuje i zapisze różnice przy następnym jego uruchomieniu. Gdy program iFolder nie jest uruchomiony, iFoldery pojawiają się w menedżerze plików lub na pulpicie. Do plików w lokalnej kopii iFolderu można uzyskać dostęp, ale nie można zarządzać iFolderami. Na dodatek, aby utworzyć iFolder lub zsynchronizować jego pliki, użytkownik musi być zalogowany do konta. Podczas tworzenia konta użytkownik jest logowany za pośrednictwem protokołu SSL. Gdy pojawi się monit o zaakceptowanie certyfikatu serwera, należy sprawdzić poprawność tego certyfikatu i zaakceptować go, aby nawiązać połączenie. Więcej informacji dotyczących zatrzymywania klienta programu iFolder można znaleźć w temacie . Linux Automatyczne uruchamianie programu iFolder podczas logowania Aby umożliwić programowi iFolder automatyczne uruchomienie, gdy użytkownik loguje się do środowiska roboczego, należy wykonać jedną z poniższych czynności: Otwórz menu aplikacji, kliknij przycisk Więcej aplikacji , znajdź i kliknij prawym przyciskiem myszy na opcji iFolder 3 , a następnie z menu wybierz opcję Dodaj do Autostartu . Upewnij się, że w chwili wylogowania się, program iFolder jest uruchomiony, po czym zapisz konfigurację sesji. Wybierz tę opcję sesji przy logowaniu się do środowiska roboczego. Można także otworzyć okno terminalu, zalogować się jako superużytkownik , a następnie uruchomić program /opt/gnome/bin/gnome-session-properties , aby dodać program iFolder do listy programów uruchamianych podczas logowania na komputerze. Aby zablokować automatyczne uruchomienie programu iFolder podczas logowania, należy wykonać jedną z następujących czynności: Otwórz menu aplikacji, znajdź i kliknij prawym przyciskiem myszy na opcji iFolder 3 , a następnie wybierz opcję Usuń z Autostartu . Upewnij się, że w chwili wylogowania się program iFolder nie jest uruchomiony, po czym zapisz konfigurację sesji. Wybierz tę opcję sesji przy logowaniu się do środowiska roboczego. Ręczne uruchamianie programu iFolder Zaloguj się na komputerze z identyfikatorem lokalnego użytkownika systemu Linux, który ma być używany podczas tworzenia iFolderów. Uruchom program iFolder, używając z jednej z następujących metod: Na pasku zadań otwórz menu aplikacji, kliknij przycisk Więcej aplikacji , znajdź pozycję iFolder 3 , szukając i przewijając wśród dostępnych opcji kliknij prawym przyciskiem myszy na opcji iFolder 3, a następnie wybierz opcję Uruchom iFolder 3 . Uruchom terminal powłoki i wprowadź polecenie /usr/bin/ifolder Windows Automatyczne uruchamianie programu iFolder podczas logowania Aby automatycznie uruchamiać program iFolder podczas logowania się użytkownika do środowiska roboczego: Kliknij prawym przyciskiem myszy ikonę Usługi iFolder , a następnie wybierz opcję Preferencje , aby otworzyć okno dialogowe Preferencje programu iFolder i kartę Ogólne . Zaznacz opcję Uruchom iFolder podczas logowania do pulpitu , a następnie kliknij przycisk Zastosuj . Kliknij przycisk OK , aby zamknąć okno dialogowe Preferencje programu iFolder. Aby zablokować automatyczne uruchomienie programu iFolder podczas logowania: Kliknij prawym przyciskiem myszy ikonę Usługi iFolder , a następnie wybierz opcję Preferencje , aby otworzyć okno dialogowe Preferencje programu iFolder i kartę Ogólne . Odznacz opcję Uruchom iFolder podczas logowania do pulpitu , a następnie kliknij przycisk Zastosuj . Kliknij przycisk OK , aby zamknąć okno dialogowe Preferencje programu iFolder. Ręczne uruchamianie programu iFolder Zaloguj się na komputerze, korzystając z identyfikatora lokalnego użytkownika Windows, którego chcesz używać podczas tworzenia iFolderów. Jeśli program iFolder nie został automatycznie uruchomiony po pomyślnym zalogowaniu, uruchom go, klikając polecenia Start Programy iFolder 3 , a następnie wybierz aplikację Klient iFolder 3 . Macintosh Automatyczne uruchamianie programu iFolder podczas logowania Jeśli program iFolder ma być automatycznie uruchamiany podczas logowania do komputera Macintosh, należy dodać go do elementów Autostartu . Uruchom program iFolder. Na panelu kliknij prawym przyciskiem myszy ikonę programu iFolder i wybierz opcję Uruchom podczas logowania . lub Z poziomu panelu naciśnij klawisz Ctrl, kliknij ikonę iFolderu, a następnie wybierz opcję Uruchom podczas logowania . Aby program iFolder nie był uruchamiany automatycznie, usuń go z elementów Autostartu . Na panelu kliknij prawym przyciskiem myszy ikonę programu iFolder i odznacz opcję Uruchom podczas logowania . lub Na panelu kliknij prawym przyciskiem myszy lub naciśnij klawisz Ctrl i kliknij ikonę programu iFolder, a następnie odznacz opcję Uruchom podczas logowania . Ręczne uruchamianie programu iFolder Zaloguj się na komputerze z identyfikatorem lokalnego użytkownika systemu Macintosh, który ma być używany podczas tworzenia iFolderów. Uruchom program iFolder, używając z jednej z następujących metod: Otwórz katalog Aplikacje na dysku twardym Macintosh HD , wybierz pozycję Aplikacje , a następnie kliknij dwukrotnie pozycję iFolder 3 . Wpisz iFolder w wierszu Spotlight (naciśnij przycisk Apple + spacja lub kliknij ikonę szkła powiększającego w prawym górnym rogu), a następnie kliknij pozycję iFolder 3 w katalogu Aplikacje. Otwórz terminal powłoki, zaloguj się jako superużytkownik, a następnie wpisz /Applications/iFolder 3.app/Contents/MacOS/iFolder 3 </content>
</topic>

<topic>
  <title>Konfigurowanie konta programu iFolder</title>
  <url>../accounts.html</url>