<?xml version="1.0" encoding="UTF-8" ?>
<!-- saved from url=(0014)about:internet -->

<!DOCTYPE site [
 <!ELEMENT site (topic+)>
  <!ELEMENT topic (title,url,content)>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT url (#PCDATA)>
   <!ELEMENT content (#PCDATA)>
]>

<site>
<topic>
  <title>Пакет обновления 1 для OES 2. Многоплатформенная справка по Novell iFolder 3.7</title>
  <url>../bookinfo.html</url>
  <content>Пакет обновления 1 для OES 2. Многоплатформенная справка по Novell iFolder 3.7 3.7 October 2008 Справка iFolder Novell® iFolder® - это приложение для совместного использования файлов клиентами Linux*, Windows* и Macintosh*. С помощью iFolder можно автоматически получать доступ к своим файлам всегда и везде, в режиме прямого подключения и в автономном режиме, а также с любых компьютеров. Вы можете совместно использовать файлы в нескольких папках iFolder, каждая из которых предназначена для различных пользователей. Вы можете управлять пользователями папок iFolder и их правами доступа к файлам в этих папках. Кроме того, Вы можете стать пользователем папок iFolder, доступ к которым был предоставлен коллегами. В данной справочной системе приведена информация по использованию клиента iFolder и управлению им. Для кого предназначено это руководство Данное руководство предназначено для пользователей клиента iFolder. Дополнительная документация Если используется клиент iFolder 3.7 на сервере Novell iFolder 3.7 Enterprise Server или на сервере веб-доступа, см. iFolder 3.7 User Guide for Novell iFolder 3.7 (Руководство пользователя iFolder 3.6 для Novell iFolder 3.6) на веб-сайте документации Novell iFolder . Условные обозначения, используемые в документации В документации Novell символ "больше" (&gt;) используется для разделения операций внутри одного действия и элементов в пути перекрестных ссылок. Символ товарного знака (®, ™ и т. д.) обозначает товарный знак Novell. Символ звездочки (*) обозначает товарный знак независимого производителя. Пути, которые для одних платформ записываются с помощью обратной косой черты, а для других – с помощью прямой, в настоящем руководстве представлены с использованием обратной косой черты. Пользователи платформ, на которых используется левая косая черта (например, Linux или UNIX), должны использовать ее в соответствии с требованиями программного обеспечения. </content>
</topic>

<topic>
  <title>Обзор iFolder</title>
  <url>../overview.html</url>
  <content>Обзор iFolder Novell® iFolder® - это приложение для совместного использования файлов клиентами Linux, Windows и Macintosh. Вы можете совместно использовать файлы в нескольких папках iFolder, каждая из которых предназначена для различных пользователей или групп LDAPGroup. Вы можете управлять пользователями папок iFolder и устанавливать уровень доступа для каждого члена. Кроме того, Вы можете стать пользователем папок iFolder, доступ к которым был предоставлен коллегами. Приложение iFolder 3.7 предоставляет удобный пользовательский интерфейс для миграции клиента iFolder 2. x в iFolder 3.6 и более поздней версии, а также для обновления клиента iFolder 3.. x на iFolder 3.6 и более позднюю версию. В данном разделе приведено описание различных преимуществ и функций iFolder: </content>
</topic>

<topic>
  <title>Преимущества iFolder</title>
  <url>../benefits.html</url>
  <content>Преимущества iFolder iFolder предоставляет следующие преимущества: Интеграция iFolder с соответствующей операционной средой рабочей станции позволяет легко создавать различные папки iFolder и управлять ими. iFolder является масштабируемой и очень гибкой системой, которая практически не имеет ограничений на число папок iFolder для одного пользователя и на число членов использования папки iFolder. Включение функции шифрования позволяет iFolder защитить данные при передаче по сети или при хранении на сервере iFolder. Благодаря усовершенствованной консоли веб-доступа можно получать доступ к файлам, хранящимся на сервере iFolder, с любой рабочей станции без клиента iFolder, используя веб-навигатор и выполняя все операции клиента iFolder. Существует возможность простого и избирательного совместного использования личных и служебных файлов. iFolder осуществляет миграцию и обновление данных iFolder на последнюю версию. iFolder поддерживает группы LDAPGroup. Существует возможность совместного использование папок iFolder с членами групп LDAPGroup. Члены групп LDAPGroup могут создавать папки iFolder, владеть ими и использовать их совместно с другими отдельными пользователями или членами других групп LDAPGroup. Существует возможность управления уровнем доступа пользователей папок iFolder, владельцем которых Вы являетесь или в которых у Вас есть необходимые права на управление правами доступа других членов. iFolder поддерживает прозрачные обновления файлов в папках членов iFolder на различных рабочих станциях. При активировании приложения iFolder производится отслеживание и протоколирование изменений, выполненных во время автономной работы, и синхронизация изменений при подключении к серверу. iFolder обеспечивает защищенную аутентификацию членов iFolder для синхронизации данных. Приложение iFolder является хорошей альтернативой обмену файлами по электронной почте, так как позволяет избежать ограничений на размеры прикрепленных к сообщению файлов и снижает требования к хранилищу электронной почты. </content>
</topic>

<topic>
  <title>Клиент iFolder</title>
  <url>../bawqltp.html</url>
  <content>Клиент iFolder Клиент iFolder интегрируется с операционной системой и предоставляет сервисы iFolder в соответствующей вычислительной среде рабочей станции. Клиент iFolder позволяет управлять собственными папками iFolder и выбрать, какие совместно используемые папки iFolder необходимо установить на каждом компьютере. Продукт iFolder поддерживает следующие операционные системы: SUSE® Linux Enterprise Desktop 10 с пакетом обновления 1 Windows Vista с пакетом обновления 1 Windows XP с пакетом обновления 2 или Windows 2000 Professional с пакетом обновления 4 openSUSE® 10.2 и более поздней версии Apple Macintosh® 10.4 и более поздней версии </content>
</topic>

<topic>
  <title>Учетная запись iFolder</title>
  <url>../bawqmpe.html</url>
  <content>Учетная запись iFolder Учетная запись iFolder создается, когда администратор сервисов iFolder персонифицирует для Вас доступ в качестве пользователя iFolder для сервера iFolder. Имя пользователя и пароль предоставляются администратором. В зависимости от принятых на предприятии правил это может быть имя пользователя или адрес его электронной почты и соответствующий пароль. Перед созданием папок iFolder необходимо сконфигурировать, как минимум, одну учетную запись сервиса iFolder. См. дополнительные сведения: . Сеанс iFolder начинается при регистрации с помощью учетной записи сервисов iFolder и завершается при выходе из системы или выходе пользователя из клиента iFolder. Файлы в папках iFolder синхронизируются с другими активными папками iFolder только при активном сеансе и при работе в режиме прямого подключения. Доступ к локальным папкам iFolder можно получить в любое время независимо от того, есть регистрация с помощью учетной записи или нет. См. дополнительные сведения: . </content>
</topic>

<topic>
  <title>Многоплатформенное использование</title>
  <url>../ovwxplat.html</url>
  <content>Многоплатформенное использование Пользовательские интерфейсы клиента iFolder для систем Linux, Windows и Macintosh соответствуют соглашениям об интерфейсах соответствующих платформ. Способ выполнения общих задач в основном аналогичен на каждой платформе, но возможны небольшие отличия в кнопках, в области отображения, в значках функций, в расположении панели задач, в начальных настройках iFolder и т.д. В данном руководстве приведены инструкции только для одной из трех платформ, за исключением случаев, когда процедуры явно отличаются. В следующей таблице перечислены основные отличия и сходства интерфейса клиента. Задание Linux Windows Macintosh Меню iFolder / параметр правого щелчка значка на панели задач Quit (Завершить) Выход Quit (Завершить) Настройки iFolder &gt; диалоговое окно "Учетные записи" Кнопка Добавить Кнопка Добавить Кнопка Плюс ( + ) Настройки iFolder диалоговое окно "Учетные записи" Кнопка Удалить Кнопка Удалить Кнопка Минус ( - ) Несколько местоположений Кнопка Закрыть Действия производятся при выполнении операции Кнопки ОК , Отмена и Применить Действия производятся только при нажатии кнопок Применить или ОК Кнопки OK и Отмена Действия производятся при выполнении операции Диалоговое окно Настройки iFolder Добавление iFolder в Startup Programs (Запуск программ) на рабочей станции Выбор (включение) Запуск iFolder при регистрации в рабочей станции Эта функция недоступна Конфигурирование учетной записи iFolder Запомнить пароль Запомнить пароль на этом компьютере Запомнить пароль Область оповещений Область оповещений Область "Состояния и оповещения" Область оповещений Щелчок правой кнопкой в области оповещений Настройки учетной записи Учетные записи Эта функция недоступна Папки iFolder меню iFolder Свойства Свойства Получить информацию Мастера iFolder Кнопка Далее и кнопка Назад Кнопка Далее и кнопка Назад Нет кнопок для перемещения впереди назад. Можно настроить имя пользователя, пароль и сервер в одном окне. Конфигурирование учетной записи iFolder Помощник по настройке учетных записей iFolder Мастер создания учетных записей iFolder Настройки &gt; Учетная запись Мастер настройки сервера iFolder Сервер iFolder Выбор сервера iFolder Недоступно Мастер настройки электронных персон iFolder Идентификация Сведения об учетной записи iFolder Недоступно </content>
</topic>

<topic>
  <title>Основные возможности iFolder</title>
  <url>../keyfeatures.html</url>
  <content>Основные возможности iFolder Перед началом работы с iFolder важно понять основные возможности этого продукта, описанные в следующих разделах: Совместное использование папки iFolder Обычно, если Вы работаете в нескольких местоположениях или совместно работаете с другими пользователями, необходимо постоянное управление версиями файлов. Чтобы получить самую последнюю версию файлов на всех компьютерах, на которых Вы работаете, достаточно установить на них клиент iFolder и создать папку iFolder. iFolder также позволяет совместно использовать несколько папок iFolder и их содержимое с другими авторизованными пользователями или группами LDAPGroup. Для получения дополнительной информации о совместном использовании папки iFolder см. раздел . Клиент iFolder поддерживает совместное использование информации путем синхронизации файлов на различных компьютерах через центральный сервер. С его помощью можно выполнять следующие задачи: совместно использовать файлы на различных компьютерах; совместно использовать файлы с другими пользователями; владеть несколькими папками iFolder; использовать различные папки iFolder, доступ к которым был предоставлен другими пользователями; быть владельцем или членом папок iFolder с помощью различных учетных записей. Работа с папками iFolder осуществляется непосредственно из менеджера файлов или с помощью навигатора iFolder, который входит в состав клиента. Внутри папки iFolder можно установить любую структуру подкаталогов, которая соответствует личным или корпоративным потребностям. Структура подкаталогов одинакова для всех членов папок iFolder. Совместное использование папок iFolder Папка iFolder представляет собой локальный каталог, файлы которого могут совместно использоваться определенными пользователями и синхронизироваться через центральный сервер. Файлы iFolder доступны всем членам папки iFolder и могут изменяться теми пользователями, кто обладает соответствующими правами. Доступ к папкам iFolder можно осуществлять с нескольких рабочий станций; кроме того, папки iFolder можно использовать совместно с отдельными пользователями и членами групп LDAPGroup. Вы решаете, какие пользователи смогут получать доступ к папкам iFolder, а также устанавливаете права доступа каждого члена. Подобным образом Вы можете стать пользователем совместно используемых папок iFolder, владельцами которых являются другие сотрудники Вашей организации. При совместном использовании папки iFolder пользователи с правом "Запись" могут изменять структуру каталогов, после чего изменения осуществляются во всех копиях папки iFolder. Каждый пользователь может указать совместно используемую папку iFolder в любом расположении на своем компьютере в соответствии с требованиями раздела . Права доступа к iFolder Клиент iFolder поддерживает владельца и три уровня доступа для членов папки iFolder: Члены группы LDAPGroup наследуют права доступа, установленные для данной группы. Владелец: Только один пользователь может быть владельцем папки iFolder. Как правило, это пользователь, который создал папку iFolder. Владелец может использовать клиент iFolder для передачи права на владение другому члену папки iFolder. Владелец папки iFolder имеет право на полный контроль. Этот пользователь имеет право доступа для чтения/записи к папке iFolder, управляет членством и правами доступа пользователей, а также может удалять право "Полный контроль" для любого члена. Если группа LDAPGroup является владельцем папки iFolder, всем пользователям, являющимся членами этой группы, предоставляется право "Полный контроль". Полный контроль: Уровень доступа члена совместно используемой папки iFolder с правом на полный контроль. Этот член имеет право доступа для чтения/записи к папке iFolder, управляет членством и правами доступа всех пользователей за исключением владельца. Для чтения/записи: Это право получает член совместно используемой папки iFolder для доступа к каталогам и файлам в папке iFolder с правами "Чтение/Запись". Данный член может изменять свой файл, и эти локальные изменения синхронизируются с копиями папки iFolder других членов. Только чтение: Уровень доступа члена совместно используемой папки iFolder с правом только для чтения в каталогах и файлах папки iFolder. Данный член может изменять свой файл, но эти локальные изменения не синхронизируются с копиями папки iFolder других членов. Любой пользователь iFolder может владеть несколькими папками iFolder и быть членом других папок iFolder. Владелец всегда обладает правом "Полный контроль". Пользователи могут иметь различный уровень доступа к каждой совместно используемой папке iFolder в зависимости от права доступа, устанавливаемого членом с правом "Полный контроль". Синхронизация файлов При подключении к серверу приложение iFolder может выполнить синхронизацию членства и файлов iFolder в фоновом режиме во время работы пользователя. При настройке учетной записи iFolder пользователь может включить функцию Запомнить пароль . Таким образом, пароль запоминается в приложении iFolder на компьютере. При последующем запуске iFolder происходит автоматическое подключение к серверу и выполняется синхронизация данных без отображения запроса на ввод пароля. Можно настроить программное обеспечение клиента iFolder для автоматического запуска при каждой регистрации пользователя в рабочей станции. Сеанс выполняется в фоновом режиме, пока пользователь работает со своими файлами в локальной папке iFolder. При этом осуществляется отслеживание и протоколирование всех выполняемых изменений. Можно указать интервалы синхронизации файлов. В приложении iFolder также предусмотрена возможность дельта-синхронизации. После изменения файла iFolder выполняется только дельта-синхронизация или синхронизация изменений с сервером. Другими словами, при дельта-синхронизации осуществляются только обновления, выполненные с момента последней синхронизации между клиентом iFolder и сервером. Благодаря сокращению времени синхронизации эффективность процесса повышается. Migration (Переход) В приложении Novell iFolder предоставляется возможность простого перехода с программного обеспечения iFolder 2. x на клиент iFolder для Novell iFolder 3.7. С помощью мастера миграции, доступного в приложении клиента iFolder , можно быстро выполнить перенос существующих данных iFolder 2. x в приложение iFolder 3.6 и более поздней версии. См. дополнительные сведения: . Шифрование В приложении iFolder предусмотрены дополнительные меры безопасности, необходимые для защиты конфиденциальных файлов iFolder от намеренного или непреднамеренного несанкционированного доступа. Ранее безопасность данных на сервере не гарантировалась, поэтому данные были доступны администратору или любому пользователю, получившему несанкционированный доступ к серверу. Кроме того, если доступ к файлам iFolder осуществляется через поставщика Интернет-услуг, существует вероятность несанкционированного непреднамеренного доступа к конфиденциальным файлам. Теперь можно шифровать и хранить файлы на сервере, а затем дешифровывать их, указав контрольную фразу, известную только Вам. Если контрольная фраза была забыта, с помощью агента восстановления, выбранного при создании зашифрованной папки iFolder, можно восстановить данные. На следующем рисунке представлен принцип восстановления утраченных данных с помощью iFolder. Совместное использование зашифрованных папок iFolder не поддерживается. Для получения дополнительной информации о шифровании см. раздел . Upgrade Novell iFolder 3.7 предоставляет возможность простого обновления версии iFolder 3. x на клиент iFolder для Novell iFolder 3.6 и более поздних версий. См. дополнительные сведения: . Объединить Функция слияния позволяет консолидировать данные iFolder и уменьшить объем данных, передаваемых между клиентом iFolder и сервером. Функция слияния также позволяет перемещать существующие папки в другое местоположение на клиентской рабочей станции. См. дополнительные сведения: . Папка iFolder по умолчанию В приложении iFolder при конфигурировании новой учетной записи можно настроить папку iFolder по умолчанию. При конфигурировании новой учетной записи iFolder в приложении iFolder выполняется автоматическая проверка наличия папки iFolder по умолчанию. Если папка iFolder по умолчанию не была создана, появляется запрос на создание. При наличии такой папки клиент iFolder отображает запрос на загрузку. Можно также отказаться от обоих указанных вариантов. Для получения дополнительной информации см. подраздел в разделе . Расширенный веб-доступ В приложении iFolder предоставляется усовершенствованный веб-интерфейс, позволяющий получать доступ к файлам iFolder на удаленных серверах. Благодаря усовершенствованной консоли веб-доступа можно использовать веб-навигатор для доступа к файлам на сервере iFolder с любой рабочей станции без установки клиента iFolder. Клиент веб-доступа позволяет выполнять все операции клиента iFolder. По сравнению с предыдущими версиями iFolder 3.6 и более поздние версии позволяют создавать, просматривать, совместно использовать, отправлять и удалять папки iFolder через усовершенствованную консоль веб-доступа. Мобильные пользователи могут также получать доступ к этим функциям через Интернет. Журнал синхронизации В журнале синхронизации отображаются все действия iFolder в фоновом режиме, например отправка или получение файлов для различных папок iFolder, нарушения политик, исключенные файлы и несинхронизированные файлы. </content>
</topic>

<topic>
  <title>Что дальше</title>
  <url>../ovwnext.html</url>
  <content>Что дальше Для получения информации о конфигурировании с помощью клиента iFolder см. следующие разделы: </content>
</topic>

<topic>
  <title>Управление учетными записями и настройками iFolder</title>
  <url>../accountsprefs.html</url>
  <content>Управление учетными записями и настройками iFolder В данном разделе приведена информация о конфигурировании учетных записей iFolder™ и по управлению настройками клиента iFolder </content>
</topic>

<topic>
  <title>Запуск клиента iFolder</title>
  <url>../startclient.html</url>
  <content>Если сервис iFolder запущен, значок отображается на папках iFolder во время их просмотра в менеджере файлов на рабочей станции или в средстве просмотра iFolder. Необходимо включить область оповещений на панели задач, чтобы при запуске приложения iFolder на ней отображался значок Сервисы iFolder . Работать локально с фалами в локальных папках iFolder можно в любое время. Если клиент iFolder запущен, во время работы с папками все изменения локальной папки данных iFolder протоколируются. Если локальные данные папки iFolder изменяются, когда приложение iFolder не запущено, при последующем запуске приложение iFolder определяет и протоколирует все изменения. Если приложение iFolder не запущено, папки iFolder отображаются в менеджере файлов или на рабочей станции. Можно получить доступ к файлам в локальной копии папки iFolder, но управлять папками iFolder нельзя. Кроме того, необходимо зарегистрироваться с помощью учетной записи, чтобы иметь возможность создавать папку iFolder или синхронизировать ее файлы. Во время создания учетной записи вход пользователя в систему выполняется по протоколу SSL. При получении запроса о том, чтобы принять сертификат сервера, для успешного соединения необходимо проверить сертификат и принять его. Дополнительную информацию об остановке клиента iFolder см. в разделе . Linux Автоматический запуск iFolder при регистрации Чтобы настроить автоматический запуск iFolder при регистрации в компьютере, выполните одно из следующих действий: Откройте меню приложений, щелкните More Applications (Приложения), найдите и щелкните правой кнопкой iFolder 3 , затем в меню выберите Add to Startup Programs (Добавить в запуск программ). При разрегистрации убедитесь, что приложение iFolder запущено, затем сохраните настройки сеанса. При регистрации в компьютере выберите этот сеанс. Откройте окно терминала, зарегистрируйтесь в качестве пользователя root , затем введите команду /opt/gnome/bin/gnome-session-properties , чтобы добавить iFolder в качестве программы, которая будет загружаться при регистрации в компьютере. Чтобы отключить автоматический запуск iFolder при регистрации, выполните одно из следующих действий: Откройте меню приложений, найдите и щелкните правой кнопкой iFolder 3 , затем выберите Remove from Startup Programs (Удалить из запуска программ). При разрегистрации убедитесь, что приложение iFolder не запущено, затем сохраните настройки сеанса. При регистрации в компьютере столе выберите этот сеанс. Запуск iFolder вручную Зарегистрируйтесь на компьютере в качестве локального пользователя Linux, которого необходимо использовать для создания папок iFolder. Для запуска iFolder используйте один из следующих способов: На панели задач откройте меню приложений, щелкните More Applications (Приложения), среди доступных элементов найдите или перейдите к iFolder 3 , щелкните правой кнопкой "iFolder 3", затем выберите Start iFolder 3 (Запуск iFolder 3). Откройте оболочку терминала и введите /opt/novell/ifolder3/bin/ifolder Windows Автоматический запуск iFolder при входе Порядок настройки автоматического запуска iFolder при регистрации на рабой станции: Right-click the iFolder Services icon, then select Preferences to open the iFolder Preferences dialog box to the General tab. Выберите Запуск iFolder при регистрации в рабочей станции , затем щелкните Применить . Щелкните ОК , чтобы закрыть диалоговое окно "Настройки iFolder". Порядок отключения автоматического запуска iFolder при регистрации в рабочей станции: Щелкните правой кнопкой значок Сервисы iFolder , затем выберите Настройки , чтобы открыть диалоговое окно "Настройки iFolder" на вкладке Общие . Отмените выбор параметра Запуск iFolder при регистрации в рабочей станции , затем щелкните Применить . Щелкните ОК , чтобы закрыть диалоговое окно "Настройки iFolder". Запуск iFolder вручную Зарегистрируйтесь на компьютере в качестве локального пользователя Windows, которого необходимо использовать для создания папок iFolder. If iFolder does not start automatically on successful logon, start iFolder by clicking Start Programs iFolder 3 , then select the iFolder 3 Client application. Macintosh Автоматический запуск iFolder при регистрации Для разрешения автоматического запуска клиента iFolder при регистрации в компьютере Macintosh добавьте iFolder в Startup Items (Автозагрузка). Запустите iFolder. На панели быстрого запуска приложений щелкните правой кнопкой значок iFolder и выберите параметр Open at Login (Открывать при регистрации). или На панели быстрого запуска приложений нажмите клавишу Ctrl, щелкните значок iFolder, затем выберите Open at Login (Открывать при регистрации). Чтобы отменить автоматический запуск приложения iFolder, удалите iFolder из списка Startup Items (Автозагрузка). В прикреплении щелкните правой кнопкой значок iFolder и отмените выбор параметра Open at Login (Открывать при регистрации). или На панели быстрого запуска приложений щелкните правой кнопкой значок iFolder или нажмите клавишу Ctrl и отмените выбор параметра Open at Login (Открывать при регистрации). Запуск iFolder вручную Зарегистрируйтесь на компьютере в качестве локального пользователя Macintosh, которого необходимо использовать для создания папок iFolder. Для запуска iFolder используйте один из следующих способов: Откройте каталог Applications (Приложения) на Macintosh HD , выберите Applications (Приложения), затем дважды щелкните приложение iFolder 3 . Введите iFolder в выделенном поле (кнопка Apple + пробел, либо щелкните значок лупы в верхнем правом углу), затем щелкните iFolder 3 в списке приложений. Откройте терминальную оболочку, зарегистрируйтесь в качестве пользователя root, затем введите /Applications/iFolder 3.app/Contents/MacOS/iFolder 3 </content>
</topic>

<topic>
  <title>Конфигурирование учетной записи iFolder</title>
  <url>../accounts.html</url>