<?xml version="1.0" encoding="UTF-8" ?>
<!-- saved from url=(0014)about:internet -->

<!DOCTYPE site [
 <!ELEMENT site (topic+) >
  <!ELEMENT topic (title,url,content) >
   <!ELEMENT url (#PCDATA) >
   <!ELEMENT profiled (#PCDATA | profiled)* >
   <!ELEMENT title (#PCDATA | profiled)* >
   <!ELEMENT content (#PCDATA | profiled)* >
   <!ATTLIST topic profiles CDATA #IMPLIED >
   <!ATTLIST profiled profiles CDATA #IMPLIED >
]>

<site>
<topic>
  <title>Guida multipiattaforma di Novell iFolder 3.9.2</title>
  <url>../bookinfo.html</url>
  <content>Guida multipiattaforma di Novell iFolder 3.9.2 December 2013 Guida di iFolder Novell iFolder è un'applicazione per la condivisione di file per client Linux,Windows e Macintosh. iFolder consente di sincronizzare automaticamente i file locali tra più computer in modo che sia possibile accedervi ovunque e in qualsiasi momento in modalità in linea e non in linea. È possibile condividere i file in più cartelle iFolder, a ognuna delle quali sono associati utenti diversi. L'utente controlla la partecipazione alla cartella iFolder da parte di altri e i rispettivi diritti di accesso ai file in essa contenuti. È inoltre possibile partecipare alle cartelle iFolder condivise di altri utenti. In questa Guida viene illustrato come utilizzare e gestire il client iFolder. Destinatari La guida è destinata agli utenti che utilizzano il client iFolder. Documentazione aggiuntiva Se si utilizza il iFolder 3.7 o un client con una versione successiva congiuntamente a Novell iFolder 3.7 o a una versione successiva di un server aziendale o di un server di accesso Web, vedere la Guida dell'utente di iFolder 3.9.x nel sito Web della documentazione di Novell iFolder . </content>
</topic>

<topic>
  <title>Panoramica di iFolder</title>
  <url>../overview.html</url>
  <content>Panoramica di iFolder Novell iFolder è un'applicazione per la condivisione di file per client Linux,Windows e Macintosh. È possibile condividere i file in più cartelle iFolder, a ognuna delle quali sono associati utenti o gruppi LDAP diversi, nonché controllare la partecipazione alla cartella iFolder da parte di altri utenti e i livelli di accesso per ciascun membro. È inoltre possibile partecipare alle cartelle iFolder condivise di altri utenti. iFolder dispone di un'interfaccia semplice e intuitiva per la migrazione sul lato client da iFolder 2. x a iFolder 3.6 e versioni successive e per l'upgrade lato client da iFolder 3. x a iFolder 3.6 e versioni successive. In questa sezione verranno illustrati i vari vantaggi e le funzioni di iFolder: </content>
</topic>

<topic>
  <title>Vantaggi di iFolder</title>
  <url>../benefits.html</url>
  <content>Vantaggi di iFolder iFolder offre i seguenti vantaggi: iFolder viene integrato con l’ambiente desktop nativo, in modo da semplificare la creazione e la gestione di più cartelle iFolder. iFolder è caratterizzato da scalabilità e flessibilità elevate, senza alcuna limitazione al numero di cartelle iFolder per utente e al numero di membri per cartella iFolder. Grazie alle funzioni di cifratura, è possibile garantire la protezione dei dati durante il trasferimento in rete e sul server iFolder. Grazie alle funzionalità avanzate della console di accesso Web, è possibile accedere ai file del server iFolder da qualsiasi workstation priva del client iFolder e utilizzare un browser Web standard per eseguire tutte le operazioni di un client iFolder. È possibile condividere file personali e di lavoro in modo semplice e selettivo. iFolder è in grado di eseguire la migrazione e l'upgrade dei dati alla versione più recente. iFolder supporta i gruppi LDAP. È possibile condividere le cartelle iFolder con gruppi LDAP. I membri del gruppo LDAP possono creare, possedere e condividere cartelle iFolder insieme ad altri singoli utenti o gruppi LDAP. È possibile controllare il livello di accesso degli utenti delle cartelle iFolder di cui si è proprietari o per cui si dispone dei diritti necessari per controllare i diritti di accesso dei membri L'aggiornamento dei file viene eseguito in modo invisibile all’utente nelle cartelle iFolder partecipanti su più workstation Quando iFolder è in esecuzione, tiene traccia delle modifiche effettuate in modalità non in linea e le registra per eseguire la sincronizzazione una volta eseguita la connessione al server. iFolder offre funzionalità di autenticazione sicura dei membri che accedono a una cartella iFolder per la sincronizzazione dei dati. iFolder offre un’alternativa allo scambio di file tramite e-mail, evitandone così le limitazioni di dimensioni per quanto riguarda gli allegati e riducendone le esigenze di archiviazione. </content>
</topic>

<topic>
  <title>Conto iFolder</title>
  <url>../bawqmpe.html</url>
  <content>Conto iFolder Un conto iFolder viene creato quando un amministratore dei servizi iFolder crea un nuovo utente iFolder per un server iFolder. L'amministratore fornisce un nome utente e una password. In un'azienda, questi possono corrispondere al nome utente o all'indirizzo di e-mail e alla relativa password già assegnati all'utente. Prima di creare cartelle iFolder, è necessario configurare almeno un conto iFolder. Per ulteriori informazioni, vedere . La sessione iFolder ha inizio nel momento in cui viene eseguito il login a un conto per i servizi iFolder e termina con l’esecuzione del logout o quando si esce dal client iFolder. Le cartelle iFolder vengono sincronizzate con altre cartelle iFolder attive solo quando la sessione è attiva e si sta lavorando in modalità in linea. È possibile accedere ai dati delle cartelle iFolder locali in qualsiasi momento, sia che sia stato eseguito il login al conto o meno. Per ulteriori informazioni, vedere il . </content>
</topic>

<topic>
  <title>Considerazioni sul supporto multipiattaforma</title>
  <url>../ovwxplat.html</url>
  <content>Considerazioni sul supporto multipiattaforma Le interfacce utente delle versioni per Linux, Windows e Macintosh del client iFolder sono conformi alle convenzioni adottate dalle singole piattaforme. L’esecuzione dei task comuni è analogo in ciascuna piattaforma, ma potrebbero esserci delle leggere differenze per quanto riguarda i pulsanti, l’area di visualizzazione, le etichette delle funzioni, l’ubicazione dell’area di notifica sul desktop, la preferenza di avvio di iFolder e così via. Tranne quando le procedure differiscono esplicitamente, in questa guida vengono fornite le istruzioni relative a una sola delle tre piattaforme. Nella seguente tabella sono elencate alcune tra le analogie e le differenze più comuni nell’interfaccia del client. Task Linux Windows Macintosh Menu iFolder Esci Esci Esci Preferenze di iFolder &gt; finestra di dialogo Conti Pulsante Aggiungi Pulsante Aggiungi Pulsante Più ( + ) Preferenze di iFolder finestra di dialogo Conti Pulsante Rimuovi Pulsante Rimuovi Pulsante Meno ( - ) Più ubicazioni Pulsante Chiudi Il commit delle azioni viene eseguito immediatamente Pulsanti OK , Annulla e Applica Il commit delle azioni viene eseguito solo quando si fa clic su Applica o OK Pulsanti OK e Annulla Il commit delle azioni viene eseguito immediatamente Finestra di dialogo Preferenze di iFolder Aggiungere iFolder ai programmi di avvio del desktop Selezionare (abilitare) Avvia iFolder al login al desktop Questa funzione non è disponibile Configurazione di un conto iFolder Memorizza password Memorizza password su questo computer Memorizza password Area di notifica Area di notifica Area di stato e di notifica Area di notifica Menu di scelta rapida dell'area di notifica Impostazioni conto Conti Questa funzione non è disponibile Menu iFolder cartelle iFolder Proprietà Proprietà Ottieni informazioni Procedure guidate iFolder Pulsanti Avanti e Indietro Pulsanti Avanti e Indietro Nessun pulsante per spostare in primo piano e indietro È possibile configurare il nome utente, la password e il server in un'unica finestra. Configurazione di un conto iFolder Assistente conti iFolder Creazione guidata conto iFolder Preferenze &gt; Conto Configurazione guidata server iFolder Server iFolder Scegliere un server iFolder Non disponibile Configurazione guidata identità iFolder Identità Informazioni conto iFolder Non disponibile </content>
</topic>

<topic>
  <title>Funzioni principali di iFolder</title>
  <url>../keyfeatures.html</url>
  <content>Funzioni principali di iFolder Prima di iniziare a utilizzare iFolder, è importante conoscerne le seguenti funzioni principali: Condivisione in iFolder In genere, quando si lavora in più ubicazioni o in collaborazione con altri, è necessaria una gestione scrupolosa delle diverse versioni dei file. Con iFolder, la versione più recente dei file di un utente è sempre disponibile in qualsiasi computer in cui sia installato il client iFolder e sia stata creata una cartella iFolder associata ai file. iFolder consente inoltre di condividere più cartelle iFolder e i relativi contenuti con altri utenti autorizzati o gruppi LDAP. Per ulteriori informazioni sulle cartelle iFolder condivise, vedere . Il client iFolder supporta la condivisione mediante la sincronizzazione dei file tra più computer attraverso un server centrale e consente di: Condividere file tra più computer Condividere file con altri utenti Essere proprietari di più cartelle iFolder Partecipare a più cartelle iFolder messe in condivisione da altri Partecipare come proprietari o membri di cartelle iFolder a più conti Per lavorare con le cartelle iFolder si può utilizzare direttamente un manager di file o il browser delle cartelle iFolder incluso nel client. Nella cartella iFolder è possibile impostare qualsiasi struttura di sottodirectory, a seconda delle esigenze personali o aziendali. La struttura di sottodirectory è costante tra tutte le cartelle iFolder partecipanti. Cartelle iFolder condivise Una cartella iFolder è una directory locale i cui file vengono condivisi e sincronizzati in modo selettivo tramite un server centrale con un gruppo di utenti specificato dall’utente. Tutti i membri iFolder possono accedere ai file memorizzati nella cartella iFolder e, se in possesso dei diritti appropriati, modificarli. È possibile accedere alle cartelle iFolder da diverse workstation e condividerle con singoli utenti e gruppi LDAP. Sarà l’utente a decidere i partecipanti a ciascuna cartella e il livello di accesso di ciascun membro. Analogamente, è possibile partecipare alle cartelle iFolder condivise di proprietà di altri utenti del proprio ambiente di collaborazione. Quando si condivide una cartella iFolder, gli utenti che dispongono di autorizzazioni di scrittura possono modificare la struttura di directory e le modifiche verranno applicate a tutte le copie della cartella. Gli utenti possono archiviare la cartella iFolder condivisa in qualsiasi ubicazione nel computer locale a condizione che i requisiti indicati in siano soddisfatti. Diritti di accesso a una cartella iFolder Il client iFolder supporta il proprietario e tre livelli di accesso per i membri di una cartella iFolder: I membri di un gruppo LDAP ereditano i diritti di accesso impostati per il gruppo. Proprietario: Solo un utente può essere il proprietario di una cartella iFolder; ed è in genere colui che crea la cartella. Il proprietario può utilizzare il client iFolder per trasferire la proprietà a un altro membro della cartella iFolder. Il proprietario di una cartella iFolder dispone del diritto di controllo completo, L'utente ha accesso in lettura/scrittura alla cartella, gestisce l’appartenenza e i diritti di accesso dei membri e può revocare il diritto di controllo completo a qualsiasi membro. Se un gruppo LDAP è proprietario di cartelle iFolder, tutti i membri del gruppo dispongono del diritto di controllo completo. Controllo completo: Membro della cartella iFolder condivisa che dispone del diritto di accesso a controllo completo. Il membro dispone di accesso in lettura/scrittura alla cartella iFolder e gestisce l’appartenenza e i diritti di accesso degli altri utenti, tranne quelli del proprietario. Lettura/scrittura: Membro della cartella iFolder condivisa con diritto di accesso in lettura/scrittura alle directory e ai file della cartella iFolder. Può modificare un file e le modifiche locali verranno sincronizzate con le copie degli altri membri della cartella iFolder. Sola lettura: Membro della cartella iFolder condivisa con diritto di accesso in sola lettura alle directory e ai file della cartella. Può modificare un file, ma le modifiche locali non verranno sincronizzate con le copie degli altri membri della cartella iFolder. Qualsiasi utente iFolder o gruppo LDAP può essere proprietario di alcune cartelle iFolder e membro di altre. Come proprietario, dispone sempre del diritto di controllo completo, mentre, in qualità di membro, il livello di accesso a ciascuna cartella iFolder condivisa può variare a seconda del livello di accesso concesso da un membro con diritto di controllo completo. Sincronizzazione dei file Quando si è connessi al server, iFolder può sincronizzare l'appartenenza e i file in background mentre si lavora. Durante la configurazione di un conto iFolder, è possibile abilitare l'opzione Memorizza password per consentire la memorizzazione della password nel computer in uso. Al successivo avvio di iFolder, verranno eseguite la connessione automatica al server e la sincronizzazione dei dati senza alcuna richiesta della password. Il client iFolder può essere configurato in modo che venga eseguito automaticamente ogni volta che si esegue il login all’ambiente desktop del computer. La sessione verrà eseguita in background mentre si modificano i file nelle cartelle iFolder locali, così da rilevare e registrare le modifiche apportate. È possibile sincronizzare i file manualmente o a intervalli specificati. In iFolder sono inoltre disponibili funzionalità di sincronizzazione differenziale. Quando vengono apportate modifiche a un file di una cartella iFolder, la sincronizzazione con il server ha come oggetto solo le differenze tra le versioni dei file. In altre parole, la sincronizzazione differenziale recupera solo gli aggiornamenti successivi all'ultima sincronizzazione tra il client iFolder e il server. In questo modo l'efficienza risulta migliorata, poiché vengono ridotti i tempi di sincronizzazione. Migrazione Novell iFolder fornisce una semplice interfaccia utente per la migrazione lato client da iFolder2.x a iFolder 3.6 e versione successiva. La procedura Migration Wizard fornita nel client iFolder consente di eseguire la migrazione della versione iFolder 2 esistente. x a iFolder 3.6 e successivamente in modo più semplice e rapido. Per ulteriori informazioni, vedere . Cifratura In iFolder sono disponibili funzionalità per la sicurezza avanzate che consentono di proteggere i file iFolder riservati da accessi intenzionali o non intenzionali da parte di utenti non autorizzati. In passato, la sicurezza dei dati sul lato server non era garantita e a questi poteva accedere l'amministratore o qualunque altro utente non autorizzato in grado di accedere al server. Inoltre, se si accede ai file iFolder tramite un provider di servizi Internet (ISP), esiste il rischio che personale non autorizzato possa inavvertitamente accedere a file riservati. Ora è possibile cifrare e salvare i file memorizzati nel server e utilizzare una stringa di cifratura personale per recuperare i dati. Se si dimentica la stringa di cifratura, l'agente di recupero selezionato durante la creazione della cartella iFolder cifrata consente di recuperare i dati. Non è possibile condividere le cartelle iFolder cifrate. Per ulteriori informazioni sulla cifratura, vedere . Upgrade Novell iFolder consente di eseguire facilmente l'upgrade da iFolder 3. x al client iFolder per Novell iFolder 3.6 e versioni successive Per ulteriori informazioni, vedere . Fondi Con la fusione, è possibile consolidare i dati delle cartelle iFolder e ridurre il tempo necessario per il trasferimento dei dati tra il server e il client iFolder. La fusione consente inoltre di spostare una cartella esistente in un'altra ubicazione nel computer client. Per ulteriori informazioni, vedere . Cartella iFolder di default In iFolder è possibile specificare una cartella iFolder di default durante la configurazione di un nuovo conto. In fase di configurazione di un nuovo conto, viene automaticamente verificata la presenza di una cartella iFolder di default e, se questa non già stata creata, viene chiesto di crearla. Se la cartella esiste già, verrà richiesto di scaricarla. È anche possibile ignorare entrambe queste opzioni. Per ulteriori informazioni, vedere in . Accesso Web avanzato iFolder offre un'interfaccia Web avanzata che consente di accedere ai file iFolder memorizzati in server remoti. Grazie alla console di accesso Web è possibile utilizzare un browser Web per accedere ai file nel server iFolder da qualsiasi workstation priva di client iFolder. L'interfaccia di accesso Web offre le stesse funzionalità del client iFolder. Rispetto alle versioni precedenti, iFolder 3.6 e le versioni successive consentono di creare, sfogliare, condividere, caricare e cancellare cartelle iFolder tramite la console di accesso Web. Le funzionalità di accesso Web risultano utili anche per gli utenti mobili. Log di sincronizzazione Nel log di sincronizzazione vengono visualizzate le informazioni sulle attività iFolder eseguite in background, relative ad esempio al caricamento e allo scaricamento di file per le diverse cartelle iFolder, alle violazioni delle policy, ai file esclusi e a quelli non sincronizzati. </content>
</topic>

<topic>
  <title>Operazione successiva</title>
  <url>../ovwnext.html</url>
  <content>Operazione successiva Per informazioni sulla configurazione per l'uso del client iFolder, vedere gli argomenti seguenti: </content>
</topic>

<topic>
  <title>Gestione dei conti e delle preferenze di iFolder</title>
  <url>../accountsprefs.html</url>
  <content>Gestione dei conti e delle preferenze di iFolder In questa sezione viene illustrato come configurare gli account iFolder e gestire le preferenze per il client iFolder. </content>
</topic>

<topic>
  <title>Avvio del client iFolder</title>
  <url>../startclient.html</url>
  <content>Avvio del client iFolder Quando iFolder è in esecuzione, l'icona Servizi iFolder viene visualizzata nell'area di notifica della barra delle applicazioni. iFolder è integrato nell'ambiente desktop. Il simbolo di iFolder (una “i” di colore verde) viene visualizzato sulle cartelle iFolder quando esse vengono visualizzate in un manager di file, sul desktop o nel browser delle cartelle iFolder. Le cartelle iFolder cifrate sono indicate dal simbolo (cartella bloccata). Affinché l'icona Servizi iFolder sia visualizzata quando iFolder è in esecuzione, è necessario abilitare l'area di notifica della barra delle applicazioni. È possibile utilizzare i file memorizzati nelle cartelle iFolder locali in qualunque momento. Quando il client iFolder è in esecuzione, le modifiche apportate ai dati iFolder vengono registrate in tempo reale. Se si apportano modifiche ai dati iFolder locali quando iFolder non è in esecuzione, queste verranno identificate e registrate al successivo avvio di iFolder. Quando iFolder non è in esecuzione, le cartelle vengono visualizzate nel manager di file o sul desktop. È consentito accedere ai file della copia locale di una cartella iFolder, ma non è possibile gestire le cartelle iFolder. Inoltre, per creare una cartella iFolder o eseguire la sincronizzazione dei relativi file è necessario eseguire il login a un conto. Durante la creazione di un conto, il login dell'utente avviene tramite SSL. Quando viene richiesto di accettare il certificato del server, è necessario convalidare il certificato e accettarlo affinché la connessione abbia esito positivo. Per informazioni sull'arresto del client iFolder, vedere . Linux Avvio automatico di iFolder al login Per abilitare l'avvio automatico di iFolder quando si esegue il login al desktop, effettuare una delle operazioni seguenti: Nel menu delle applicazioni, fare clic su Altre applicazioni , fare clic con il pulsante destro del mouse su iFolder e scegliere Aggiungi ai programmi di avvio dal menu. Accertarsi che iFolder sia in esecuzione quando si esegue il logout, quindi salvare le impostazioni di sessione. Selezionare questa opzione di sessione quando si esegue il login al desktop. Per aggiungere iFolder come programma di avvio quando si esegue il login al computer, è anche possibile aprire una finestra del terminale, eseguire il login come utente root , quindi eseguire /opt/gnome/bin/gnome-session-properties . Per disabilitare l'avvio automatico di iFolder al login, effettuare una delle operazioni seguenti: Aprire il menu delle applicazioni, fare clic con il pulsante destro del mouse su iFolder 3 e selezionare Rimuovi dai programmi di avvio . Accertarsi che iFolder non sia in esecuzione quando si esegue il logout, quindi salvare le impostazioni di sessione. Selezionare questa opzione di sessione quando si esegue il login al desktop. Avvio manuale di iFolder Eseguire il login al computer con l’identità utente Linux locale che si desidera utilizzare per la creazione delle cartelle iFolder. Per avviare iFolder, utilizzare uno dei seguenti metodi: Nella barra dei task, aprire il menu delle applicazioni, fare clic su Altre applicazioni , individuare iFolder 3 scorrendo l'elenco di opzioni disponibili, fare clic con il pulsante destro del mouse sull'applicazione e scegliere Avvia iFolder 3 . Aprire una shell del terminale e digitare: /usr/bin/ifolder Windows Avvio automatico di iFolder al login Per abilitare l'avvio automatico di iFolder quando si esegue il login al desktop: Fare clic con il pulsante destro del mouse sull'icona Servizi iFolder e scegliere Preferenze per passare alla scheda Generale della finestra di dialogo Preferenze di iFolder. Selezionare Avvia iFolder al login al desktop e fare clic su Applica . Fare clic su OK per chiudere la finestra di dialogo Preferenze di iFolder. Per disabilitare l'avvio automatico di iFolder quando si esegue il login al desktop: Fare clic con il pulsante destro del mouse sull'icona Servizi iFolder e scegliere Preferenze per aprire la scheda Generale della finestra di dialogo Preferenze di iFolder. Deselezionare Avvia iFolder al login al desktop e fare clic su Applica . Fare clic su OK per chiudere la finestra di dialogo Preferenze di iFolder. Avvio manuale di iFolder Eseguire il login al computer con l’identità locale dell’utente Windows che si desidera utilizzare per la creazione delle cartelle iFolder. Se iFolder non viene avviato automaticamente dopo il login, avviarlo facendo clic su Start Programmi iFolder 3 , quindi selezionare l'applicazione Client iFolder 3 . Macintosh Avvio automatico di iFolder al login Per abilitare l'avvio automatico di iFolder quando si esegue il login al computer Macintosh, aggiungere iFolder agli elementi di avvio . Avviare iFolder. Nel Dock, fare clic con il pulsante destro del mouse sull'icona iFolder e scegliere l'opzione per l'avvio al login . oppure Nel Dock, premere il tasto CTRL, fare clic sull'icona iFolder, quindi scegliere l'opzione per l'avvio al login . Per disabilitare l'avvio automatico di iFolder, rimuovere iFolder dagli elementi di avvio . Nel Dock, fare clic con il pulsante destro del mouse sull'icona iFolder e deselezionare l'opzione per l'avvio al login . oppure Nel Dock, fare clic con il pulsante destro del mouse oppure premere CTRL e fare clic sull'icona iFolder e deselezionare l'opzione per l'avvio al login . Avvio manuale di iFolder Eseguire il login al computer con l’identità utente Macintosh locale che si desidera utilizzare per la creazione delle cartelle iFolder. Per avviare iFolder, utilizzare uno dei seguenti metodi: Aprire la directory delle applicazioni in Macintosh HD , selezionare Applicazioni , quindi fare doppio clic su iFolder 3 . Digitare iFolder in Spotlight (pulsante Apple + Barra spaziatrice oppure clic sull'icona della lente di ingrandimento in alto a destra), quindi fare clic su iFolder 3 in Applicazioni. Aprire una shell terminale, eseguire il login come utente root, quindi immettere /Applications/iFolder 3.app/Contents/MacOS/iFolder 3 </content>
</topic>

<topic>
  <title>Configurazione di un conto iFolder</title>
  <url>../accounts.html</url>